//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;

namespace CSIPKeyInGUI.EntityLayer
{

    /// <summary>
    /// iPASS
    /// </summary>
    [Serializable()]
    [AttributeTable("iPASS")]
    public class EntityiPASS : Entity
    {
        private Guid _Newid;

        /// <summary>
        /// Newid
        /// </summary>
        public static Guid M_Newid = Guid.NewGuid();

        private string _Card_No;

        /// <summary>
        /// Card_No
        /// </summary>
        public static string M_Card_No = "Card_No";

        private string _Eng_Name;

        /// <summary>
        /// Eng_Name
        /// </summary>
        public static string M_Eng_Name = "Eng_Name";

        private string _GetCard_code;

        /// <summary>
        /// GetCard_code
        /// </summary>
        public static string M_GetCard_code = "GetCard_code";

        private string _Member_No;

        /// <summary>
        /// Member_No
        /// </summary>
        public static string M_Member_No = "Member_No";

        private string _ReIssue_Type;

        /// <summary>
        /// ReIssue_Type
        /// </summary>
        public static string M_ReIssue_Type = "ReIssue_Type";

        private string _KeyIn_Flag;

        /// <summary>
        /// KeyIn_Flag
        /// </summary>
        public static string M_KeyIn_Flag = "KeyIn_Flag";

        private string _Upload_Flag;

        /// <summary>
        /// Upload_Flag
        /// </summary>
        public static string M_Upload_Flag = "Upload_Flag";

        private string _user_id;

        /// <summary>
        /// user_id
        /// </summary>
        public static string M_user_id = "user_id";

        private string _mod_date;

        /// <summary>
        /// mod_date
        /// </summary>
        public static string M_mod_date = "mod_date";

        private string _Card_Type;

        /// <summary>
        /// Card_Type
        /// </summary>
        public static string M_Card_Type = "Card_Type";

        private string _Co_Marketing_Com;

        /// <summary>
        /// Co_Marketing_Com
        /// </summary>
        public static string M_Co_Marketing_Com = "Co_Marketing_Com";

        private string _Co_Marketing;

        /// <summary>
        /// Co_Marketing
        /// </summary>
        public static string M_Co_Marketing = "Co_Marketing";

        private string _ISAuto_Load;

        /// <summary>
        /// Co_Marketing
        /// </summary>
        public static string M_ISAuto_Load = "ISAuto_Load";

        private string _Chinese_Name;

        /// <summary>
        /// Chinese_Name
        /// </summary>
        public static string M_Chinese_Name = "Chinese_Name";

        private string _Create_User;

        /// <summary>
        /// Create_User
        /// </summary>
        public static string M_Create_User = "Create_User";

        private DateTime _Create_DateTime;

        /// <summary>
        /// Create_DateTime
        /// </summary>
        public static string M_Create_DateTime = "Create_DateTime";

        private string _Modify_User;

        /// <summary>
        /// Modify_User
        /// </summary>
        public static string M_Modify_User = "Modify_User";

        private DateTime _Modify_DateTime;

        /// <summary>
        /// Modify_DateTime
        /// </summary>
        public static string M_Modify_DateTime = "Modify_DateTime";

        /* -------------------------------------------------------------------------------------------------------- */

        /// <summary>
        /// Newid
        /// </summary>
        [AttributeField("Newid", "System.GUID", false, false, false, "Guid")]
        public Guid Newid
        {
            get
            {
                return this._Newid;
            }
            set
            {
                this._Newid = value;
            }
        }

        /// <summary>
        /// Card_No
        /// </summary>
        [AttributeField("Card_No", "System.String", false, false, false, "String")]
        public string Card_No
        {
            get
            {
                return this._Card_No;
            }
            set
            {
                this._Card_No = value;
            }
        }

        /// <summary>
        /// Eng_Name
        /// </summary>
        [AttributeField("Eng_Name", "System.String", false, false, false, "String")]
        public string Eng_Name
        {
            get
            {
                return this._Eng_Name;
            }
            set
            {
                this._Eng_Name = value;
            }
        }

        /// <summary>
        /// GetCard_code
        /// </summary>
        [AttributeField("GetCard_code", "System.String", false, false, false, "String")]
        public string GetCard_code
        {
            get
            {
                return this._GetCard_code;
            }
            set
            {
                this._GetCard_code = value;
            }
        }

        /// <summary>
        /// Member_No
        /// </summary>
        [AttributeField("Member_No", "System.String", false, false, false, "String")]
        public string Member_No
        {
            get
            {
                return this._Member_No;
            }
            set
            {
                this._Member_No = value;
            }
        }

        /// <summary>
        /// ReIssue_Type
        /// </summary>
        [AttributeField("ReIssue_Type", "System.String", false, false, false, "String")]
        public string ReIssue_Type
        {
            get
            {
                return this._ReIssue_Type;
            }
            set
            {
                this._ReIssue_Type = value;
            }
        }

        /// <summary>
        /// KeyIn_Flag
        /// </summary>
        [AttributeField("KeyIn_Flag", "System.String", false, false, false, "String")]
        public string KeyIn_Flag
        {
            get
            {
                return this._KeyIn_Flag;
            }
            set
            {
                this._KeyIn_Flag = value;
            }
        }

        /// <summary>
        /// Upload_Flag
        /// </summary>
        [AttributeField("Upload_Flag", "System.String", false, false, false, "String")]
        public string Upload_Flag
        {
            get
            {
                return this._Upload_Flag;
            }
            set
            {
                this._Upload_Flag = value;
            }
        }

        /// <summary>
        /// user_id
        /// </summary>
        [AttributeField("user_id", "System.String", false, false, false, "String")]
        public string user_id
        {
            get
            {
                return this._user_id;
            }
            set
            {
                this._user_id = value;
            }
        }

        /// <summary>
        /// mod_date
        /// </summary>
        [AttributeField("mod_date", "System.String", false, false, false, "String")]
        public string mod_date
        {
            get
            {
                return this._mod_date;
            }
            set
            {
                this._mod_date = value;
            }
        }

        /// <summary>
        /// Card_Type
        /// </summary>
        [AttributeField("Card_Type", "System.String", false, false, false, "String")]
        public string Card_Type
        {
            get
            {
                return this._Card_Type;
            }
            set
            {
                this._Card_Type = value;
            }
        }

        /// <summary>
        /// Co_Marketing_Com
        /// </summary>
        [AttributeField("Co_Marketing_Com", "System.String", false, false, false, "String")]
        public string Co_Marketing_Com
        {
            get
            {
                return this._Co_Marketing_Com;
            }
            set
            {
                this._Co_Marketing_Com = value;
            }
        }

        /// <summary>
        /// Co_Marketing
        /// </summary>
        [AttributeField("Co_Marketing", "System.String", false, false, false, "String")]
        public string Co_Marketing
        {
            get
            {
                return this._Co_Marketing;
            }
            set
            {
                this._Co_Marketing = value;
            }
        }

        /// <summary>
        /// ISAuto_Load
        /// </summary>
        [AttributeField("ISAuto_Load", "System.String", false, false, false, "String")]
        public string ISAuto_Load
        {
            get
            {
                return this._ISAuto_Load;
            }
            set
            {
                this._ISAuto_Load = value;
            }
        }

        /// <summary>
        /// Chinese_Name
        /// </summary>
        [AttributeField("Chinese_Name", "System.String", false, false, false, "String")]
        public string Chinese_Name
        {
            get
            {
                return this._Chinese_Name;
            }
            set
            {
                this._Chinese_Name = value;
            }
        }

        /// <summary>
        /// Create_User
        /// </summary>
        [AttributeField("Create_User", "System.String", false, false, false, "String")]
        public string Create_User
        {
            get
            {
                return this._Create_User;
            }
            set
            {
                this._Create_User = value;
            }
        }

        /// <summary>
        /// Create_DateTime
        /// </summary>
        [AttributeField("Create_DateTime", "System.DateTime", false, false, false, "DateTime")]
        public DateTime Create_DateTime
        {
            get
            {
                return this._Create_DateTime;
            }
            set
            {
                this._Create_DateTime = value;
            }
        }

        /// <summary>
        /// Modify_User
        /// </summary>
        [AttributeField("Modify_User", "System.String", false, false, false, "String")]
        public string Modify_User
        {
            get
            {
                return this._Modify_User;
            }
            set
            {
                this._Modify_User = value;
            }
        }

        /// <summary>
        /// Modify_DateTime
        /// </summary>
        [AttributeField("Modify_DateTime", "System.DateTime", false, false, false, "DateTime")]
        public DateTime Modify_DateTime
        {
            get
            {
                return this._Modify_DateTime;
            }
            set
            {
                this._Modify_DateTime = value;
            }
        }

    }

    /// <summary>
    /// iPASS
    /// </summary>
    [Serializable()]
    public class EntityiPASSSet : EntitySet<EntityiPASS>
    {
    }

}
