//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPKeyInGUI.EntityLayer
{
    
    
    /// <summary>
    /// batch
    /// </summary>
    [Serializable()]
    [AttributeTable("batch")]
    public class EntityBATCH : Entity
    {
        
        private string _Batch_no;
        
        /// <summary>
        /// Batch_no
        /// </summary>
        public static string M_Batch_no = "Batch_no";
        
        private string _dateSend;
        
        /// <summary>
        /// dateSend
        /// </summary>
        public static string M_dateSend = "dateSend";
        
        private string _dateInput;
        
        /// <summary>
        /// dateInput
        /// </summary>
        public static string M_dateInput = "dateInput";
        
        private string _dateReceive;
        
        /// <summary>
        /// dateReceive
        /// </summary>
        public static string M_dateReceive = "dateReceive";
        
        private string _P02_flag;
        
        /// <summary>
        /// P02_flag
        /// </summary>
        public static string M_P02_flag = "P02_flag";
        
        private string _R02_flag;
        
        /// <summary>
        /// R02_flag
        /// </summary>
        public static string M_R02_flag = "R02_flag";
        
        private string _R02DateReceive;
        
        /// <summary>
        /// R02DateReceive
        /// </summary>
        public static string M_R02DateReceive = "R02DateReceive";
        
        private string _TotalCount;
        
        /// <summary>
        /// TotalCount
        /// </summary>
        public static string M_TotalCount = "TotalCount";
        
        /// <summary>
        /// Batch_no
        /// </summary>
        [AttributeField("Batch_no", "System.String", false, false, false, "String")]
        public string Batch_no
        {
            get
            {
                return this._Batch_no;
            }
            set
            {
                this._Batch_no = value;
            }
        }
        
        /// <summary>
        /// dateSend
        /// </summary>
        [AttributeField("dateSend", "System.String", false, false, false, "String")]
        public string dateSend
        {
            get
            {
                return this._dateSend;
            }
            set
            {
                this._dateSend = value;
            }
        }
        
        /// <summary>
        /// dateInput
        /// </summary>
        [AttributeField("dateInput", "System.String", false, false, false, "String")]
        public string dateInput
        {
            get
            {
                return this._dateInput;
            }
            set
            {
                this._dateInput = value;
            }
        }
        
        /// <summary>
        /// dateReceive
        /// </summary>
        [AttributeField("dateReceive", "System.String", false, false, false, "String")]
        public string dateReceive
        {
            get
            {
                return this._dateReceive;
            }
            set
            {
                this._dateReceive = value;
            }
        }
        
        /// <summary>
        /// P02_flag
        /// </summary>
        [AttributeField("P02_flag", "System.String", false, false, false, "String")]
        public string P02_flag
        {
            get
            {
                return this._P02_flag;
            }
            set
            {
                this._P02_flag = value;
            }
        }
        
        /// <summary>
        /// R02_flag
        /// </summary>
        [AttributeField("R02_flag", "System.String", false, false, false, "String")]
        public string R02_flag
        {
            get
            {
                return this._R02_flag;
            }
            set
            {
                this._R02_flag = value;
            }
        }
        
        /// <summary>
        /// R02DateReceive
        /// </summary>
        [AttributeField("R02DateReceive", "System.String", false, false, false, "String")]
        public string R02DateReceive
        {
            get
            {
                return this._R02DateReceive;
            }
            set
            {
                this._R02DateReceive = value;
            }
        }
        
        /// <summary>
        /// TotalCount
        /// </summary>
        [AttributeField("TotalCount", "System.String", false, false, false, "String")]
        public string TotalCount
        {
            get
            {
                return this._TotalCount;
            }
            set
            {
                this._TotalCount = value;
            }
        }
    }
    
    /// <summary>
    /// batch
    /// </summary>
    [Serializable()]
    public class EntityBATCHSet : EntitySet<EntityBATCH>
    {
    }
}
