//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPKeyInGUI.EntityLayer
{
    
    
    /// <summary>
    /// Ach_Rtn_Info
    /// </summary>
    [Serializable()]
    [AttributeTable("Ach_Rtn_Info")]
    public class EntityACH_RTN_INFO : Entity
    {
        
        private string _Ach_Rtn_Code;
        
        /// <summary>
        /// Ach_Rtn_Code
        /// </summary>
        public static string M_Ach_Rtn_Code = "Ach_Rtn_Code";
        
        private string _Ach_Rtn_Msg;
        
        /// <summary>
        /// Ach_Rtn_Msg
        /// </summary>
        public static string M_Ach_Rtn_Msg = "Ach_Rtn_Msg";
        
        /// <summary>
        /// Ach_Rtn_Code
        /// </summary>
        [AttributeField("Ach_Rtn_Code", "System.String", false, false, false, "String")]
        public string Ach_Rtn_Code
        {
            get
            {
                return this._Ach_Rtn_Code;
            }
            set
            {
                this._Ach_Rtn_Code = value;
            }
        }
        
        /// <summary>
        /// Ach_Rtn_Msg
        /// </summary>
        [AttributeField("Ach_Rtn_Msg", "System.String", false, false, false, "String")]
        public string Ach_Rtn_Msg
        {
            get
            {
                return this._Ach_Rtn_Msg;
            }
            set
            {
                this._Ach_Rtn_Msg = value;
            }
        }
    }
    
    /// <summary>
    /// Ach_Rtn_Info
    /// </summary>
    [Serializable()]
    public class EntityACH_RTN_INFOSet : EntitySet<EntityACH_RTN_INFO>
    {
    }
}
