//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.3603
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPKeyInGUI.EntityLayer
{
    
    
    /// <summary>
    /// Redeem3270
    /// </summary>
    [Serializable()]
    [AttributeTable("Redeem3270")]
    public class EntityRedeem3270 : Entity
    {

        private int _ID;

        /// <summary>
        /// ID
        /// </summary>
        public static string M_ID = "ID";
        

        private string _RECEIVE_NUMBER;

        /// <summary>
        /// RECEIVE_NUMBER
        /// </summary>
        public static string M_RECEIVE_NUMBER = "RECEIVE_NUMBER";
        
        private string _USER_ID;
        
        /// <summary>
        /// USER_ID
        /// </summary>
        public static string M_USER_ID = "USER_ID";
        
        private string _FUNCTION_CODE;
        
        /// <summary>
        /// FUNCTION_CODE
        /// </summary>
        public static string M_FUNCTION_CODE = "FUNCTION_CODE";
        
        private string _MSG_SEQ;
        
        /// <summary>
        /// MSG_SEQ
        /// </summary>
        public static string M_MSG_SEQ = "MSG_SEQ";
        
        private string _MSG_ERR;
        
        /// <summary>
        /// MSG_ERR
        /// </summary>
        public static string M_MSG_ERR = "MSG_ERR";
        
        private string _IN_ORG;
        
        /// <summary>
        /// IN_ORG
        /// </summary>
        public static string M_IN_ORG = "IN_ORG";
        
        private string _IN_MERCHANT;
        
        /// <summary>
        /// IN_MERCHANT
        /// </summary>
        public static string M_IN_MERCHANT = "IN_MERCHANT";
        
        private string _IN_PROD_CODE;
        
        /// <summary>
        /// IN_PROD_CODE
        /// </summary>
        public static string M_IN_PROD_CODE = "IN_PROD_CODE";
        
        private string _IN_CARD_TYPE;
        
        /// <summary>
        /// IN_CARD_TYPE
        /// </summary>
        public static string M_IN_CARD_TYPE = "IN_CARD_TYPE";
        
        private string _PROGID;
        
        /// <summary>
        /// PROGID
        /// </summary>
        public static string M_PROGID = "PROGID";
        
        private string _MER_RATE;
        
        /// <summary>
        /// MER_RATE
        /// </summary>
        public static string M_MER_RATE = "MER_RATE";
        
        private string _LIMITR;
        
        /// <summary>
        /// LIMITR
        /// </summary>
        public static string M_LIMITR = "LIMITR";
        
        private string _CHPOINT;
        
        /// <summary>
        /// CHPOINT
        /// </summary>
        public static string M_CHPOINT = "CHPOINT";
        
        private string _CHAMT;
        
        /// <summary>
        /// CHAMT
        /// </summary>
        public static string M_CHAMT = "CHAMT";
        
        private string _USER_EXIT;
        
        /// <summary>
        /// USER_EXIT
        /// </summary>
        public static string M_USER_EXIT = "USER_EXIT";
        
        private string _CYLCO;
        
        /// <summary>
        /// CYLCO
        /// </summary>
        public static string M_CYLCO = "CYLCO";
        
        private string _STARTU;
        
        /// <summary>
        /// STARTU
        /// </summary>
        public static string M_STARTU = "STARTU";
        
        private string _ENDU;
        
        /// <summary>
        /// ENDU
        /// </summary>
        public static string M_ENDU = "ENDU";
        
        private string _LIMITU;
        
        /// <summary>
        /// LIMITU
        /// </summary>
        public static string M_LIMITU = "LIMITU";
        
        private string _CHPOINTU;
        
        /// <summary>
        /// CHPOINTU
        /// </summary>
        public static string M_CHPOINTU = "CHPOINTU";
        
        private string _CHAMTU;
        
        /// <summary>
        /// CHAMTU
        /// </summary>
        public static string M_CHAMTU = "CHAMTU";
        
        private string _BIRTH;
        
        /// <summary>
        /// BIRTH
        /// </summary>
        public static string M_BIRTH = "BIRTH";
        
        private string _STARTB;
        
        /// <summary>
        /// STARTB
        /// </summary>
        public static string M_STARTB = "STARTB";
        
        private string _ENDB;
        
        /// <summary>
        /// ENDB
        /// </summary>
        public static string M_ENDB = "ENDB";
        
        private string _LIMITB;
        
        /// <summary>
        /// LIMITB
        /// </summary>
        public static string M_LIMITB = "LIMITB";
        
        private string _CHPOINTB;
        
        /// <summary>
        /// CHPOINTB
        /// </summary>
        public static string M_CHPOINTB = "CHPOINTB";
        
        private string _CHAMTB;
        
        /// <summary>
        /// CHAMTB
        /// </summary>
        public static string M_CHAMTB = "CHAMTB";
        
        private string _SEND_FLAG;
        
        /// <summary>
        /// SEND_FLAG
        /// </summary>
        public static string M_SEND_FLAG = "SEND_FLAG";

        /// <summary>
        /// ID
        /// </summary>
        [AttributeField("ID", "System.Int32", false, true, true, "Int32")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this._ID = value;
            }
        }
        
        /// <summary>
        /// RECEIVE_NUMBER
        /// </summary>
        [AttributeField("RECEIVE_NUMBER", "System.String", false, false, false, "String")]
        public string RECEIVE_NUMBER
        {
            get
            {
                return this._RECEIVE_NUMBER;
            }
            set
            {
                this._RECEIVE_NUMBER = value;
            }
        }
        
        /// <summary>
        /// USER_ID
        /// </summary>
        [AttributeField("USER_ID", "System.String", false, false, false, "String")]
        public string USER_ID
        {
            get
            {
                return this._USER_ID;
            }
            set
            {
                this._USER_ID = value;
            }
        }
        
        /// <summary>
        /// FUNCTION_CODE
        /// </summary>
        [AttributeField("FUNCTION_CODE", "System.String", false, false, false, "String")]
        public string FUNCTION_CODE
        {
            get
            {
                return this._FUNCTION_CODE;
            }
            set
            {
                this._FUNCTION_CODE = value;
            }
        }
        
        /// <summary>
        /// MSG_SEQ
        /// </summary>
        [AttributeField("MSG_SEQ", "System.String", false, false, false, "String")]
        public string MSG_SEQ
        {
            get
            {
                return this._MSG_SEQ;
            }
            set
            {
                this._MSG_SEQ = value;
            }
        }
        
        /// <summary>
        /// MSG_ERR
        /// </summary>
        [AttributeField("MSG_ERR", "System.String", false, false, false, "String")]
        public string MSG_ERR
        {
            get
            {
                return this._MSG_ERR;
            }
            set
            {
                this._MSG_ERR = value;
            }
        }
        
        /// <summary>
        /// IN_ORG
        /// </summary>
        [AttributeField("IN_ORG", "System.String", false, false, false, "String")]
        public string IN_ORG
        {
            get
            {
                return this._IN_ORG;
            }
            set
            {
                this._IN_ORG = value;
            }
        }
        
        /// <summary>
        /// IN_MERCHANT
        /// </summary>
        [AttributeField("IN_MERCHANT", "System.String", false, false, false, "String")]
        public string IN_MERCHANT
        {
            get
            {
                return this._IN_MERCHANT;
            }
            set
            {
                this._IN_MERCHANT = value;
            }
        }
        
        /// <summary>
        /// IN_PROD_CODE
        /// </summary>
        [AttributeField("IN_PROD_CODE", "System.String", false, false, false, "String")]
        public string IN_PROD_CODE
        {
            get
            {
                return this._IN_PROD_CODE;
            }
            set
            {
                this._IN_PROD_CODE = value;
            }
        }
        
        /// <summary>
        /// IN_CARD_TYPE
        /// </summary>
        [AttributeField("IN_CARD_TYPE", "System.String", false, false, false, "String")]
        public string IN_CARD_TYPE
        {
            get
            {
                return this._IN_CARD_TYPE;
            }
            set
            {
                this._IN_CARD_TYPE = value;
            }
        }
        
        /// <summary>
        /// PROGID
        /// </summary>
        [AttributeField("PROGID", "System.String", false, false, false, "String")]
        public string PROGID
        {
            get
            {
                return this._PROGID;
            }
            set
            {
                this._PROGID = value;
            }
        }
        
        /// <summary>
        /// MER_RATE
        /// </summary>
        [AttributeField("MER_RATE", "System.String", false, false, false, "String")]
        public string MER_RATE
        {
            get
            {
                return this._MER_RATE;
            }
            set
            {
                this._MER_RATE = value;
            }
        }
        
        /// <summary>
        /// LIMITR
        /// </summary>
        [AttributeField("LIMITR", "System.String", false, false, false, "String")]
        public string LIMITR
        {
            get
            {
                return this._LIMITR;
            }
            set
            {
                this._LIMITR = value;
            }
        }
        
        /// <summary>
        /// CHPOINT
        /// </summary>
        [AttributeField("CHPOINT", "System.String", false, false, false, "String")]
        public string CHPOINT
        {
            get
            {
                return this._CHPOINT;
            }
            set
            {
                this._CHPOINT = value;
            }
        }
        
        /// <summary>
        /// CHAMT
        /// </summary>
        [AttributeField("CHAMT", "System.String", false, false, false, "String")]
        public string CHAMT
        {
            get
            {
                return this._CHAMT;
            }
            set
            {
                this._CHAMT = value;
            }
        }
        
        /// <summary>
        /// USER_EXIT
        /// </summary>
        [AttributeField("USER_EXIT", "System.String", false, false, false, "String")]
        public string USER_EXIT
        {
            get
            {
                return this._USER_EXIT;
            }
            set
            {
                this._USER_EXIT = value;
            }
        }
        
        /// <summary>
        /// CYLCO
        /// </summary>
        [AttributeField("CYLCO", "System.String", false, false, false, "String")]
        public string CYLCO
        {
            get
            {
                return this._CYLCO;
            }
            set
            {
                this._CYLCO = value;
            }
        }
        
        /// <summary>
        /// STARTU
        /// </summary>
        [AttributeField("STARTU", "System.String", false, false, false, "String")]
        public string STARTU
        {
            get
            {
                return this._STARTU;
            }
            set
            {
                this._STARTU = value;
            }
        }
        
        /// <summary>
        /// ENDU
        /// </summary>
        [AttributeField("ENDU", "System.String", false, false, false, "String")]
        public string ENDU
        {
            get
            {
                return this._ENDU;
            }
            set
            {
                this._ENDU = value;
            }
        }
        
        /// <summary>
        /// LIMITU
        /// </summary>
        [AttributeField("LIMITU", "System.String", false, false, false, "String")]
        public string LIMITU
        {
            get
            {
                return this._LIMITU;
            }
            set
            {
                this._LIMITU = value;
            }
        }
        
        /// <summary>
        /// CHPOINTU
        /// </summary>
        [AttributeField("CHPOINTU", "System.String", false, false, false, "String")]
        public string CHPOINTU
        {
            get
            {
                return this._CHPOINTU;
            }
            set
            {
                this._CHPOINTU = value;
            }
        }
        
        /// <summary>
        /// CHAMTU
        /// </summary>
        [AttributeField("CHAMTU", "System.String", false, false, false, "String")]
        public string CHAMTU
        {
            get
            {
                return this._CHAMTU;
            }
            set
            {
                this._CHAMTU = value;
            }
        }
        
        /// <summary>
        /// BIRTH
        /// </summary>
        [AttributeField("BIRTH", "System.String", false, false, false, "String")]
        public string BIRTH
        {
            get
            {
                return this._BIRTH;
            }
            set
            {
                this._BIRTH = value;
            }
        }
        
        /// <summary>
        /// STARTB
        /// </summary>
        [AttributeField("STARTB", "System.String", false, false, false, "String")]
        public string STARTB
        {
            get
            {
                return this._STARTB;
            }
            set
            {
                this._STARTB = value;
            }
        }
        
        /// <summary>
        /// ENDB
        /// </summary>
        [AttributeField("ENDB", "System.String", false, false, false, "String")]
        public string ENDB
        {
            get
            {
                return this._ENDB;
            }
            set
            {
                this._ENDB = value;
            }
        }
        
        /// <summary>
        /// LIMITB
        /// </summary>
        [AttributeField("LIMITB", "System.String", false, false, false, "String")]
        public string LIMITB
        {
            get
            {
                return this._LIMITB;
            }
            set
            {
                this._LIMITB = value;
            }
        }
        
        /// <summary>
        /// CHPOINTB
        /// </summary>
        [AttributeField("CHPOINTB", "System.String", false, false, false, "String")]
        public string CHPOINTB
        {
            get
            {
                return this._CHPOINTB;
            }
            set
            {
                this._CHPOINTB = value;
            }
        }
        
        /// <summary>
        /// CHAMTB
        /// </summary>
        [AttributeField("CHAMTB", "System.String", false, false, false, "String")]
        public string CHAMTB
        {
            get
            {
                return this._CHAMTB;
            }
            set
            {
                this._CHAMTB = value;
            }
        }
        
        /// <summary>
        /// SEND_FLAG
        /// </summary>
        [AttributeField("SEND_FLAG", "System.String", false, false, false, "String")]
        public string SEND_FLAG
        {
            get
            {
                return this._SEND_FLAG;
            }
            set
            {
                this._SEND_FLAG = value;
            }
        }
    }
    
    /// <summary>
    /// Redeem3270
    /// </summary>
    [Serializable()]
    public class EntityRedeem3270Set : EntitySet<EntityRedeem3270>
    {
    }
}
