//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.3603
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPKeyInGUI.EntityLayer
{


    /// <summary>
    /// SHOP_PCAM
    /// </summary>
    [Serializable()]
    [AttributeTable("shop_pcam")]
    public class EntitySHOP_PCAM : Entity
    {

        private string _organization;

        /// <summary>
        /// organization
        /// </summary>
        public static string M_organization = "organization";

        private string _merchant_name;

        /// <summary>
        /// merchant_name
        /// </summary>
        public static string M_merchant_name = "merchant_name";

        private string _corp;

        /// <summary>
        /// corp
        /// </summary>
        public static string M_corp = "corp";

        private string _merchdba_name;

        /// <summary>
        /// merchdba_name
        /// </summary>
        public static string M_merchdba_name = "merchdba_name";

        private string _merchant_nbr;

        /// <summary>
        /// merchant_nbr
        /// </summary>
        public static string M_merchant_nbr = "merchant_nbr";

        private string _dba_city;

        /// <summary>
        /// dba_city
        /// </summary>
        public static string M_dba_city = "dba_city";

        private string _zip;

        /// <summary>
        /// zip
        /// </summary>
        public static string M_zip = "zip";

        private string _address1;

        /// <summary>
        /// address1
        /// </summary>
        public static string M_address1 = "address1";

        private string _address2;

        /// <summary>
        /// address2
        /// </summary>
        public static string M_address2 = "address2";

        private string _address3;

        /// <summary>
        /// address3
        /// </summary>
        public static string M_address3 = "address3";

        private string _address4;

        /// <summary>
        /// address4
        /// </summary>
        public static string M_address4 = "address4";

        private string _phone;

        /// <summary>
        /// phone
        /// </summary>
        public static string M_phone = "phone";

        private string _owner;

        /// <summary>
        /// owner
        /// </summary>
        public static string M_owner = "owner";

        private string _imp1;

        /// <summary>
        /// imp1
        /// </summary>
        public static string M_imp1 = "imp1";

        private string _pos1;

        /// <summary>
        /// pos1
        /// </summary>
        public static string M_pos1 = "pos1";

        private string _edc1;

        /// <summary>
        /// edc1
        /// </summary>
        public static string M_edc1 = "edc1";

        private string _imp2;

        /// <summary>
        /// imp2
        /// </summary>
        public static string M_imp2 = "imp2";

        private string _pos2;

        /// <summary>
        /// pos2
        /// </summary>
        public static string M_pos2 = "pos2";

        private string _edc2;

        /// <summary>
        /// edc2
        /// </summary>
        public static string M_edc2 = "edc2";

        private string _sales_name;

        /// <summary>
        /// sales_name
        /// </summary>
        public static string M_sales_name = "sales_name";

        private string _agent_bank;

        /// <summary>
        /// agent_bank
        /// </summary>
        public static string M_agent_bank = "agent_bank";

        private string _merchant_type;

        /// <summary>
        /// merchant_type
        /// </summary>
        public static string M_merchant_type = "merchant_type";

        private string _chain_store;

        /// <summary>
        /// chain_store
        /// </summary>
        public static string M_chain_store = "chain_store";

        private string _chain_merch;

        /// <summary>
        /// chain_merch
        /// </summary>
        public static string M_chain_merch = "chain_merch";

        private string _chain_level;

        /// <summary>
        /// chain_level
        /// </summary>
        public static string M_chain_level = "chain_level";

        private string _Source;

        /// <summary>
        /// Source
        /// </summary>
        public static string M_Source = "Source";

        private string _mcc_VISA;

        /// <summary>
        /// mcc_VISA
        /// </summary>
        public static string M_mcc_VISA = "mcc_VISA";

        private string _mcc_MC;

        /// <summary>
        /// mcc_MC
        /// </summary>
        public static string M_mcc_MC = "mcc_MC";

        private string _mcc_PL;

        /// <summary>
        /// mcc_PL
        /// </summary>
        public static string M_mcc_PL = "mcc_PL";

        private string _avg_tkt;

        /// <summary>
        /// avg_tkt
        /// </summary>
        public static string M_avg_tkt = "avg_tkt";

        private string _monthly_volume;

        /// <summary>
        /// monthly_volume
        /// </summary>
        public static string M_monthly_volume = "monthly_volume";

        private string _branch;

        /// <summary>
        /// branch
        /// </summary>
        public static string M_branch = "branch";

        private string _INT;

        /// <summary>
        /// INT
        /// </summary>
        public static string M_INT = "INT";

        private string _MAIL;

        /// <summary>
        /// MAIL
        /// </summary>
        public static string M_MAIL = "MAIL";

        private string _POS_CA;

        /// <summary>
        /// POS_CA
        /// </summary>
        public static string M_POS_CA = "POS_CA";

        private string _POS_MO;

        /// <summary>
        /// POS_MO
        /// </summary>
        public static string M_POS_MO = "POS_MO";

        private string _CH;

        /// <summary>
        /// CH
        /// </summary>
        public static string M_CH = "CH";

        private string _MC;

        /// <summary>
        /// MC
        /// </summary>
        public static string M_MC = "MC";

        private string _FileNo;

        /// <summary>
        /// FileNo
        /// </summary>
        public static string M_FileNo = "FileNo";

        private string _hold_stmt;

        /// <summary>
        /// hold_stmt
        /// </summary>
        public static string M_hold_stmt = "hold_stmt";

        private string _DDA_NO;

        /// <summary>
        /// DDA_NO
        /// </summary>
        public static string M_DDA_NO = "DDA_NO";

        private string _status1;

        /// <summary>
        /// status1
        /// </summary>
        public static string M_status1 = "status1";

        private string _status2;

        /// <summary>
        /// status2
        /// </summary>
        public static string M_status2 = "status2";

        private string _status3;

        /// <summary>
        /// status3
        /// </summary>
        public static string M_status3 = "status3";

        private string _status4;

        /// <summary>
        /// status4
        /// </summary>
        public static string M_status4 = "status4";

        private string _status5;

        /// <summary>
        /// status5
        /// </summary>
        public static string M_status5 = "status5";

        private string _status6;

        /// <summary>
        /// status6
        /// </summary>
        public static string M_status6 = "status6";

        private string _status7;

        /// <summary>
        /// status7
        /// </summary>
        public static string M_status7 = "status7";

        private string _status8;

        /// <summary>
        /// status8
        /// </summary>
        public static string M_status8 = "status8";

        private string _status9;

        /// <summary>
        /// status9
        /// </summary>
        public static string M_status9 = "status9";

        private string _status10;

        /// <summary>
        /// status10
        /// </summary>
        public static string M_status10 = "status10";

        private string _status11;

        /// <summary>
        /// status11
        /// </summary>
        public static string M_status11 = "status11";

        private string _status12;

        /// <summary>
        /// status12
        /// </summary>
        public static string M_status12 = "status12";

        private string _status13;

        /// <summary>
        /// status13
        /// </summary>
        public static string M_status13 = "status13";

        private string _status14;

        /// <summary>
        /// status14
        /// </summary>
        public static string M_status14 = "status14";

        private string _status15;

        /// <summary>
        /// status15
        /// </summary>
        public static string M_status15 = "status15";

        private string _dis_rate1;

        /// <summary>
        /// dis_rate1
        /// </summary>
        public static string M_dis_rate1 = "dis_rate1";

        private string _dis_rate2;

        /// <summary>
        /// dis_rate2
        /// </summary>
        public static string M_dis_rate2 = "dis_rate2";

        private string _dis_rate3;

        /// <summary>
        /// dis_rate3
        /// </summary>
        public static string M_dis_rate3 = "dis_rate3";

        private string _dis_rate4;

        /// <summary>
        /// dis_rate4
        /// </summary>
        public static string M_dis_rate4 = "dis_rate4";

        private string _dis_rate5;

        /// <summary>
        /// dis_rate5
        /// </summary>
        public static string M_dis_rate5 = "dis_rate5";

        private string _dis_rate6;

        /// <summary>
        /// dis_rate6
        /// </summary>
        public static string M_dis_rate6 = "dis_rate6";

        private string _dis_rate7;

        /// <summary>
        /// dis_rate7
        /// </summary>
        public static string M_dis_rate7 = "dis_rate7";

        private string _dis_rate8;

        /// <summary>
        /// dis_rate8
        /// </summary>
        public static string M_dis_rate8 = "dis_rate8";

        private string _dis_rate9;

        /// <summary>
        /// dis_rate9
        /// </summary>
        public static string M_dis_rate9 = "dis_rate9";

        private string _dis_rate10;

        /// <summary>
        /// dis_rate10
        /// </summary>
        public static string M_dis_rate10 = "dis_rate10";

        private string _dis_rate11;

        /// <summary>
        /// dis_rate11
        /// </summary>
        public static string M_dis_rate11 = "dis_rate11";

        private string _dis_rate12;

        /// <summary>
        /// dis_rate12
        /// </summary>
        public static string M_dis_rate12 = "dis_rate12";

        private string _dis_rate13;

        /// <summary>
        /// dis_rate13
        /// </summary>
        public static string M_dis_rate13 = "dis_rate13";

        private string _dis_rate14;

        /// <summary>
        /// dis_rate14
        /// </summary>
        public static string M_dis_rate14 = "dis_rate14";

        private string _dis_rate15;

        /// <summary>
        /// dis_rate15
        /// </summary>
        public static string M_dis_rate15 = "dis_rate15";

        private string _keyin_day;

        /// <summary>
        /// keyin_day
        /// </summary>
        public static string M_keyin_day = "keyin_day";

        private string _first_user;

        /// <summary>
        /// first_user
        /// </summary>
        public static string M_first_user = "first_user";

        private string _second_user;

        /// <summary>
        /// second_user
        /// </summary>
        public static string M_second_user = "second_user";

        private string _send3270;

        /// <summary>
        /// send3270
        /// </summary>
        public static string M_send3270 = "send3270";

        private string _keyin_flag;

        /// <summary>
        /// keyin_flag
        /// </summary>
        public static string M_keyin_flag = "keyin_flag";

        private string _keyin_userID;

        /// <summary>
        /// keyin_userID
        /// </summary>
        public static string M_keyin_userID = "keyin_userID";

        private string _MER_NAME_TYPE;

        /// <summary>
        /// MER_NAME_TYPE
        /// </summary>
        public static string M_MER_NAME_TYPE = "MER_NAME_TYPE";

        private string _LAST_UPD_MAKER;

        /// <summary>
        /// LAST_UPD_MAKER
        /// </summary>
        public static string M_LAST_UPD_MAKER = "LAST_UPD_MAKER";

        private string _LAST_UPD_CHECKER;

        /// <summary>
        /// LAST_UPD_CHECKER
        /// </summary>
        public static string M_LAST_UPD_CHECKER = "LAST_UPD_CHECKER";

        private string _LAST_UPD_BRANCH;

        /// <summary>
        /// LAST_UPD_BRANCH
        /// </summary>
        public static string M_LAST_UPD_BRANCH = "LAST_UPD_BRANCH";

        /// <summary>
        /// organization
        /// </summary>
        [AttributeField("organization", "System.String", false, false, false, "String")]
        public string organization
        {
            get
            {
                return this._organization;
            }
            set
            {
                this._organization = value;
            }
        }

        /// <summary>
        /// merchant_name
        /// </summary>
        [AttributeField("merchant_name", "System.String", false, false, false, "String")]
        public string merchant_name
        {
            get
            {
                return this._merchant_name;
            }
            set
            {
                this._merchant_name = value;
            }
        }

        /// <summary>
        /// corp
        /// </summary>
        [AttributeField("corp", "System.String", false, false, false, "String")]
        public string corp
        {
            get
            {
                return this._corp;
            }
            set
            {
                this._corp = value;
            }
        }

        /// <summary>
        /// merchdba_name
        /// </summary>
        [AttributeField("merchdba_name", "System.String", false, false, false, "String")]
        public string merchdba_name
        {
            get
            {
                return this._merchdba_name;
            }
            set
            {
                this._merchdba_name = value;
            }
        }

        /// <summary>
        /// merchant_nbr
        /// </summary>
        [AttributeField("merchant_nbr", "System.String", false, true, false, "String")]
        public string merchant_nbr
        {
            get
            {
                return this._merchant_nbr;
            }
            set
            {
                this._merchant_nbr = value;
            }
        }

        /// <summary>
        /// dba_city
        /// </summary>
        [AttributeField("dba_city", "System.String", false, false, false, "String")]
        public string dba_city
        {
            get
            {
                return this._dba_city;
            }
            set
            {
                this._dba_city = value;
            }
        }

        /// <summary>
        /// zip
        /// </summary>
        [AttributeField("zip", "System.String", false, false, false, "String")]
        public string zip
        {
            get
            {
                return this._zip;
            }
            set
            {
                this._zip = value;
            }
        }

        /// <summary>
        /// address1
        /// </summary>
        [AttributeField("address1", "System.String", false, false, false, "String")]
        public string address1
        {
            get
            {
                return this._address1;
            }
            set
            {
                this._address1 = value;
            }
        }

        /// <summary>
        /// address2
        /// </summary>
        [AttributeField("address2", "System.String", false, false, false, "String")]
        public string address2
        {
            get
            {
                return this._address2;
            }
            set
            {
                this._address2 = value;
            }
        }

        /// <summary>
        /// address3
        /// </summary>
        [AttributeField("address3", "System.String", false, false, false, "String")]
        public string address3
        {
            get
            {
                return this._address3;
            }
            set
            {
                this._address3 = value;
            }
        }

        /// <summary>
        /// address4
        /// </summary>
        [AttributeField("address4", "System.String", false, false, false, "String")]
        public string address4
        {
            get
            {
                return this._address4;
            }
            set
            {
                this._address4 = value;
            }
        }

        /// <summary>
        /// phone
        /// </summary>
        [AttributeField("phone", "System.String", false, false, false, "String")]
        public string phone
        {
            get
            {
                return this._phone;
            }
            set
            {
                this._phone = value;
            }
        }

        /// <summary>
        /// owner
        /// </summary>
        [AttributeField("owner", "System.String", false, false, false, "String")]
        public string owner
        {
            get
            {
                return this._owner;
            }
            set
            {
                this._owner = value;
            }
        }

        /// <summary>
        /// imp1
        /// </summary>
        [AttributeField("imp1", "System.String", false, false, false, "String")]
        public string imp1
        {
            get
            {
                return this._imp1;
            }
            set
            {
                this._imp1 = value;
            }
        }

        /// <summary>
        /// pos1
        /// </summary>
        [AttributeField("pos1", "System.String", false, false, false, "String")]
        public string pos1
        {
            get
            {
                return this._pos1;
            }
            set
            {
                this._pos1 = value;
            }
        }

        /// <summary>
        /// edc1
        /// </summary>
        [AttributeField("edc1", "System.String", false, false, false, "String")]
        public string edc1
        {
            get
            {
                return this._edc1;
            }
            set
            {
                this._edc1 = value;
            }
        }

        /// <summary>
        /// imp2
        /// </summary>
        [AttributeField("imp2", "System.String", false, false, false, "String")]
        public string imp2
        {
            get
            {
                return this._imp2;
            }
            set
            {
                this._imp2 = value;
            }
        }

        /// <summary>
        /// pos2
        /// </summary>
        [AttributeField("pos2", "System.String", false, false, false, "String")]
        public string pos2
        {
            get
            {
                return this._pos2;
            }
            set
            {
                this._pos2 = value;
            }
        }

        /// <summary>
        /// edc2
        /// </summary>
        [AttributeField("edc2", "System.String", false, false, false, "String")]
        public string edc2
        {
            get
            {
                return this._edc2;
            }
            set
            {
                this._edc2 = value;
            }
        }

        /// <summary>
        /// sales_name
        /// </summary>
        [AttributeField("sales_name", "System.String", false, false, false, "String")]
        public string sales_name
        {
            get
            {
                return this._sales_name;
            }
            set
            {
                this._sales_name = value;
            }
        }

        /// <summary>
        /// agent_bank
        /// </summary>
        [AttributeField("agent_bank", "System.String", false, false, false, "String")]
        public string agent_bank
        {
            get
            {
                return this._agent_bank;
            }
            set
            {
                this._agent_bank = value;
            }
        }

        /// <summary>
        /// merchant_type
        /// </summary>
        [AttributeField("merchant_type", "System.String", false, false, false, "String")]
        public string merchant_type
        {
            get
            {
                return this._merchant_type;
            }
            set
            {
                this._merchant_type = value;
            }
        }

        /// <summary>
        /// chain_store
        /// </summary>
        [AttributeField("chain_store", "System.String", false, false, false, "String")]
        public string chain_store
        {
            get
            {
                return this._chain_store;
            }
            set
            {
                this._chain_store = value;
            }
        }

        /// <summary>
        /// chain_merch
        /// </summary>
        [AttributeField("chain_merch", "System.String", false, false, false, "String")]
        public string chain_merch
        {
            get
            {
                return this._chain_merch;
            }
            set
            {
                this._chain_merch = value;
            }
        }

        /// <summary>
        /// chain_level
        /// </summary>
        [AttributeField("chain_level", "System.String", false, false, false, "String")]
        public string chain_level
        {
            get
            {
                return this._chain_level;
            }
            set
            {
                this._chain_level = value;
            }
        }

        /// <summary>
        /// Source
        /// </summary>
        [AttributeField("Source", "System.String", false, false, false, "String")]
        public string Source
        {
            get
            {
                return this._Source;
            }
            set
            {
                this._Source = value;
            }
        }

        /// <summary>
        /// mcc_VISA
        /// </summary>
        [AttributeField("mcc_VISA", "System.String", false, false, false, "String")]
        public string mcc_VISA
        {
            get
            {
                return this._mcc_VISA;
            }
            set
            {
                this._mcc_VISA = value;
            }
        }

        /// <summary>
        /// mcc_MC
        /// </summary>
        [AttributeField("mcc_MC", "System.String", false, false, false, "String")]
        public string mcc_MC
        {
            get
            {
                return this._mcc_MC;
            }
            set
            {
                this._mcc_MC = value;
            }
        }

        /// <summary>
        /// mcc_PL
        /// </summary>
        [AttributeField("mcc_PL", "System.String", false, false, false, "String")]
        public string mcc_PL
        {
            get
            {
                return this._mcc_PL;
            }
            set
            {
                this._mcc_PL = value;
            }
        }

        /// <summary>
        /// avg_tkt
        /// </summary>
        [AttributeField("avg_tkt", "System.String", false, false, false, "String")]
        public string avg_tkt
        {
            get
            {
                return this._avg_tkt;
            }
            set
            {
                this._avg_tkt = value;
            }
        }

        /// <summary>
        /// monthly_volume
        /// </summary>
        [AttributeField("monthly_volume", "System.String", false, false, false, "String")]
        public string monthly_volume
        {
            get
            {
                return this._monthly_volume;
            }
            set
            {
                this._monthly_volume = value;
            }
        }

        /// <summary>
        /// branch
        /// </summary>
        [AttributeField("branch", "System.String", false, false, false, "String")]
        public string branch
        {
            get
            {
                return this._branch;
            }
            set
            {
                this._branch = value;
            }
        }

        /// <summary>
        /// INT
        /// </summary>
        [AttributeField("INT", "System.String", false, false, false, "String")]
        public string INT
        {
            get
            {
                return this._INT;
            }
            set
            {
                this._INT = value;
            }
        }

        /// <summary>
        /// MAIL
        /// </summary>
        [AttributeField("MAIL", "System.String", false, false, false, "String")]
        public string MAIL
        {
            get
            {
                return this._MAIL;
            }
            set
            {
                this._MAIL = value;
            }
        }

        /// <summary>
        /// POS_CA
        /// </summary>
        [AttributeField("POS_CA", "System.String", false, false, false, "String")]
        public string POS_CA
        {
            get
            {
                return this._POS_CA;
            }
            set
            {
                this._POS_CA = value;
            }
        }

        /// <summary>
        /// POS_MO
        /// </summary>
        [AttributeField("POS_MO", "System.String", false, false, false, "String")]
        public string POS_MO
        {
            get
            {
                return this._POS_MO;
            }
            set
            {
                this._POS_MO = value;
            }
        }

        /// <summary>
        /// CH
        /// </summary>
        [AttributeField("CH", "System.String", false, false, false, "String")]
        public string CH
        {
            get
            {
                return this._CH;
            }
            set
            {
                this._CH = value;
            }
        }

        /// <summary>
        /// MC
        /// </summary>
        [AttributeField("MC", "System.String", false, false, false, "String")]
        public string MC
        {
            get
            {
                return this._MC;
            }
            set
            {
                this._MC = value;
            }
        }

        /// <summary>
        /// FileNo
        /// </summary>
        [AttributeField("FileNo", "System.String", false, false, false, "String")]
        public string FileNo
        {
            get
            {
                return this._FileNo;
            }
            set
            {
                this._FileNo = value;
            }
        }

        /// <summary>
        /// hold_stmt
        /// </summary>
        [AttributeField("hold_stmt", "System.String", false, false, false, "String")]
        public string hold_stmt
        {
            get
            {
                return this._hold_stmt;
            }
            set
            {
                this._hold_stmt = value;
            }
        }

        /// <summary>
        /// DDA_NO
        /// </summary>
        [AttributeField("DDA_NO", "System.String", false, false, false, "String")]
        public string DDA_NO
        {
            get
            {
                return this._DDA_NO;
            }
            set
            {
                this._DDA_NO = value;
            }
        }

        /// <summary>
        /// status1
        /// </summary>
        [AttributeField("status1", "System.String", false, false, false, "String")]
        public string status1
        {
            get
            {
                return this._status1;
            }
            set
            {
                this._status1 = value;
            }
        }

        /// <summary>
        /// status2
        /// </summary>
        [AttributeField("status2", "System.String", false, false, false, "String")]
        public string status2
        {
            get
            {
                return this._status2;
            }
            set
            {
                this._status2 = value;
            }
        }

        /// <summary>
        /// status3
        /// </summary>
        [AttributeField("status3", "System.String", false, false, false, "String")]
        public string status3
        {
            get
            {
                return this._status3;
            }
            set
            {
                this._status3 = value;
            }
        }

        /// <summary>
        /// status4
        /// </summary>
        [AttributeField("status4", "System.String", false, false, false, "String")]
        public string status4
        {
            get
            {
                return this._status4;
            }
            set
            {
                this._status4 = value;
            }
        }

        /// <summary>
        /// status5
        /// </summary>
        [AttributeField("status5", "System.String", false, false, false, "String")]
        public string status5
        {
            get
            {
                return this._status5;
            }
            set
            {
                this._status5 = value;
            }
        }

        /// <summary>
        /// status6
        /// </summary>
        [AttributeField("status6", "System.String", false, false, false, "String")]
        public string status6
        {
            get
            {
                return this._status6;
            }
            set
            {
                this._status6 = value;
            }
        }

        /// <summary>
        /// status7
        /// </summary>
        [AttributeField("status7", "System.String", false, false, false, "String")]
        public string status7
        {
            get
            {
                return this._status7;
            }
            set
            {
                this._status7 = value;
            }
        }

        /// <summary>
        /// status8
        /// </summary>
        [AttributeField("status8", "System.String", false, false, false, "String")]
        public string status8
        {
            get
            {
                return this._status8;
            }
            set
            {
                this._status8 = value;
            }
        }

        /// <summary>
        /// status9
        /// </summary>
        [AttributeField("status9", "System.String", false, false, false, "String")]
        public string status9
        {
            get
            {
                return this._status9;
            }
            set
            {
                this._status9 = value;
            }
        }

        /// <summary>
        /// status10
        /// </summary>
        [AttributeField("status10", "System.String", false, false, false, "String")]
        public string status10
        {
            get
            {
                return this._status10;
            }
            set
            {
                this._status10 = value;
            }
        }

        /// <summary>
        /// status11
        /// </summary>
        [AttributeField("status11", "System.String", false, false, false, "String")]
        public string status11
        {
            get
            {
                return this._status11;
            }
            set
            {
                this._status11 = value;
            }
        }

        /// <summary>
        /// status12
        /// </summary>
        [AttributeField("status12", "System.String", false, false, false, "String")]
        public string status12
        {
            get
            {
                return this._status12;
            }
            set
            {
                this._status12 = value;
            }
        }

        /// <summary>
        /// status13
        /// </summary>
        [AttributeField("status13", "System.String", false, false, false, "String")]
        public string status13
        {
            get
            {
                return this._status13;
            }
            set
            {
                this._status13 = value;
            }
        }

        /// <summary>
        /// status14
        /// </summary>
        [AttributeField("status14", "System.String", false, false, false, "String")]
        public string status14
        {
            get
            {
                return this._status14;
            }
            set
            {
                this._status14 = value;
            }
        }

        /// <summary>
        /// status15
        /// </summary>
        [AttributeField("status15", "System.String", false, false, false, "String")]
        public string status15
        {
            get
            {
                return this._status15;
            }
            set
            {
                this._status15 = value;
            }
        }

        /// <summary>
        /// dis_rate1
        /// </summary>
        [AttributeField("dis_rate1", "System.String", false, false, false, "String")]
        public string dis_rate1
        {
            get
            {
                return this._dis_rate1;
            }
            set
            {
                this._dis_rate1 = value;
            }
        }

        /// <summary>
        /// dis_rate2
        /// </summary>
        [AttributeField("dis_rate2", "System.String", false, false, false, "String")]
        public string dis_rate2
        {
            get
            {
                return this._dis_rate2;
            }
            set
            {
                this._dis_rate2 = value;
            }
        }

        /// <summary>
        /// dis_rate3
        /// </summary>
        [AttributeField("dis_rate3", "System.String", false, false, false, "String")]
        public string dis_rate3
        {
            get
            {
                return this._dis_rate3;
            }
            set
            {
                this._dis_rate3 = value;
            }
        }

        /// <summary>
        /// dis_rate4
        /// </summary>
        [AttributeField("dis_rate4", "System.String", false, false, false, "String")]
        public string dis_rate4
        {
            get
            {
                return this._dis_rate4;
            }
            set
            {
                this._dis_rate4 = value;
            }
        }

        /// <summary>
        /// dis_rate5
        /// </summary>
        [AttributeField("dis_rate5", "System.String", false, false, false, "String")]
        public string dis_rate5
        {
            get
            {
                return this._dis_rate5;
            }
            set
            {
                this._dis_rate5 = value;
            }
        }

        /// <summary>
        /// dis_rate6
        /// </summary>
        [AttributeField("dis_rate6", "System.String", false, false, false, "String")]
        public string dis_rate6
        {
            get
            {
                return this._dis_rate6;
            }
            set
            {
                this._dis_rate6 = value;
            }
        }

        /// <summary>
        /// dis_rate7
        /// </summary>
        [AttributeField("dis_rate7", "System.String", false, false, false, "String")]
        public string dis_rate7
        {
            get
            {
                return this._dis_rate7;
            }
            set
            {
                this._dis_rate7 = value;
            }
        }

        /// <summary>
        /// dis_rate8
        /// </summary>
        [AttributeField("dis_rate8", "System.String", false, false, false, "String")]
        public string dis_rate8
        {
            get
            {
                return this._dis_rate8;
            }
            set
            {
                this._dis_rate8 = value;
            }
        }

        /// <summary>
        /// dis_rate9
        /// </summary>
        [AttributeField("dis_rate9", "System.String", false, false, false, "String")]
        public string dis_rate9
        {
            get
            {
                return this._dis_rate9;
            }
            set
            {
                this._dis_rate9 = value;
            }
        }

        /// <summary>
        /// dis_rate10
        /// </summary>
        [AttributeField("dis_rate10", "System.String", false, false, false, "String")]
        public string dis_rate10
        {
            get
            {
                return this._dis_rate10;
            }
            set
            {
                this._dis_rate10 = value;
            }
        }

        /// <summary>
        /// dis_rate11
        /// </summary>
        [AttributeField("dis_rate11", "System.String", false, false, false, "String")]
        public string dis_rate11
        {
            get
            {
                return this._dis_rate11;
            }
            set
            {
                this._dis_rate11 = value;
            }
        }

        /// <summary>
        /// dis_rate12
        /// </summary>
        [AttributeField("dis_rate12", "System.String", false, false, false, "String")]
        public string dis_rate12
        {
            get
            {
                return this._dis_rate12;
            }
            set
            {
                this._dis_rate12 = value;
            }
        }

        /// <summary>
        /// dis_rate13
        /// </summary>
        [AttributeField("dis_rate13", "System.String", false, false, false, "String")]
        public string dis_rate13
        {
            get
            {
                return this._dis_rate13;
            }
            set
            {
                this._dis_rate13 = value;
            }
        }

        /// <summary>
        /// dis_rate14
        /// </summary>
        [AttributeField("dis_rate14", "System.String", false, false, false, "String")]
        public string dis_rate14
        {
            get
            {
                return this._dis_rate14;
            }
            set
            {
                this._dis_rate14 = value;
            }
        }

        /// <summary>
        /// dis_rate15
        /// </summary>
        [AttributeField("dis_rate15", "System.String", false, false, false, "String")]
        public string dis_rate15
        {
            get
            {
                return this._dis_rate15;
            }
            set
            {
                this._dis_rate15 = value;
            }
        }

        /// <summary>
        /// keyin_day
        /// </summary>
        [AttributeField("keyin_day", "System.String", false, false, false, "String")]
        public string keyin_day
        {
            get
            {
                return this._keyin_day;
            }
            set
            {
                this._keyin_day = value;
            }
        }

        /// <summary>
        /// first_user
        /// </summary>
        [AttributeField("first_user", "System.String", false, false, false, "String")]
        public string first_user
        {
            get
            {
                return this._first_user;
            }
            set
            {
                this._first_user = value;
            }
        }

        /// <summary>
        /// second_user
        /// </summary>
        [AttributeField("second_user", "System.String", false, false, false, "String")]
        public string second_user
        {
            get
            {
                return this._second_user;
            }
            set
            {
                this._second_user = value;
            }
        }

        /// <summary>
        /// send3270
        /// </summary>
        [AttributeField("send3270", "System.String", false, false, false, "String")]
        public string send3270
        {
            get
            {
                return this._send3270;
            }
            set
            {
                this._send3270 = value;
            }
        }

        /// <summary>
        /// keyin_flag
        /// </summary>
        [AttributeField("keyin_flag", "System.String", false, true, false, "String")]
        public string keyin_flag
        {
            get
            {
                return this._keyin_flag;
            }
            set
            {
                this._keyin_flag = value;
            }
        }

        /// <summary>
        /// keyin_userID
        /// </summary>
        [AttributeField("keyin_userID", "System.String", false, false, false, "String")]
        public string keyin_userID
        {
            get
            {
                return this._keyin_userID;
            }
            set
            {
                this._keyin_userID = value;
            }
        }

        /// <summary>
        /// MER_NAME_TYPE
        /// </summary>
        [AttributeField("MER_NAME_TYPE", "System.String", false, false, false, "String")]
        public string MER_NAME_TYPE
        {
            get
            {
                return this._MER_NAME_TYPE;
            }
            set
            {
                this._MER_NAME_TYPE = value;
            }
        }

        /// <summary>
        /// LAST_UPD_MAKER
        /// </summary>
        [AttributeField("LAST_UPD_MAKER", "System.String", false, false, false, "String")]
        public string LAST_UPD_MAKER
        {
            get
            {
                return this._LAST_UPD_MAKER;
            }
            set
            {
                this._LAST_UPD_MAKER = value;
            }
        }

        /// <summary>
        /// LAST_UPD_CHECKER
        /// </summary>
        [AttributeField("LAST_UPD_CHECKER", "System.String", false, false, false, "String")]
        public string LAST_UPD_CHECKER
        {
            get
            {
                return this._LAST_UPD_CHECKER;
            }
            set
            {
                this._LAST_UPD_CHECKER = value;
            }
        }

        /// <summary>
        /// LAST_UPD_BRANCH
        /// </summary>
        [AttributeField("LAST_UPD_BRANCH", "System.String", false, false, false, "String")]
        public string LAST_UPD_BRANCH
        {
            get
            {
                return this._LAST_UPD_BRANCH;
            }
            set
            {
                this._LAST_UPD_BRANCH = value;
            }
        }
    }

    /// <summary>
    /// SHOP_PCAM
    /// </summary>
    [Serializable()]
    public class EntitySHOP_PCAMSet : EntitySet<EntitySHOP_PCAM>
    {
    }
}
