//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPKeyInGUI.EntityLayer
{


    /// <summary>
    /// shop
    /// </summary>
    [Serializable()]
    [AttributeTable("shop")]
    public class EntitySHOP : Entity
    {

        private string _shop_id;

        /// <summary>
        /// shop_id
        /// </summary>
        public static string M_shop_id = "shop_id";

        private string _record_name;

        /// <summary>
        /// record_name
        /// </summary>
        public static string M_record_name = "record_name";

        private string _business_name;

        /// <summary>
        /// business_name
        /// </summary>
        public static string M_business_name = "business_name";

        private string _english_name;

        /// <summary>
        /// english_name
        /// </summary>
        public static string M_english_name = "english_name";

        private string _undertaker;

        /// <summary>
        /// undertaker
        /// </summary>
        public static string M_undertaker = "undertaker";

        private string _undertaker_id;

        /// <summary>
        /// undertaker_id
        /// </summary>
        public static string M_undertaker_id = "undertaker_id";

        private string _undertaker_tel1;

        /// <summary>
        /// undertaker_tel1
        /// </summary>
        public static string M_undertaker_tel1 = "undertaker_tel1";

        private string _undertaker_tel2;

        /// <summary>
        /// undertaker_tel2
        /// </summary>
        public static string M_undertaker_tel2 = "undertaker_tel2";

        private string _undertaker_tel3;

        /// <summary>
        /// undertaker_tel3
        /// </summary>
        public static string M_undertaker_tel3 = "undertaker_tel3";

        private string _undertaker_add1;

        /// <summary>
        /// undertaker_add1
        /// </summary>
        public static string M_undertaker_add1 = "undertaker_add1";

        private string _undertaker_add2;

        /// <summary>
        /// undertaker_add2
        /// </summary>
        public static string M_undertaker_add2 = "undertaker_add2";

        private string _realperson;

        /// <summary>
        /// realperson
        /// </summary>
        public static string M_realperson = "realperson";

        private string _realperson_id;

        /// <summary>
        /// realperson_id
        /// </summary>
        public static string M_realperson_id = "realperson_id";

        private string _realperson_tel1;

        /// <summary>
        /// realperson_tel1
        /// </summary>
        public static string M_realperson_tel1 = "realperson_tel1";

        private string _realperson_tel2;

        /// <summary>
        /// realperson_tel2
        /// </summary>
        public static string M_realperson_tel2 = "realperson_tel2";

        private string _realperson_tel3;

        /// <summary>
        /// realperson_tel3
        /// </summary>
        public static string M_realperson_tel3 = "realperson_tel3";

        private string _realperson_add1;

        /// <summary>
        /// realperson_add1
        /// </summary>
        public static string M_realperson_add1 = "realperson_add1";

        private string _realperson_add2;

        /// <summary>
        /// realperson_add2
        /// </summary>
        public static string M_realperson_add2 = "realperson_add2";

        private string _junctionperson;

        /// <summary>
        /// junctionperson
        /// </summary>
        public static string M_junctionperson = "junctionperson";

        private string _junctionperson_tel1;

        /// <summary>
        /// junctionperson_tel1
        /// </summary>
        public static string M_junctionperson_tel1 = "junctionperson_tel1";

        private string _junctionperson_tel2;

        /// <summary>
        /// junctionperson_tel2
        /// </summary>
        public static string M_junctionperson_tel2 = "junctionperson_tel2";

        private string _junctionperson_tel3;

        /// <summary>
        /// junctionperson_tel3
        /// </summary>
        public static string M_junctionperson_tel3 = "junctionperson_tel3";

        private string _junctionperson_fax1;

        /// <summary>
        /// junctionperson_fax1
        /// </summary>
        public static string M_junctionperson_fax1 = "junctionperson_fax1";

        private string _junctionperson_fax2;

        /// <summary>
        /// junctionperson_fax2
        /// </summary>
        public static string M_junctionperson_fax2 = "junctionperson_fax2";

        private string _junctionperson_recadd1;

        /// <summary>
        /// junctionperson_recadd1
        /// </summary>
        public static string M_junctionperson_recadd1 = "junctionperson_recadd1";

        private string _junctionperson_recadd2;

        /// <summary>
        /// junctionperson_recadd2
        /// </summary>
        public static string M_junctionperson_recadd2 = "junctionperson_recadd2";

        private string _junctionperson_realadd1;

        /// <summary>
        /// junctionperson_realadd1
        /// </summary>
        public static string M_junctionperson_realadd1 = "junctionperson_realadd1";

        private string _junctionperson_realadd2;

        /// <summary>
        /// junctionperson_realadd2
        /// </summary>
        public static string M_junctionperson_realadd2 = "junctionperson_realadd2";

        private string _black;

        /// <summary>
        /// black
        /// </summary>
        public static string M_black = "black";

        private string _class;

        /// <summary>
        /// class
        /// </summary>
        public static string M_class = "class";

        private string _introduce;

        /// <summary>
        /// introduce
        /// </summary>
        public static string M_introduce = "introduce";

        private string _commadd1;

        /// <summary>
        /// commadd1
        /// </summary>
        public static string M_commadd1 = "commadd1";

        private string _comaddr2;

        /// <summary>
        /// comaddr2
        /// </summary>
        public static string M_comaddr2 = "comaddr2";

        private string _zip;

        /// <summary>
        /// zip
        /// </summary>
        public static string M_zip = "zip";

        private string _addjcb;

        /// <summary>
        /// addjcb
        /// </summary>
        public static string M_addjcb = "addjcb";

        private string _moddate;

        /// <summary>
        /// moddate
        /// </summary>
        public static string M_moddate = "moddate";

        private string _page1;

        /// <summary>
        /// page1
        /// </summary>
        public static string M_page1 = "page1";

        private string _page2;

        /// <summary>
        /// page2
        /// </summary>
        public static string M_page2 = "page2";

        private string _page3;

        /// <summary>
        /// page3
        /// </summary>
        public static string M_page3 = "page3";

        private string _page4;

        /// <summary>
        /// page4
        /// </summary>
        public static string M_page4 = "page4";

        private string _bank_name;

        /// <summary>
        /// bank_name
        /// </summary>
        public static string M_bank_name = "bank_name";

        private string _branch_name;

        /// <summary>
        /// branch_name
        /// </summary>
        public static string M_branch_name = "branch_name";

        private string _account;

        /// <summary>
        /// account
        /// </summary>
        public static string M_account = "account";

        private string _check_num;

        /// <summary>
        /// check_num
        /// </summary>
        public static string M_check_num = "check_num";

        private string _account1;

        /// <summary>
        /// account1
        /// </summary>
        public static string M_account1 = "account1";

        private string _account2;

        /// <summary>
        /// account2
        /// </summary>
        public static string M_account2 = "account2";

        private string _cancel_code1;

        /// <summary>
        /// cancel_code1
        /// </summary>
        public static string M_cancel_code1 = "cancel_code1";

        private string _cancel_date;

        /// <summary>
        /// cancel_date
        /// </summary>
        public static string M_cancel_date = "cancel_date";

        private string _cancel_code2;

        /// <summary>
        /// cancel_code2
        /// </summary>
        public static string M_cancel_code2 = "cancel_code2";

        private string _imp1;

        /// <summary>
        /// imp1
        /// </summary>
        public static string M_imp1 = "imp1";

        private string _imp2;

        /// <summary>
        /// imp2
        /// </summary>
        public static string M_imp2 = "imp2";

        private string _imp_money;

        /// <summary>
        /// imp_money
        /// </summary>
        public static string M_imp_money = "imp_money";

        private string _pos1;

        /// <summary>
        /// pos1
        /// </summary>
        public static string M_pos1 = "pos1";

        private string _pos2;

        /// <summary>
        /// pos2
        /// </summary>
        public static string M_pos2 = "pos2";

        private string _pos_money;

        /// <summary>
        /// pos_money
        /// </summary>
        public static string M_pos_money = "pos_money";

        private string _edc1;

        /// <summary>
        /// edc1
        /// </summary>
        public static string M_edc1 = "edc1";

        private string _edcnum;

        /// <summary>
        /// edcnum
        /// </summary>
        public static string M_edcnum = "edcnum";

        private string _edc;

        /// <summary>
        /// edc
        /// </summary>
        public static string M_edc = "edc";

        private string _edc_money;

        /// <summary>
        /// edc_money
        /// </summary>
        public static string M_edc_money = "edc_money";

        private string _undertaker_add3;

        /// <summary>
        /// undertaker_add3
        /// </summary>
        public static string M_undertaker_add3 = "undertaker_add3";

        private string _realperson_add3;

        /// <summary>
        /// realperson_add3
        /// </summary>
        public static string M_realperson_add3 = "realperson_add3";

        private string _junctionperson_recadd3;

        /// <summary>
        /// junctionperson_recadd3
        /// </summary>
        public static string M_junctionperson_recadd3 = "junctionperson_recadd3";

        private string _junctionperson_realadd3;

        /// <summary>
        /// junctionperson_realadd3
        /// </summary>
        public static string M_junctionperson_realadd3 = "junctionperson_realadd3";

        private string _MERCHANT_NAME;

        /// <summary>
        /// MERCHANT_NAME
        /// </summary>
        public static string M_MERCHANT_NAME = "MERCHANT_NAME";

        private System.Nullable<int> _P4;

        /// <summary>
        /// P4
        /// </summary>
        public static string M_P4 = "P4";

        private System.Nullable<int> _p4A;

        /// <summary>
        /// p4A
        /// </summary>
        public static string M_p4A = "p4A";

        private string _KeyIn_Flag;

        /// <summary>
        /// KeyIn_Flag
        /// </summary>
        public static string M_KeyIn_Flag = "KeyIn_Flag";

        private string _user_id;

        /// <summary>
        /// user_id
        /// </summary>
        public static string M_user_id = "user_id";

        private string _mod_date;

        /// <summary>
        /// mod_date
        /// </summary>
        public static string M_mod_date = "mod_date";

        private string _realadd_zip;

        /// <summary>
        /// realadd_zip
        /// </summary>
        public static string M_realadd_zip = "realadd_zip";

        private string _undertaker_EngName;

        /// <summary>
        /// undertaker_EngName
        /// </summary>
        public static string M_undertaker_EngName = "undertaker_EngName";

        private string _introduce_flag;

        /// <summary>
        /// introduce_flag
        /// </summary>
        public static string M_introduce_flag = "introduce_flag";

        private string _invoice_cycle;

        /// <summary>
        /// invoice_cycle
        /// </summary>
        public static string M_invoice_cycle = "invoice_cycle";

        private string _HOLD_STMT;

        /// <summary>
        /// HOLD_STMT
        /// </summary>
        public static string M_HOLD_STMT = "HOLD_STMT";

        private string _Change_Item;

        /// <summary>
        /// Change_Item
        /// </summary>
        public static string M_Change_Item = "Change_Item";

        private string _addjcb_us;

        /// <summary>
        /// addjcb_us
        /// </summary>
        public static string M_addjcb_us = "addjcb_us";

        private string _addjcb_notus;

        /// <summary>
        /// addjcb_notus
        /// </summary>
        public static string M_addjcb_notus = "addjcb_notus";

        private string _rate02N;

        /// <summary>
        /// rate02N
        /// </summary>
        public static string M_rate02N = "rate02N";

        private string _rate03V;

        /// <summary>
        /// rate03V
        /// </summary>
        public static string M_rate03V = "rate03V";

        private string _rate04V;

        /// <summary>
        /// rate04V
        /// </summary>
        public static string M_rate04V = "rate04V";

        private string _rate05M;

        /// <summary>
        /// rate05M
        /// </summary>
        public static string M_rate05M = "rate05M";

        private string _rate06M;

        /// <summary>
        /// rate06M
        /// </summary>
        public static string M_rate06M = "rate06M";

        private string _rate07J;

        /// <summary>
        /// rate07J
        /// </summary>
        public static string M_rate07J = "rate07J";

        private string _rate08J;

        /// <summary>
        /// rate08J
        /// </summary>
        public static string M_rate08J = "rate08J";

        private string _rate09;

        /// <summary>
        /// rate09
        /// </summary>
        public static string M_rate09 = "rate09";

        private string _rate10;

        /// <summary>
        /// rate10
        /// </summary>
        public static string M_rate10 = "rate10";

        private string _rate11;

        /// <summary>
        /// rate11
        /// </summary>
        public static string M_rate11 = "rate11";

        private string _rate13;

        /// <summary>
        /// rate13
        /// </summary>
        public static string M_rate13 = "rate13";

        private string _rate12;

        /// <summary>
        /// rate12
        /// </summary>
        public static string M_rate12 = "rate12";

        private string _rate14;

        /// <summary>
        /// rate14
        /// </summary>
        public static string M_rate14 = "rate14";

        private string _rate15;

        /// <summary>
        /// rate15
        /// </summary>
        public static string M_rate15 = "rate15";

        private string _shop_type;

        /// <summary>
        /// shop_type
        /// </summary>
        public static string M_shop_type = "shop_type";

        private string _imp1_type;

        /// <summary>
        /// imp1_type
        /// </summary>
        public static string M_imp1_type = "imp1_type";

        private string _imp2_type;

        /// <summary>
        /// imp2_type
        /// </summary>
        public static string M_imp2_type = "imp2_type";

        private string _pos1_type;

        /// <summary>
        /// pos1_type
        /// </summary>
        public static string M_pos1_type = "pos1_type";

        private string _pos2_type;

        /// <summary>
        /// pos2_type
        /// </summary>
        public static string M_pos2_type = "pos2_type";

        private string _edc1_type;

        /// <summary>
        /// edc1_type
        /// </summary>
        public static string M_edc1_type = "edc1_type";

        private string _edc_type;

        /// <summary>
        /// edc_type
        /// </summary>
        public static string M_edc_type = "edc_type";

        private string _cup_status1;

        /// <summary>
        /// cup_status1
        /// </summary>
        public static string M_cup_status1 = "cup_status1";

        private string _cup_status2;

        /// <summary>
        /// cup_status2
        /// </summary>
        public static string M_cup_status2 = "cup_status2";

        private string _cup_status3;

        /// <summary>
        /// cup_status3
        /// </summary>
        public static string M_cup_status3 = "cup_status3";

        private string _cup_status4;

        /// <summary>
        /// cup_status4
        /// </summary>
        public static string M_cup_status4 = "cup_status4";

        private string _cup_status5;

        /// <summary>
        /// cup_status5
        /// </summary>
        public static string M_cup_status5 = "cup_status5";

        private string _cup_status6;

        /// <summary>
        /// cup_status6
        /// </summary>
        public static string M_cup_status6 = "cup_status6";

        private string _cup_status7;

        /// <summary>
        /// cup_status7
        /// </summary>
        public static string M_cup_status7 = "cup_status7";

        private string _cup_status8;

        /// <summary>
        /// cup_status8
        /// </summary>
        public static string M_cup_status8 = "cup_status8";

        private string _cup_status9;

        /// <summary>
        /// cup_status9
        /// </summary>
        public static string M_cup_status9 = "cup_status9";

        private string _cup_status10;

        /// <summary>
        /// cup_status10
        /// </summary>
        public static string M_cup_status10 = "cup_status10";

        private string _cup_rate1;

        /// <summary>
        /// cup_rate1
        /// </summary>
        public static string M_cup_rate1 = "cup_rate1";

        private string _cup_rate2;

        /// <summary>
        /// cup_rate2
        /// </summary>
        public static string M_cup_rate2 = "cup_rate2";

        private string _cup_rate3;

        /// <summary>
        /// cup_rate3
        /// </summary>
        public static string M_cup_rate3 = "cup_rate3";

        private string _cup_rate4;

        /// <summary>
        /// cup_rate4
        /// </summary>
        public static string M_cup_rate4 = "cup_rate4";

        private string _cup_rate5;

        /// <summary>
        /// cup_rate5
        /// </summary>
        public static string M_cup_rate5 = "cup_rate5";

        private string _cup_rate6;

        /// <summary>
        /// cup_rate6
        /// </summary>
        public static string M_cup_rate6 = "cup_rate6";

        private string _cup_rate7;

        /// <summary>
        /// cup_rate7
        /// </summary>
        public static string M_cup_rate7 = "cup_rate7";

        private string _cup_rate8;

        /// <summary>
        /// cup_rate8
        /// </summary>
        public static string M_cup_rate8 = "cup_rate8";

        private string _cup_rate9;

        /// <summary>
        /// cup_rate9
        /// </summary>
        public static string M_cup_rate9 = "cup_rate9";

        private string _cup_rate10;

        /// <summary>
        /// cup_rate10
        /// </summary>
        public static string M_cup_rate10 = "cup_rate10";

        private string _ReqAppro;

        /// <summary>
        /// ReqAppro
        /// </summary>
        public static string M_ReqAppro = "ReqAppro";

        /// <summary>
        /// shop_id
        /// </summary>
        [AttributeField("shop_id", "System.String", false, true, false, "String")]
        public string shop_id
        {
            get
            {
                return this._shop_id;
            }
            set
            {
                this._shop_id = value;
            }
        }

        /// <summary>
        /// record_name
        /// </summary>
        [AttributeField("record_name", "System.String", false, false, false, "String")]
        public string record_name
        {
            get
            {
                return this._record_name;
            }
            set
            {
                this._record_name = value;
            }
        }

        /// <summary>
        /// business_name
        /// </summary>
        [AttributeField("business_name", "System.String", false, false, false, "String")]
        public string business_name
        {
            get
            {
                return this._business_name;
            }
            set
            {
                this._business_name = value;
            }
        }

        /// <summary>
        /// english_name
        /// </summary>
        [AttributeField("english_name", "System.String", false, false, false, "String")]
        public string english_name
        {
            get
            {
                return this._english_name;
            }
            set
            {
                this._english_name = value;
            }
        }

        /// <summary>
        /// undertaker
        /// </summary>
        [AttributeField("undertaker", "System.String", false, false, false, "String")]
        public string undertaker
        {
            get
            {
                return this._undertaker;
            }
            set
            {
                this._undertaker = value;
            }
        }

        /// <summary>
        /// undertaker_id
        /// </summary>
        [AttributeField("undertaker_id", "System.String", false, false, false, "String")]
        public string undertaker_id
        {
            get
            {
                return this._undertaker_id;
            }
            set
            {
                this._undertaker_id = value;
            }
        }

        /// <summary>
        /// undertaker_tel1
        /// </summary>
        [AttributeField("undertaker_tel1", "System.String", false, false, false, "String")]
        public string undertaker_tel1
        {
            get
            {
                return this._undertaker_tel1;
            }
            set
            {
                this._undertaker_tel1 = value;
            }
        }

        /// <summary>
        /// undertaker_tel2
        /// </summary>
        [AttributeField("undertaker_tel2", "System.String", false, false, false, "String")]
        public string undertaker_tel2
        {
            get
            {
                return this._undertaker_tel2;
            }
            set
            {
                this._undertaker_tel2 = value;
            }
        }

        /// <summary>
        /// undertaker_tel3
        /// </summary>
        [AttributeField("undertaker_tel3", "System.String", false, false, false, "String")]
        public string undertaker_tel3
        {
            get
            {
                return this._undertaker_tel3;
            }
            set
            {
                this._undertaker_tel3 = value;
            }
        }

        /// <summary>
        /// undertaker_add1
        /// </summary>
        [AttributeField("undertaker_add1", "System.String", false, false, false, "String")]
        public string undertaker_add1
        {
            get
            {
                return this._undertaker_add1;
            }
            set
            {
                this._undertaker_add1 = value;
            }
        }

        /// <summary>
        /// undertaker_add2
        /// </summary>
        [AttributeField("undertaker_add2", "System.String", false, false, false, "String")]
        public string undertaker_add2
        {
            get
            {
                return this._undertaker_add2;
            }
            set
            {
                this._undertaker_add2 = value;
            }
        }

        /// <summary>
        /// realperson
        /// </summary>
        [AttributeField("realperson", "System.String", false, false, false, "String")]
        public string realperson
        {
            get
            {
                return this._realperson;
            }
            set
            {
                this._realperson = value;
            }
        }

        /// <summary>
        /// realperson_id
        /// </summary>
        [AttributeField("realperson_id", "System.String", false, false, false, "String")]
        public string realperson_id
        {
            get
            {
                return this._realperson_id;
            }
            set
            {
                this._realperson_id = value;
            }
        }

        /// <summary>
        /// realperson_tel1
        /// </summary>
        [AttributeField("realperson_tel1", "System.String", false, false, false, "String")]
        public string realperson_tel1
        {
            get
            {
                return this._realperson_tel1;
            }
            set
            {
                this._realperson_tel1 = value;
            }
        }

        /// <summary>
        /// realperson_tel2
        /// </summary>
        [AttributeField("realperson_tel2", "System.String", false, false, false, "String")]
        public string realperson_tel2
        {
            get
            {
                return this._realperson_tel2;
            }
            set
            {
                this._realperson_tel2 = value;
            }
        }

        /// <summary>
        /// realperson_tel3
        /// </summary>
        [AttributeField("realperson_tel3", "System.String", false, false, false, "String")]
        public string realperson_tel3
        {
            get
            {
                return this._realperson_tel3;
            }
            set
            {
                this._realperson_tel3 = value;
            }
        }

        /// <summary>
        /// realperson_add1
        /// </summary>
        [AttributeField("realperson_add1", "System.String", false, false, false, "String")]
        public string realperson_add1
        {
            get
            {
                return this._realperson_add1;
            }
            set
            {
                this._realperson_add1 = value;
            }
        }

        /// <summary>
        /// realperson_add2
        /// </summary>
        [AttributeField("realperson_add2", "System.String", false, false, false, "String")]
        public string realperson_add2
        {
            get
            {
                return this._realperson_add2;
            }
            set
            {
                this._realperson_add2 = value;
            }
        }

        /// <summary>
        /// junctionperson
        /// </summary>
        [AttributeField("junctionperson", "System.String", false, false, false, "String")]
        public string junctionperson
        {
            get
            {
                return this._junctionperson;
            }
            set
            {
                this._junctionperson = value;
            }
        }

        /// <summary>
        /// junctionperson_tel1
        /// </summary>
        [AttributeField("junctionperson_tel1", "System.String", false, false, false, "String")]
        public string junctionperson_tel1
        {
            get
            {
                return this._junctionperson_tel1;
            }
            set
            {
                this._junctionperson_tel1 = value;
            }
        }

        /// <summary>
        /// junctionperson_tel2
        /// </summary>
        [AttributeField("junctionperson_tel2", "System.String", false, false, false, "String")]
        public string junctionperson_tel2
        {
            get
            {
                return this._junctionperson_tel2;
            }
            set
            {
                this._junctionperson_tel2 = value;
            }
        }

        /// <summary>
        /// junctionperson_tel3
        /// </summary>
        [AttributeField("junctionperson_tel3", "System.String", false, false, false, "String")]
        public string junctionperson_tel3
        {
            get
            {
                return this._junctionperson_tel3;
            }
            set
            {
                this._junctionperson_tel3 = value;
            }
        }

        /// <summary>
        /// junctionperson_fax1
        /// </summary>
        [AttributeField("junctionperson_fax1", "System.String", false, false, false, "String")]
        public string junctionperson_fax1
        {
            get
            {
                return this._junctionperson_fax1;
            }
            set
            {
                this._junctionperson_fax1 = value;
            }
        }

        /// <summary>
        /// junctionperson_fax2
        /// </summary>
        [AttributeField("junctionperson_fax2", "System.String", false, false, false, "String")]
        public string junctionperson_fax2
        {
            get
            {
                return this._junctionperson_fax2;
            }
            set
            {
                this._junctionperson_fax2 = value;
            }
        }

        /// <summary>
        /// junctionperson_recadd1
        /// </summary>
        [AttributeField("junctionperson_recadd1", "System.String", false, false, false, "String")]
        public string junctionperson_recadd1
        {
            get
            {
                return this._junctionperson_recadd1;
            }
            set
            {
                this._junctionperson_recadd1 = value;
            }
        }

        /// <summary>
        /// junctionperson_recadd2
        /// </summary>
        [AttributeField("junctionperson_recadd2", "System.String", false, false, false, "String")]
        public string junctionperson_recadd2
        {
            get
            {
                return this._junctionperson_recadd2;
            }
            set
            {
                this._junctionperson_recadd2 = value;
            }
        }

        /// <summary>
        /// junctionperson_realadd1
        /// </summary>
        [AttributeField("junctionperson_realadd1", "System.String", false, false, false, "String")]
        public string junctionperson_realadd1
        {
            get
            {
                return this._junctionperson_realadd1;
            }
            set
            {
                this._junctionperson_realadd1 = value;
            }
        }

        /// <summary>
        /// junctionperson_realadd2
        /// </summary>
        [AttributeField("junctionperson_realadd2", "System.String", false, false, false, "String")]
        public string junctionperson_realadd2
        {
            get
            {
                return this._junctionperson_realadd2;
            }
            set
            {
                this._junctionperson_realadd2 = value;
            }
        }

        /// <summary>
        /// black
        /// </summary>
        [AttributeField("black", "System.String", false, false, false, "String")]
        public string black
        {
            get
            {
                return this._black;
            }
            set
            {
                this._black = value;
            }
        }

        /// <summary>
        /// class
        /// </summary>
        [AttributeField("class", "System.String", false, false, false, "String")]
        public string @class
        {
            get
            {
                return this._class;
            }
            set
            {
                this._class = value;
            }
        }

        /// <summary>
        /// introduce
        /// </summary>
        [AttributeField("introduce", "System.String", false, false, false, "String")]
        public string introduce
        {
            get
            {
                return this._introduce;
            }
            set
            {
                this._introduce = value;
            }
        }

        /// <summary>
        /// commadd1
        /// </summary>
        [AttributeField("commadd1", "System.String", false, false, false, "String")]
        public string commadd1
        {
            get
            {
                return this._commadd1;
            }
            set
            {
                this._commadd1 = value;
            }
        }

        /// <summary>
        /// comaddr2
        /// </summary>
        [AttributeField("comaddr2", "System.String", false, false, false, "String")]
        public string comaddr2
        {
            get
            {
                return this._comaddr2;
            }
            set
            {
                this._comaddr2 = value;
            }
        }

        /// <summary>
        /// zip
        /// </summary>
        [AttributeField("zip", "System.String", false, false, false, "String")]
        public string zip
        {
            get
            {
                return this._zip;
            }
            set
            {
                this._zip = value;
            }
        }

        /// <summary>
        /// addjcb
        /// </summary>
        [AttributeField("addjcb", "System.String", false, false, false, "String")]
        public string addjcb
        {
            get
            {
                return this._addjcb;
            }
            set
            {
                this._addjcb = value;
            }
        }

        /// <summary>
        /// moddate
        /// </summary>
        [AttributeField("moddate", "System.String", false, false, false, "String")]
        public string moddate
        {
            get
            {
                return this._moddate;
            }
            set
            {
                this._moddate = value;
            }
        }

        /// <summary>
        /// page1
        /// </summary>
        [AttributeField("page1", "System.String", false, false, false, "String")]
        public string page1
        {
            get
            {
                return this._page1;
            }
            set
            {
                this._page1 = value;
            }
        }

        /// <summary>
        /// page2
        /// </summary>
        [AttributeField("page2", "System.String", false, false, false, "String")]
        public string page2
        {
            get
            {
                return this._page2;
            }
            set
            {
                this._page2 = value;
            }
        }

        /// <summary>
        /// page3
        /// </summary>
        [AttributeField("page3", "System.String", false, false, false, "String")]
        public string page3
        {
            get
            {
                return this._page3;
            }
            set
            {
                this._page3 = value;
            }
        }

        /// <summary>
        /// page4
        /// </summary>
        [AttributeField("page4", "System.String", false, false, false, "String")]
        public string page4
        {
            get
            {
                return this._page4;
            }
            set
            {
                this._page4 = value;
            }
        }

        /// <summary>
        /// bank_name
        /// </summary>
        [AttributeField("bank_name", "System.String", false, false, false, "String")]
        public string bank_name
        {
            get
            {
                return this._bank_name;
            }
            set
            {
                this._bank_name = value;
            }
        }

        /// <summary>
        /// branch_name
        /// </summary>
        [AttributeField("branch_name", "System.String", false, false, false, "String")]
        public string branch_name
        {
            get
            {
                return this._branch_name;
            }
            set
            {
                this._branch_name = value;
            }
        }

        /// <summary>
        /// account
        /// </summary>
        [AttributeField("account", "System.String", false, false, false, "String")]
        public string account
        {
            get
            {
                return this._account;
            }
            set
            {
                this._account = value;
            }
        }

        /// <summary>
        /// check_num
        /// </summary>
        [AttributeField("check_num", "System.String", false, false, false, "String")]
        public string check_num
        {
            get
            {
                return this._check_num;
            }
            set
            {
                this._check_num = value;
            }
        }

        /// <summary>
        /// account1
        /// </summary>
        [AttributeField("account1", "System.String", false, false, false, "String")]
        public string account1
        {
            get
            {
                return this._account1;
            }
            set
            {
                this._account1 = value;
            }
        }

        /// <summary>
        /// account2
        /// </summary>
        [AttributeField("account2", "System.String", false, false, false, "String")]
        public string account2
        {
            get
            {
                return this._account2;
            }
            set
            {
                this._account2 = value;
            }
        }

        /// <summary>
        /// cancel_code1
        /// </summary>
        [AttributeField("cancel_code1", "System.String", false, false, false, "String")]
        public string cancel_code1
        {
            get
            {
                return this._cancel_code1;
            }
            set
            {
                this._cancel_code1 = value;
            }
        }

        /// <summary>
        /// cancel_date
        /// </summary>
        [AttributeField("cancel_date", "System.String", false, false, false, "String")]
        public string cancel_date
        {
            get
            {
                return this._cancel_date;
            }
            set
            {
                this._cancel_date = value;
            }
        }

        /// <summary>
        /// cancel_code2
        /// </summary>
        [AttributeField("cancel_code2", "System.String", false, false, false, "String")]
        public string cancel_code2
        {
            get
            {
                return this._cancel_code2;
            }
            set
            {
                this._cancel_code2 = value;
            }
        }

        /// <summary>
        /// imp1
        /// </summary>
        [AttributeField("imp1", "System.String", false, false, false, "String")]
        public string imp1
        {
            get
            {
                return this._imp1;
            }
            set
            {
                this._imp1 = value;
            }
        }

        /// <summary>
        /// imp2
        /// </summary>
        [AttributeField("imp2", "System.String", false, false, false, "String")]
        public string imp2
        {
            get
            {
                return this._imp2;
            }
            set
            {
                this._imp2 = value;
            }
        }

        /// <summary>
        /// imp_money
        /// </summary>
        [AttributeField("imp_money", "System.String", false, false, false, "String")]
        public string imp_money
        {
            get
            {
                return this._imp_money;
            }
            set
            {
                this._imp_money = value;
            }
        }

        /// <summary>
        /// pos1
        /// </summary>
        [AttributeField("pos1", "System.String", false, false, false, "String")]
        public string pos1
        {
            get
            {
                return this._pos1;
            }
            set
            {
                this._pos1 = value;
            }
        }

        /// <summary>
        /// pos2
        /// </summary>
        [AttributeField("pos2", "System.String", false, false, false, "String")]
        public string pos2
        {
            get
            {
                return this._pos2;
            }
            set
            {
                this._pos2 = value;
            }
        }

        /// <summary>
        /// pos_money
        /// </summary>
        [AttributeField("pos_money", "System.String", false, false, false, "String")]
        public string pos_money
        {
            get
            {
                return this._pos_money;
            }
            set
            {
                this._pos_money = value;
            }
        }

        /// <summary>
        /// edc1
        /// </summary>
        [AttributeField("edc1", "System.String", false, false, false, "String")]
        public string edc1
        {
            get
            {
                return this._edc1;
            }
            set
            {
                this._edc1 = value;
            }
        }

        /// <summary>
        /// edcnum
        /// </summary>
        [AttributeField("edcnum", "System.String", false, false, false, "String")]
        public string edcnum
        {
            get
            {
                return this._edcnum;
            }
            set
            {
                this._edcnum = value;
            }
        }

        /// <summary>
        /// edc
        /// </summary>
        [AttributeField("edc", "System.String", false, false, false, "String")]
        public string edc
        {
            get
            {
                return this._edc;
            }
            set
            {
                this._edc = value;
            }
        }

        /// <summary>
        /// edc_money
        /// </summary>
        [AttributeField("edc_money", "System.String", false, false, false, "String")]
        public string edc_money
        {
            get
            {
                return this._edc_money;
            }
            set
            {
                this._edc_money = value;
            }
        }

        /// <summary>
        /// undertaker_add3
        /// </summary>
        [AttributeField("undertaker_add3", "System.String", false, false, false, "String")]
        public string undertaker_add3
        {
            get
            {
                return this._undertaker_add3;
            }
            set
            {
                this._undertaker_add3 = value;
            }
        }

        /// <summary>
        /// realperson_add3
        /// </summary>
        [AttributeField("realperson_add3", "System.String", false, false, false, "String")]
        public string realperson_add3
        {
            get
            {
                return this._realperson_add3;
            }
            set
            {
                this._realperson_add3 = value;
            }
        }

        /// <summary>
        /// junctionperson_recadd3
        /// </summary>
        [AttributeField("junctionperson_recadd3", "System.String", false, false, false, "String")]
        public string junctionperson_recadd3
        {
            get
            {
                return this._junctionperson_recadd3;
            }
            set
            {
                this._junctionperson_recadd3 = value;
            }
        }

        /// <summary>
        /// junctionperson_realadd3
        /// </summary>
        [AttributeField("junctionperson_realadd3", "System.String", false, false, false, "String")]
        public string junctionperson_realadd3
        {
            get
            {
                return this._junctionperson_realadd3;
            }
            set
            {
                this._junctionperson_realadd3 = value;
            }
        }

        /// <summary>
        /// MERCHANT_NAME
        /// </summary>
        [AttributeField("MERCHANT_NAME", "System.String", false, false, false, "String")]
        public string MERCHANT_NAME
        {
            get
            {
                return this._MERCHANT_NAME;
            }
            set
            {
                this._MERCHANT_NAME = value;
            }
        }

        /// <summary>
        /// P4
        /// </summary>
        [AttributeField("P4", "System.Nullable`1[System.Int32]", false, false, false, "Int32")]
        public System.Nullable<int> P4
        {
            get
            {
                return this._P4;
            }
            set
            {
                this._P4 = value;
            }
        }

        /// <summary>
        /// p4A
        /// </summary>
        [AttributeField("p4A", "System.Nullable`1[System.Int32]", false, false, false, "Int32")]
        public System.Nullable<int> p4A
        {
            get
            {
                return this._p4A;
            }
            set
            {
                this._p4A = value;
            }
        }

        /// <summary>
        /// KeyIn_Flag
        /// </summary>
        [AttributeField("KeyIn_Flag", "System.String", false, true, false, "String")]
        public string KeyIn_Flag
        {
            get
            {
                return this._KeyIn_Flag;
            }
            set
            {
                this._KeyIn_Flag = value;
            }
        }

        /// <summary>
        /// user_id
        /// </summary>
        [AttributeField("user_id", "System.String", false, false, false, "String")]
        public string user_id
        {
            get
            {
                return this._user_id;
            }
            set
            {
                this._user_id = value;
            }
        }

        /// <summary>
        /// mod_date
        /// </summary>
        [AttributeField("mod_date", "System.String", false, false, false, "String")]
        public string mod_date
        {
            get
            {
                return this._mod_date;
            }
            set
            {
                this._mod_date = value;
            }
        }

        /// <summary>
        /// realadd_zip
        /// </summary>
        [AttributeField("realadd_zip", "System.String", false, false, false, "String")]
        public string realadd_zip
        {
            get
            {
                return this._realadd_zip;
            }
            set
            {
                this._realadd_zip = value;
            }
        }

        /// <summary>
        /// undertaker_EngName
        /// </summary>
        [AttributeField("undertaker_EngName", "System.String", false, false, false, "String")]
        public string undertaker_EngName
        {
            get
            {
                return this._undertaker_EngName;
            }
            set
            {
                this._undertaker_EngName = value;
            }
        }

        /// <summary>
        /// introduce_flag
        /// </summary>
        [AttributeField("introduce_flag", "System.String", false, false, false, "String")]
        public string introduce_flag
        {
            get
            {
                return this._introduce_flag;
            }
            set
            {
                this._introduce_flag = value;
            }
        }

        /// <summary>
        /// invoice_cycle
        /// </summary>
        [AttributeField("invoice_cycle", "System.String", false, false, false, "String")]
        public string invoice_cycle
        {
            get
            {
                return this._invoice_cycle;
            }
            set
            {
                this._invoice_cycle = value;
            }
        }

        /// <summary>
        /// HOLD_STMT
        /// </summary>
        [AttributeField("HOLD_STMT", "System.String", false, false, false, "String")]
        public string HOLD_STMT
        {
            get
            {
                return this._HOLD_STMT;
            }
            set
            {
                this._HOLD_STMT = value;
            }
        }

        /// <summary>
        /// Change_Item
        /// </summary>
        [AttributeField("Change_Item", "System.String", false, false, false, "String")]
        public string Change_Item
        {
            get
            {
                return this._Change_Item;
            }
            set
            {
                this._Change_Item = value;
            }
        }

        /// <summary>
        /// addjcb_us
        /// </summary>
        [AttributeField("addjcb_us", "System.String", false, false, false, "String")]
        public string addjcb_us
        {
            get
            {
                return this._addjcb_us;
            }
            set
            {
                this._addjcb_us = value;
            }
        }

        /// <summary>
        /// addjcb_notus
        /// </summary>
        [AttributeField("addjcb_notus", "System.String", false, false, false, "String")]
        public string addjcb_notus
        {
            get
            {
                return this._addjcb_notus;
            }
            set
            {
                this._addjcb_notus = value;
            }
        }

        /// <summary>
        /// rate02N
        /// </summary>
        [AttributeField("rate02N", "System.String", false, false, false, "String")]
        public string rate02N
        {
            get
            {
                return this._rate02N;
            }
            set
            {
                this._rate02N = value;
            }
        }

        /// <summary>
        /// rate03V
        /// </summary>
        [AttributeField("rate03V", "System.String", false, false, false, "String")]
        public string rate03V
        {
            get
            {
                return this._rate03V;
            }
            set
            {
                this._rate03V = value;
            }
        }

        /// <summary>
        /// rate04V
        /// </summary>
        [AttributeField("rate04V", "System.String", false, false, false, "String")]
        public string rate04V
        {
            get
            {
                return this._rate04V;
            }
            set
            {
                this._rate04V = value;
            }
        }

        /// <summary>
        /// rate05M
        /// </summary>
        [AttributeField("rate05M", "System.String", false, false, false, "String")]
        public string rate05M
        {
            get
            {
                return this._rate05M;
            }
            set
            {
                this._rate05M = value;
            }
        }

        /// <summary>
        /// rate06M
        /// </summary>
        [AttributeField("rate06M", "System.String", false, false, false, "String")]
        public string rate06M
        {
            get
            {
                return this._rate06M;
            }
            set
            {
                this._rate06M = value;
            }
        }

        /// <summary>
        /// rate07J
        /// </summary>
        [AttributeField("rate07J", "System.String", false, false, false, "String")]
        public string rate07J
        {
            get
            {
                return this._rate07J;
            }
            set
            {
                this._rate07J = value;
            }
        }

        /// <summary>
        /// rate08J
        /// </summary>
        [AttributeField("rate08J", "System.String", false, false, false, "String")]
        public string rate08J
        {
            get
            {
                return this._rate08J;
            }
            set
            {
                this._rate08J = value;
            }
        }

        /// <summary>
        /// rate09
        /// </summary>
        [AttributeField("rate09", "System.String", false, false, false, "String")]
        public string rate09
        {
            get
            {
                return this._rate09;
            }
            set
            {
                this._rate09 = value;
            }
        }

        /// <summary>
        /// rate10
        /// </summary>
        [AttributeField("rate10", "System.String", false, false, false, "String")]
        public string rate10
        {
            get
            {
                return this._rate10;
            }
            set
            {
                this._rate10 = value;
            }
        }

        /// <summary>
        /// rate11
        /// </summary>
        [AttributeField("rate11", "System.String", false, false, false, "String")]
        public string rate11
        {
            get
            {
                return this._rate11;
            }
            set
            {
                this._rate11 = value;
            }
        }

        /// <summary>
        /// rate13
        /// </summary>
        [AttributeField("rate13", "System.String", false, false, false, "String")]
        public string rate13
        {
            get
            {
                return this._rate13;
            }
            set
            {
                this._rate13 = value;
            }
        }

        /// <summary>
        /// rate12
        /// </summary>
        [AttributeField("rate12", "System.String", false, false, false, "String")]
        public string rate12
        {
            get
            {
                return this._rate12;
            }
            set
            {
                this._rate12 = value;
            }
        }

        /// <summary>
        /// rate14
        /// </summary>
        [AttributeField("rate14", "System.String", false, false, false, "String")]
        public string rate14
        {
            get
            {
                return this._rate14;
            }
            set
            {
                this._rate14 = value;
            }
        }

        /// <summary>
        /// rate15
        /// </summary>
        [AttributeField("rate15", "System.String", false, false, false, "String")]
        public string rate15
        {
            get
            {
                return this._rate15;
            }
            set
            {
                this._rate15 = value;
            }
        }

        /// <summary>
        /// shop_type
        /// </summary>
        [AttributeField("shop_type", "System.String", false, true, false, "String")]
        public string shop_type
        {
            get
            {
                return this._shop_type;
            }
            set
            {
                this._shop_type = value;
            }
        }

        /// <summary>
        /// imp1_type
        /// </summary>
        [AttributeField("imp1_type", "System.String", false, false, false, "String")]
        public string imp1_type
        {
            get
            {
                return this._imp1_type;
            }
            set
            {
                this._imp1_type = value;
            }
        }

        /// <summary>
        /// imp2_type
        /// </summary>
        [AttributeField("imp2_type", "System.String", false, false, false, "String")]
        public string imp2_type
        {
            get
            {
                return this._imp2_type;
            }
            set
            {
                this._imp2_type = value;
            }
        }

        /// <summary>
        /// pos1_type
        /// </summary>
        [AttributeField("pos1_type", "System.String", false, false, false, "String")]
        public string pos1_type
        {
            get
            {
                return this._pos1_type;
            }
            set
            {
                this._pos1_type = value;
            }
        }

        /// <summary>
        /// pos2_type
        /// </summary>
        [AttributeField("pos2_type", "System.String", false, false, false, "String")]
        public string pos2_type
        {
            get
            {
                return this._pos2_type;
            }
            set
            {
                this._pos2_type = value;
            }
        }

        /// <summary>
        /// edc1_type
        /// </summary>
        [AttributeField("edc1_type", "System.String", false, false, false, "String")]
        public string edc1_type
        {
            get
            {
                return this._edc1_type;
            }
            set
            {
                this._edc1_type = value;
            }
        }

        /// <summary>
        /// edc_type
        /// </summary>
        [AttributeField("edc_type", "System.String", false, false, false, "String")]
        public string edc_type
        {
            get
            {
                return this._edc_type;
            }
            set
            {
                this._edc_type = value;
            }
        }

        /// <summary>
        /// cup_status1
        /// </summary>
        [AttributeField("cup_status1", "System.String", false, false, false, "String")]
        public string cup_status1
        {
            get
            {
                return this._cup_status1;
            }
            set
            {
                this._cup_status1 = value;
            }
        }

        /// <summary>
        /// cup_status2
        /// </summary>
        [AttributeField("cup_status2", "System.String", false, false, false, "String")]
        public string cup_status2
        {
            get
            {
                return this._cup_status2;
            }
            set
            {
                this._cup_status2 = value;
            }
        }

        /// <summary>
        /// cup_status3
        /// </summary>
        [AttributeField("cup_status3", "System.String", false, false, false, "String")]
        public string cup_status3
        {
            get
            {
                return this._cup_status3;
            }
            set
            {
                this._cup_status3 = value;
            }
        }

        /// <summary>
        /// cup_status4
        /// </summary>
        [AttributeField("cup_status4", "System.String", false, false, false, "String")]
        public string cup_status4
        {
            get
            {
                return this._cup_status4;
            }
            set
            {
                this._cup_status4 = value;
            }
        }

        /// <summary>
        /// cup_status5
        /// </summary>
        [AttributeField("cup_status5", "System.String", false, false, false, "String")]
        public string cup_status5
        {
            get
            {
                return this._cup_status5;
            }
            set
            {
                this._cup_status5 = value;
            }
        }

        /// <summary>
        /// cup_status6
        /// </summary>
        [AttributeField("cup_status6", "System.String", false, false, false, "String")]
        public string cup_status6
        {
            get
            {
                return this._cup_status6;
            }
            set
            {
                this._cup_status6 = value;
            }
        }

        /// <summary>
        /// cup_status7
        /// </summary>
        [AttributeField("cup_status7", "System.String", false, false, false, "String")]
        public string cup_status7
        {
            get
            {
                return this._cup_status7;
            }
            set
            {
                this._cup_status7 = value;
            }
        }

        /// <summary>
        /// cup_status8
        /// </summary>
        [AttributeField("cup_status8", "System.String", false, false, false, "String")]
        public string cup_status8
        {
            get
            {
                return this._cup_status8;
            }
            set
            {
                this._cup_status8 = value;
            }
        }

        /// <summary>
        /// cup_status9
        /// </summary>
        [AttributeField("cup_status9", "System.String", false, false, false, "String")]
        public string cup_status9
        {
            get
            {
                return this._cup_status9;
            }
            set
            {
                this._cup_status9 = value;
            }
        }

        /// <summary>
        /// cup_status10
        /// </summary>
        [AttributeField("cup_status10", "System.String", false, false, false, "String")]
        public string cup_status10
        {
            get
            {
                return this._cup_status10;
            }
            set
            {
                this._cup_status10 = value;
            }
        }

        /// <summary>
        /// cup_rate1
        /// </summary>
        [AttributeField("cup_rate1", "System.String", false, false, false, "String")]
        public string cup_rate1
        {
            get
            {
                return this._cup_rate1;
            }
            set
            {
                this._cup_rate1 = value;
            }
        }

        /// <summary>
        /// cup_rate2
        /// </summary>
        [AttributeField("cup_rate2", "System.String", false, false, false, "String")]
        public string cup_rate2
        {
            get
            {
                return this._cup_rate2;
            }
            set
            {
                this._cup_rate2 = value;
            }
        }

        /// <summary>
        /// cup_rate3
        /// </summary>
        [AttributeField("cup_rate3", "System.String", false, false, false, "String")]
        public string cup_rate3
        {
            get
            {
                return this._cup_rate3;
            }
            set
            {
                this._cup_rate3 = value;
            }
        }

        /// <summary>
        /// cup_rate4
        /// </summary>
        [AttributeField("cup_rate4", "System.String", false, false, false, "String")]
        public string cup_rate4
        {
            get
            {
                return this._cup_rate4;
            }
            set
            {
                this._cup_rate4 = value;
            }
        }

        /// <summary>
        /// cup_rate5
        /// </summary>
        [AttributeField("cup_rate5", "System.String", false, false, false, "String")]
        public string cup_rate5
        {
            get
            {
                return this._cup_rate5;
            }
            set
            {
                this._cup_rate5 = value;
            }
        }

        /// <summary>
        /// cup_rate6
        /// </summary>
        [AttributeField("cup_rate6", "System.String", false, false, false, "String")]
        public string cup_rate6
        {
            get
            {
                return this._cup_rate6;
            }
            set
            {
                this._cup_rate6 = value;
            }
        }

        /// <summary>
        /// cup_rate7
        /// </summary>
        [AttributeField("cup_rate7", "System.String", false, false, false, "String")]
        public string cup_rate7
        {
            get
            {
                return this._cup_rate7;
            }
            set
            {
                this._cup_rate7 = value;
            }
        }

        /// <summary>
        /// cup_rate8
        /// </summary>
        [AttributeField("cup_rate8", "System.String", false, false, false, "String")]
        public string cup_rate8
        {
            get
            {
                return this._cup_rate8;
            }
            set
            {
                this._cup_rate8 = value;
            }
        }

        /// <summary>
        /// cup_rate9
        /// </summary>
        [AttributeField("cup_rate9", "System.String", false, false, false, "String")]
        public string cup_rate9
        {
            get
            {
                return this._cup_rate9;
            }
            set
            {
                this._cup_rate9 = value;
            }
        }

        /// <summary>
        /// cup_rate10
        /// </summary>
        [AttributeField("cup_rate10", "System.String", false, false, false, "String")]
        public string cup_rate10
        {
            get
            {
                return this._cup_rate10;
            }
            set
            {
                this._cup_rate10 = value;
            }
        }

        /// <summary>
        /// ReqAppro
        /// </summary>
        [AttributeField("ReqAppro", "System.String", false, false, false, "String")]
        public string ReqAppro
        {
            get
            {
                return this._ReqAppro;
            }
            set
            {
                this._ReqAppro = value;
            }
        }
    }

    /// <summary>
    /// shop
    /// </summary>
    [Serializable()]
    public class EntitySHOPSet : EntitySet<EntitySHOP>
    {
    }
}
