//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPKeyInGUI.EntityLayer
{


    /// <summary>
    /// Auto_Pay_Popul
    /// </summary>
    [Serializable()]
    [AttributeTable("Auto_Pay_Popul")]
    public class EntityAuto_Pay_Popul : Entity
    {

        private string _Receive_Number;

        /// <summary>
        /// Receive_Number
        /// </summary>
        public static string M_Receive_Number = "Receive_Number";

        private string _Cus_Id;

        /// <summary>
        /// Cus_Id
        /// </summary>
        public static string M_Cus_Id = "Cus_Id";

        private string _Case_Class;

        /// <summary>
        /// Case_Class
        /// </summary>
        public static string M_Case_Class = "Case_Class";

        private string _Popul_No;

        /// <summary>
        /// Popul_No
        /// </summary>
        public static string M_Popul_No = "Popul_No";

        private string _Popul_EmpNo;

        /// <summary>
        /// Popul_EmpNo
        /// </summary>
        public static string M_Popul_EmpNo = "Popul_EmpNo";

        private string _isEnd;

        /// <summary>
        /// isEnd
        /// </summary>
        public static string M_isEnd = "isEnd";

        private string _FUNCTION_CODE;

        /// <summary>
        /// FUNCTION_CODE
        /// </summary>
        public static string M_FUNCTION_CODE = "FUNCTION_CODE";

        private object _mod_date;

        /// <summary>
        /// mod_date
        /// </summary>
        public static string M_mod_date = "mod_date";

        private string _KeyIn_Flag;

        /// <summary>
        /// KeyIn_Flag
        /// </summary>
        public static string M_KeyIn_Flag = "KeyIn_Flag";

        private string _User_Id;

        /// <summary>
        /// User_Id
        /// </summary>
        public static string M_User_Id = "User_Id";

        private string _AccNoBank;

        /// <summary>
        /// AccNoBank
        /// </summary>
        public static string M_AccNoBank = "AccNoBank";

        private string _Acc_No;

        /// <summary>
        /// Acc_No
        /// </summary>
        public static string M_Acc_No = "Acc_No";

        private string _Acc_Id;

        /// <summary>
        /// Acc_Id
        /// </summary>
        public static string M_Acc_Id = "Acc_Id";

        private string _Cus_name;

        /// <summary>
        /// Cus_name
        /// </summary>
        public static string M_Cus_name = "Cus_name";

        private string _Pay_Way;
        /// <summary>
        /// Pay_Way
        /// </summary>
        public static string M_Pay_Way = "Pay_Way";

        private string _bcycle_code;
        /// <summary>
        /// bcycle_code
        /// </summary>
        public static string M_bcycle_code = "bcycle_code";

        /// <summary>
        /// Receive_Number
        /// </summary>
        [AttributeField("Receive_Number", "System.String", false, false, false, "String")]
        public string Receive_Number
        {
            get
            {
                return this._Receive_Number;
            }
            set
            {
                this._Receive_Number = value;
            }
        }

        /// <summary>
        /// Cus_Id
        /// </summary>
        [AttributeField("Cus_Id", "System.String", false, false, false, "String")]
        public string Cus_Id
        {
            get
            {
                return this._Cus_Id;
            }
            set
            {
                this._Cus_Id = value;
            }
        }

        /// <summary>
        /// Case_Class
        /// </summary>
        [AttributeField("Case_Class", "System.String", false, false, false, "String")]
        public string Case_Class
        {
            get
            {
                return this._Case_Class;
            }
            set
            {
                this._Case_Class = value;
            }
        }

        /// <summary>
        /// Popul_No
        /// </summary>
        [AttributeField("Popul_No", "System.Char", false, false, false, "String")]
        public string Popul_No
        {
            get
            {
                return this._Popul_No;
            }
            set
            {
                this._Popul_No = value;
            }
        }

        /// <summary>
        /// Popul_EmpNo
        /// </summary>
        [AttributeField("Popul_EmpNo", "System.Char", false, false, false, "String")]
        public string Popul_EmpNo
        {
            get
            {
                return this._Popul_EmpNo;
            }
            set
            {
                this._Popul_EmpNo = value;
            }
        }

        /// <summary>
        /// isEnd
        /// </summary>
        [AttributeField("isEnd", "System.Char", false, false, false, "String")]
        public string isEnd
        {
            get
            {
                return this._isEnd;
            }
            set
            {
                this._isEnd = value;
            }
        }

        /// <summary>
        /// FUNCTION_CODE
        /// </summary>
        [AttributeField("FUNCTION_CODE", "System.Char", false, false, false, "String")]
        public string FUNCTION_CODE
        {
            get
            {
                return this._FUNCTION_CODE;
            }
            set
            {
                this._FUNCTION_CODE = value;
            }
        }
       
        /// <summary>
        /// mod_date
        /// </summary>
        [AttributeField("mod_date", "System.DateTime", false, false, false, "DateTime")]
        public object mod_date
        {
            get
            {
                return this._mod_date;
            }
            set
            {
                this._mod_date = value;
            }
        }

        /// <summary>
        /// KeyIn_Flag
        /// </summary>
        [AttributeField("KeyIn_Flag", "System.Char", false, false, false, "String")]
        public string KeyIn_Flag
        {
            get
            {
                return this._KeyIn_Flag;
            }
            set
            {
                this._KeyIn_Flag = value;
            }
        }

        /// <summary>
        /// User_Id
        /// </summary>
        [AttributeField("User_Id", "System.String", false, false, false, "String")]
        public string User_Id
        {
            get
            {
                return this._User_Id;
            }
            set
            {
                this._User_Id = value;
            }
        }

        /// <summary>
        /// AccNoBank
        /// </summary>
        [AttributeField("AccNoBank", "System.String", false, false, false, "String")]
        public string AccNoBank
        {
            get
            {
                return this._AccNoBank;
            }
            set
            {
                this._AccNoBank = value;
            }
        }

        /// <summary>
        /// Acc_No
        /// </summary>
        [AttributeField("Acc_No", "System.String", false, false, false, "String")]
        public string Acc_No
        {
            get
            {
                return this._Acc_No;
            }
            set
            {
                this._Acc_No = value;
            }
        }

        /// <summary>
        /// Acc_Id
        /// </summary>
        [AttributeField("Acc_Id", "System.String", false, false, false, "String")]
        public string Acc_Id
        {
            get
            {
                return this._Acc_Id;
            }
            set
            {
                this._Acc_Id = value;
            }
        }

        /// <summary>
        /// Cus_name
        /// </summary>
        [AttributeField("Cus_name", "System.String", false, false, false, "String")]
        public string Cus_name
        {
            get
            {
                return this._Cus_name;
            }
            set
            {
                this._Cus_name = value;
            }
        }

        /// <summary>
        /// Pay_Way
        /// </summary>
        [AttributeField("Pay_way", "System.String", false, false, false, "String")]
        public string pay_way
        {
            get
            {
                return this._Pay_Way;
            }
            set
            {
                this._Pay_Way = value;
            }
        }

        /// <summary>
        /// bcycle_code
        /// </summary>
        [AttributeField("bcycle_code", "System.String", false, false, false, "String")]
        public string bcycle_code
        {
            get
            {
                return this._bcycle_code;
            }
            set
            {
                this._bcycle_code = value;
            }
        }
    }

    /// <summary>
    /// Auto_Pay_Popul
    /// </summary>
    [Serializable()]
    public class Auto_Pay_PopulSet : EntitySet<EntityAuto_Pay_Popul>
    {
    }
}
