//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPKeyInGUI.EntityLayer
{


    /// <summary>
    /// shop_1keylog
    /// </summary>
    [Serializable()]
    [AttributeTable("AML_CHECKLOG")]
    public class EntityAML_CHECKLOG : Entity
    {        
        private string _CORP_NO;

        /// <summary>
        /// CORP_NO
        /// </summary>
        public static string M_CORP_NO = "CORP_NO";

        private string _MER_NO;

        /// <summary>
        /// CORP_NO
        /// </summary>
        public static string M_MER_NO = "MER_NO";

        private string _TRANS_ID;

        /// <summary>
        /// TRANS_ID
        /// </summary>
        public static string M_TRANS_ID = "TRANS_ID";

        private string _LAST_UPD_MAKER;

        /// <summary>
        /// LAST_UPD_MAKER
        /// </summary>
        public static string M_LAST_UPD_MAKER = "LAST_UPD_MAKER";

        private string _LAST_UPD_CHECKER;

        /// <summary>
        /// LAST_UPD_CHECKER
        /// </summary>
        public static string M_LAST_UPD_CHECKER = "LAST_UPD_CHECKER";

        private string _LAST_UPD_BRANCH;

        /// <summary>
        /// LAST_UPD_BRANCH
        /// </summary>
        public static string M_LAST_UPD_BRANCH = "LAST_UPD_BRANCH";

        private string _MOD_USERID;

        /// <summary>
        /// MOD_USERID
        /// </summary>
        public static string M_MOD_USERID = "MOD_USERID";

        private string _MOD_DATE;

        /// <summary>
        /// MOD_DATE
        /// </summary>
        public static string M_MOD_DATE = "MOD_DATE";

        private string _MOD_TIME;

        /// <summary>
        /// MOD_TIME
        /// </summary>
        public static string M_MOD_TIME = "MOD_TIME";
        
        /// <summary>
        /// CORP_NO
        /// </summary>
        [AttributeField("CORP_NO", "System.String", false, true, false, "String")]
        public string CORP_NO
        {
            get
            {
                return this._CORP_NO;
            }
            set
            {
                this._CORP_NO = value;
            }
        }

        /// <summary>
        /// MER_NO
        /// </summary>
        [AttributeField("MER_NO", "System.String", false, false, false, "String")]
        public string MER_NO
        {
            get
            {
                return this._MER_NO;
            }
            set
            {
                this._MER_NO = value;
            }
        }

        /// <summary>
        /// TRANS_ID
        /// </summary>
        [AttributeField("TRANS_ID", "System.String", false, false, false, "String")]
        public string TRANS_ID
        {
            get
            {
                return this._TRANS_ID;
            }
            set
            {
                this._TRANS_ID = value;
            }
        }

        /// <summary>
        /// LAST_UPD_MAKER
        /// </summary>
        [AttributeField("LAST_UPD_MAKER", "System.String", false, false, false, "String")]
        public string LAST_UPD_MAKER
        {
            get
            {
                return this._LAST_UPD_MAKER;
            }
            set
            {
                this._LAST_UPD_MAKER = value;
            }
        }

        /// <summary>
        /// LAST_UPD_CHECKER
        /// </summary>
        [AttributeField("LAST_UPD_CHECKER", "System.String", false, false, false, "String")]
        public string LAST_UPD_CHECKER
        {
            get
            {
                return this._LAST_UPD_CHECKER;
            }
            set
            {
                this._LAST_UPD_CHECKER = value;
            }
        }

        /// <summary>
        /// LAST_UPD_BRANCH
        /// </summary>
        [AttributeField("LAST_UPD_BRANCH", "System.String", false, false, false, "String")]
        public string LAST_UPD_BRANCH
        {
            get
            {
                return this._LAST_UPD_BRANCH;
            }
            set
            {
                this._LAST_UPD_BRANCH = value;
            }
        }

        /// <summary>
        /// MOD_USERID
        /// </summary>
        [AttributeField("MOD_USERID", "System.String", false, false, false, "String")]
        public string MOD_USERID
        {
            get
            {
                return this._MOD_USERID;
            }
            set
            {
                this._MOD_USERID = value;
            }
        }

        /// <summary>
        /// MOD_DATE
        /// </summary>
        [AttributeField("MOD_DATE", "System.String", false, false, false, "String")]
        public string MOD_DATE
        {
            get
            {
                return this._MOD_DATE;
            }
            set
            {
                this._MOD_DATE = value;
            }
        }

        /// <summary>
        /// MOD_TIME
        /// </summary>
        [AttributeField("MOD_TIME", "System.String", false, false, false, "String")]
        public string MOD_TIME
        {
            get
            {
                return this._MOD_TIME;
            }
            set
            {
                this._MOD_TIME = value;
            }
        }        
    }

    /// <summary>
    /// shop_1keylog
    /// </summary>
    [Serializable()]
    public class EntityAML_CHECKLOGSet : EntitySet<EntityAML_CHECKLOG>
    {
    }
}
