//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPNewInvoice.EntityLayer_new
{
    /// <summary>
    /// AML_HeadOffice
    /// </summary>
    [Serializable()]
    [AttributeTable("AML_AddHeadOfficeReport")]
    public class EntityAML_AddHeadOfficeReport : Entity
    {
        /// <summary>
        /// 建構式，建立時將高階經理人物件預設建立，避免NULL
        /// </summary>
        public EntityAML_AddHeadOfficeReport()
        {
           
        }
        private string _ID;
        /// <summary>
        /// ID
        /// </summary>
        [AttributeRfPage("txtID", "CustTextBox", false)]
        public string ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this._ID = value;
            }
        }
        private string _TaxID;
        /// <summary>
        /// TaxID
        /// </summary>
        [AttributeRfPage("txtTaxID", "CustTextBox", false)]
        public string TaxID
        {
            get
            {
                return this._TaxID;
            }
            set
            {
                this._TaxID = value;
            }
        }
        private string _Branch_TaxID;
        /// <summary>
        /// Branch_TaxID
        /// </summary>
        [AttributeRfPage("txtBranch_TaxID", "CustTextBox", false)]
        public string Branch_TaxID
        {
            get
            {
                return this._Branch_TaxID;
            }
            set
            {
                this._Branch_TaxID = value;
            }
        }
        private string _Branch_No;
        /// <summary>
        /// Branch_No
        /// </summary>
        [AttributeRfPage("txtBranch_No", "CustTextBox", false)]
        public string Branch_No
        {
            get
            {
                return this._Branch_No;
            }
            set
            {
                this._Branch_No = value;
            }
        }
        private string _Recv_no;
        /// <summary>
        /// Recv_no
        /// </summary>
        [AttributeRfPage("txtRecv_no", "CustTextBox", false)]
        public string Recv_no
        {
            get
            {
                return this._Recv_no;
            }
            set
            {
                this._Recv_no = value;
            }
        }
        private string _Create_day;
        /// <summary>
        /// Create_day
        /// </summary>
        [AttributeRfPage("txtCreate_day", "CustTextBox", false)]
        public string Create_day
        {
            get
            {
                return this._Create_day;
            }
            set
            {
                this._Create_day = value;
            }
        }
        private string _OfficeAdd_day;
        /// <summary>
        /// OfficeAdd_day
        /// </summary>
        [AttributeRfPage("txtOfficeAdd_day", "CustTextBox", false)]
        public string OfficeAdd_day
        {
            get
            {
                return this._OfficeAdd_day;
            }
            set
            {
                this._OfficeAdd_day = value;
            }
        }


    }
}
