//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPNewInvoice.EntityLayer_new
{
    /// <summary>
    /// AML_HeadOffice
    /// </summary>
    [Serializable()] 
    public class EntityAML_DtlMaster
    {
        public EntityAML_DtlMaster()
        {
        }

        AML_SessionState _DetailHeader;

        /// <summary>
        /// 表頭資料
        /// </summary>
       public AML_SessionState DetailHeader
        {
            get { return _DetailHeader; }
            set { _DetailHeader = value; }
        }

        EntityAML_HQ_Work _AML_HQ_Work; 
        /// <summary>
        /// 總公司資料
        /// </summary>
        public EntityAML_HQ_Work AML_HQ_Work
        {
            get { return _AML_HQ_Work; }
            set { _AML_HQ_Work = value; }
        }
  
        /// <summary>
        /// 總公司資料
        /// </summary>
        public EntityAML_HQ_Work_edit AML_HQ_Work_edit
        {
            get { return _AML_HQ_Work.toEditMode(); }
            set { _AML_HQ_Work = value.toShowMode();
            }
        } 

        EntityAML_Cdata_Work _AML_CdataWork;
        /// <summary>
        /// 總公司資料
        /// </summary>
        public EntityAML_Cdata_Work AML_Cdata_Work
        {
            get { return _AML_CdataWork; }
            set { _AML_CdataWork = value; }
        }
    
        /// <summary>
        /// 總公司資料
        /// </summary>
        public EntityAML_Cdata_Work_edit AML_Cdata_Work_edit
        {
            get { return _AML_CdataWork.toEditMode(); }
            set
            {
                _AML_CdataWork = value.toShowMode();
            }
        }
    }
}