//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPNewInvoice.EntityLayer_new
{
    /// <summary>
    /// AML_HeadOffice
    /// </summary>
    [Serializable()]
    [AttributeTable("AML_Edata_Work")]
    public class EntityAML_Edata_Work : Entity
    {
        public EntityAML_Edata_Work()
        {
        }
        private string _ID;
        /// <summary>
        /// ID
        /// </summary>
        [AttributeRfPage("txtID", "CustLabel", false)]
        public string ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this._ID = value;
            }
        }
        private string _CASE_NO;
        /// <summary>
        /// CASE_NO
        /// </summary>
        [AttributeRfPage("txtCASE_NO", "CustLabel", false)]
        public string CASE_NO
        {
            get
            {
                return this._CASE_NO;
            }
            set
            {
                this._CASE_NO = value;
            }
        }
        private string _FileName;
        /// <summary>
        /// FileName
        /// </summary>
        [AttributeRfPage("txtFileName", "CustLabel", false)]
        public string FileName
        {
            get
            {
                return this._FileName;
            }
            set
            {
                this._FileName = value;
            }
        }
        private string _RMMBatchNo;
        /// <summary>
        /// RMMBatchNo
        /// </summary>
        [AttributeRfPage("txtRMMBatchNo", "CustLabel", false)]
        public string RMMBatchNo
        {
            get
            {
                return this._RMMBatchNo;
            }
            set
            {
                this._RMMBatchNo = value;
            }
        }
        private string _AMLInternalID;
        /// <summary>
        /// AMLInternalID
        /// </summary>
        [AttributeRfPage("txtAMLInternalID", "CustLabel", false)]
        public string AMLInternalID
        {
            get
            {
                return this._AMLInternalID;
            }
            set
            {
                this._AMLInternalID = value;
            }
        }
        private string _DataDate;
        /// <summary>
        /// DataDate
        /// </summary>
        [AttributeRfPage("txtDataDate", "CustLabel", false)]
        public string DataDate
        {
            get
            {
                return this._DataDate;
            }
            set
            {
                this._DataDate = value;
            }
        }
        private string _CustomerID;
        /// <summary>
        /// CustomerID
        /// </summary>
        [AttributeRfPage("txtCustomerID", "CustLabel", false)]
        public string CustomerID
        {
            get
            {
                return this._CustomerID;
            }
            set
            {
                this._CustomerID = value;
            }
        }
        private string _CustomerEnglishName;
        /// <summary>
        /// CustomerEnglishName
        /// </summary>
        [AttributeRfPage("txtCustomerEnglishName", "CustLabel", false)]
        public string CustomerEnglishName
        {
            get
            {
                return this._CustomerEnglishName;
            }
            set
            {
                this._CustomerEnglishName = value;
            }
        }
        private string _CustomerChineseName;
        /// <summary>
        /// CustomerChineseName
        /// </summary>
        [AttributeRfPage("txtCustomerChineseName", "CustLabel", false)]
        public string CustomerChineseName
        {
            get
            {
                return this._CustomerChineseName;
            }
            set
            {
                this._CustomerChineseName = value;
            }
        }
        private string _AMLSegment;
        /// <summary>
        /// AMLSegment
        /// </summary>
        [AttributeRfPage("txtAMLSegment", "CustLabel", false)]
        public string AMLSegment
        {
            get
            {
                return this._AMLSegment;
            }
            set
            {
                this._AMLSegment = value;
            }
        }
        private string _OriginalRiskRanking;
        /// <summary>
        /// OriginalRiskRanking
        /// </summary>
        [AttributeRfPage("txtOriginalRiskRanking", "CustLabel", false)]
        public string OriginalRiskRanking
        {
            get
            {
                return this._OriginalRiskRanking;
            }
            set
            {
                this._OriginalRiskRanking = value;
            }
        }
        private string _OriginalNextReviewDate;
        /// <summary>
        /// OriginalNextReviewDate
        /// </summary>
        [AttributeRfPage("txtOriginalNextReviewDate", "CustLabel", false)]
        public string OriginalNextReviewDate
        {
            get
            {
                return this._OriginalNextReviewDate;
            }
            set
            {
                this._OriginalNextReviewDate = value;
            }
        }
        private string _NewRiskRanking;
        /// <summary>
        /// NewRiskRanking
        /// </summary>
        [AttributeRfPage("txtNewRiskRanking", "CustLabel", false)]
        public string NewRiskRanking
        {
            get
            {
                return this._NewRiskRanking;
            }
            set
            {
                this._NewRiskRanking = value;
            }
        }
        private string _NewNextReviewDate;
        /// <summary>
        /// NewNextReviewDate
        /// </summary>
        [AttributeRfPage("txtNewNextReviewDate", "CustLabel", false)]
        public string NewNextReviewDate
        {
            get
            {
                return this._NewNextReviewDate;
            }
            set
            {
                this._NewNextReviewDate = value;
            }
        }
        private string _LastUpdateMaker;
        /// <summary>
        /// LastUpdateMaker
        /// </summary>
        [AttributeRfPage("txtLastUpdateMaker", "CustLabel", false)]
        public string LastUpdateMaker
        {
            get
            {
                return this._LastUpdateMaker;
            }
            set
            {
                this._LastUpdateMaker = value;
            }
        }
        private string _LastUpdateBranch;
        /// <summary>
        /// LastUpdateBranch
        /// </summary>
        [AttributeRfPage("txtLastUpdateBranch", "CustLabel", false)]
        public string LastUpdateBranch
        {
            get
            {
                return this._LastUpdateBranch;
            }
            set
            {
                this._LastUpdateBranch = value;
            }
        }
        private string _LastUpdateDate;
        /// <summary>
        /// LastUpdateDate
        /// </summary>
        [AttributeRfPage("txtLastUpdateDate", "CustLabel", false)]
        public string LastUpdateDate
        {
            get
            {
                return this._LastUpdateDate;
            }
            set
            {
                this._LastUpdateDate = value;
            }
        }
        private string _HomeBranch;
        /// <summary>
        /// HomeBranch
        /// </summary>
        [AttributeRfPage("txtHomeBranch", "CustLabel", false)]
        public string HomeBranch
        {
            get
            {
                return this._HomeBranch;
            }
            set
            {
                this._HomeBranch = value;
            }
        }
        private string _CaseType;
        /// <summary>
        /// CaseType
        /// </summary>
        [AttributeRfPage("txtCaseType", "CustLabel", false)]
        public string CaseType
        {
            get
            {
                return this._CaseType;
            }
            set
            {
                this._CaseType = value;
            }
        }
        private string _FiledSAR;
        /// <summary>
        /// FiledSAR
        /// </summary>
        [AttributeRfPage("txtFiledSAR", "CustLabel", false)]
        public string FiledSAR
        {
            get
            {
                return this._FiledSAR;
            }
            set
            {
                this._FiledSAR = value;
            }
        }
        private string _Filler;
        /// <summary>
        /// Filler
        /// </summary>
        [AttributeRfPage("txtFiller", "CustLabel", false)]
        public string Filler
        {
            get
            {
                return this._Filler;
            }
            set
            {
                this._Filler = value;
            }
        }
        private string _Create_Time;
        /// <summary>
        /// Create_Time
        /// </summary>
        [AttributeRfPage("txtCreate_Time", "CustLabel", false)]
        public string Create_Time
        {
            get
            {
                return this._Create_Time;
            }
            set
            {
                this._Create_Time = value;
            }
        }
        private string _Create_User;
        /// <summary>
        /// Create_User
        /// </summary>
        [AttributeRfPage("txtCreate_User", "CustLabel", false)]
        public string Create_User
        {
            get
            {
                return this._Create_User;
            }
            set
            {
                this._Create_User = value;
            }
        }
        private string _Create_Date;
        /// <summary>
        /// Create_Date
        /// </summary>
        [AttributeRfPage("txtCreate_Date", "CustLabel", false)]
        public string Create_Date
        {
            get
            {
                return this._Create_Date;
            }
            set
            {
                this._Create_Date = value;
            }
        }

        /// <summary>
        /// 轉換型別
        /// </summary>
        /// <returns></returns>
        public EntityAML_Edata_Work_edit toEditMode()
        {
            EntityAML_Edata_Work_edit returnObj = new EntityAML_Edata_Work_edit();
            DataTableConvertor.Clone2Other<EntityAML_Edata_Work, EntityAML_Edata_Work_edit>(this, ref returnObj);
            return returnObj;
        }
    }
}