//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.Data.OM;
using Framework.Data.OM.OMAttribute;
using System;


namespace CSIPNewInvoice.EntityLayer_new
{

    /// <summary>
    /// AML_FinalDataLog
    /// </summary>
    [Serializable()]
    [AttributeTable("AML_HeadOffice_Log")]
    public class EntityAML_HeadOffice_Log : Entity, IMutiLineClass
    {
        private string _ID = "";
        /// <summary>
        /// ID
        /// </summary>
        [AttributeRfPage("hidID_", "CustHiddenField", false)]
        public string ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this._ID = value;
            }
        }

        private string _keyin_day;
        /// <summary>
        /// keyin_day
        /// </summary>
        [AttributeRfPage("txtkeyin_day", "CustTextBox", false)]
        public string keyin_day
        {
            get
            {
                return this._keyin_day;
            }
            set
            {
                this._keyin_day = value;
            }
        }
        private string _BasicTaxID;
        /// <summary>
        /// BasicTaxID
        /// </summary>
        //[AttributeRfPage("txtBasicTaxID", "CustTextBox", false)]
        [AttributeRfPage("txtBasicTaxID", "CustTextBox", false, "", "CORP_NO")]
        public string BasicTaxID
        {
            get
            {
                return this._BasicTaxID;
            }
            set
            {
                this._BasicTaxID = value;
            }
        }
        private string _BasicRegistyNameEN;
        /// <summary>
        /// BasicRegistyNameEN
        /// </summary>
        //[AttributeRfPage("txtBasicRegistyNameEN", "CustTextBox", false, "", "CORP_REG_ENG_NAME")]
        [AttributeRfPage("txtBasicRegistyNameEN", "CustTextBox", false)]
        [AttributeValidPage(false, "", true, 120, "公司英文名稱")]
        public string BasicRegistyNameEN
        {
            get
            {
                return this._BasicRegistyNameEN;
            }
            set
            {
                this._BasicRegistyNameEN = value;
            }
        }
        private string _BasicRegistyNameCH;
        /// <summary>
        /// BasicRegistyNameCH
        /// </summary>
        //[AttributeRfPage("txtBasicRegistyNameCH", "CustTextBox", false)]
        [AttributeRfPage("txtBasicRegistyNameCH", "CustTextBox", false, "", "REG_NAME", 60, '　', false)]
        [AttributeValidPage(true, "公司名稱", true, 60, "公司名稱")]
        public string BasicRegistyNameCH
        {
            get
            {
                return this._BasicRegistyNameCH;
            }
            set
            {
                this._BasicRegistyNameCH = value;
            }
        }
        private string _userID_1key;
        /// <summary>
        /// userID_1key
        /// </summary>
        [AttributeRfPage("txtuserID_1key", "CustTextBox", false)]
        public string userID_1key
        {
            get
            {
                return this._userID_1key;
            }
            set
            {
                this._userID_1key = value;
            }
        }
        private string _userID_2key;
        /// <summary>
        /// userID_2key
        /// </summary>
        [AttributeRfPage("txtuserID_2key", "CustTextBox", false)]
        public string userID_2key
        {
            get
            {
                return this._userID_2key;
            }
            set
            {
                this._userID_2key = value;
            }
        }


        public bool isMutilime
        {
            get { return true; }
        }

        public string InterFaceLineID
        {
            get { return _LineID; }
        }
        private string _LineID = "";
        /// <summary>
        /// ID
        /// </summary>
        [AttributeRfPage("txtID", "CustTextBox", false)]
        public string LineID
        {
            get
            {
                return this._LineID;
            }
            set
            {
                this._LineID = value;
            }
        }       

    }
}
