//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.3603
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPKeyInGUI.EntityLayer
{
    
    
    /// <summary>
    /// shop_6063
    /// </summary>
    [Serializable()]
    [AttributeTable("shop_6063")]
    public class EntitySHOP_6063 : Entity
    {
        
        private string _shop_no;
        
        /// <summary>
        /// shop_no
        /// </summary>
        public static string M_shop_no = "shop_no";
        
        private string _card_type;
        
        /// <summary>
        /// card_type
        /// </summary>
        public static string M_card_type = "card_type";
        
        private string _identify_no;
        
        /// <summary>
        /// identify_no
        /// </summary>
        public static string M_identify_no = "identify_no";
        
        private string _favour_fee;
        
        /// <summary>
        /// favour_fee
        /// </summary>
        public static string M_favour_fee = "favour_fee";
        
        private string _batch_depict;
        
        /// <summary>
        /// batch_depict
        /// </summary>
        public static string M_batch_depict = "batch_depict";
        
        private string _keyin_day;
        
        /// <summary>
        /// keyin_day
        /// </summary>
        public static string M_keyin_day = "keyin_day";
        
        private string _first_user;
        
        /// <summary>
        /// first_user
        /// </summary>
        public static string M_first_user = "first_user";
        
        private string _second_user;
        
        /// <summary>
        /// second_user
        /// </summary>
        public static string M_second_user = "second_user";
        
        private string _send3270;
        
        /// <summary>
        /// send3270
        /// </summary>
        public static string M_send3270 = "send3270";
        
        private string _keyin_flag;
        
        /// <summary>
        /// keyin_flag
        /// </summary>
        public static string M_keyin_flag = "keyin_flag";
        
        private string _keyin_userID;
        
        /// <summary>
        /// keyin_userID
        /// </summary>
        public static string M_keyin_userID = "keyin_userID";
        
        /// <summary>
        /// shop_no
        /// </summary>
        [AttributeField("shop_no", "System.String", false, true, false, "String")]
        public string shop_no
        {
            get
            {
                return this._shop_no;
            }
            set
            {
                this._shop_no = value;
            }
        }
        
        /// <summary>
        /// card_type
        /// </summary>
        [AttributeField("card_type", "System.String", false, true, false, "String")]
        public string card_type
        {
            get
            {
                return this._card_type;
            }
            set
            {
                this._card_type = value;
            }
        }
        
        /// <summary>
        /// identify_no
        /// </summary>
        [AttributeField("identify_no", "System.String", false, true, false, "String")]
        public string identify_no
        {
            get
            {
                return this._identify_no;
            }
            set
            {
                this._identify_no = value;
            }
        }
        
        /// <summary>
        /// favour_fee
        /// </summary>
        [AttributeField("favour_fee", "System.String", false, false, false, "String")]
        public string favour_fee
        {
            get
            {
                return this._favour_fee;
            }
            set
            {
                this._favour_fee = value;
            }
        }
        
        /// <summary>
        /// batch_depict
        /// </summary>
        [AttributeField("batch_depict", "System.String", false, false, false, "String")]
        public string batch_depict
        {
            get
            {
                return this._batch_depict;
            }
            set
            {
                this._batch_depict = value;
            }
        }
        
        /// <summary>
        /// keyin_day
        /// </summary>
        [AttributeField("keyin_day", "System.String", false, false, false, "String")]
        public string keyin_day
        {
            get
            {
                return this._keyin_day;
            }
            set
            {
                this._keyin_day = value;
            }
        }
        
        /// <summary>
        /// first_user
        /// </summary>
        [AttributeField("first_user", "System.String", false, false, false, "String")]
        public string first_user
        {
            get
            {
                return this._first_user;
            }
            set
            {
                this._first_user = value;
            }
        }
        
        /// <summary>
        /// second_user
        /// </summary>
        [AttributeField("second_user", "System.String", false, false, false, "String")]
        public string second_user
        {
            get
            {
                return this._second_user;
            }
            set
            {
                this._second_user = value;
            }
        }
        
        /// <summary>
        /// send3270
        /// </summary>
        [AttributeField("send3270", "System.String", false, false, false, "String")]
        public string send3270
        {
            get
            {
                return this._send3270;
            }
            set
            {
                this._send3270 = value;
            }
        }
        
        /// <summary>
        /// keyin_flag
        /// </summary>
        [AttributeField("keyin_flag", "System.String", false, true, false, "String")]
        public string keyin_flag
        {
            get
            {
                return this._keyin_flag;
            }
            set
            {
                this._keyin_flag = value;
            }
        }
        
        /// <summary>
        /// keyin_userID
        /// </summary>
        [AttributeField("keyin_userID", "System.String", false, false, false, "String")]
        public string keyin_userID
        {
            get
            {
                return this._keyin_userID;
            }
            set
            {
                this._keyin_userID = value;
            }
        }
    }
    
    /// <summary>
    /// shop_6063
    /// </summary>
    [Serializable()]
    public class EntitySHOP_6063Set : EntitySet<EntitySHOP_6063>
    {
    }
}
