//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.3603
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPKeyInGUI.EntityLayer
{
    
    
    /// <summary>
    /// RedeemUpload
    /// </summary>
    [Serializable()]
    [AttributeTable("RedeemUpload")]
    public class EntityRedeemUpload : Entity
    {
        
        private string _RECEIVE_NUMBER;
        
        /// <summary>
        /// RECEIVE_NUMBER
        /// </summary>
        public static string M_RECEIVE_NUMBER = "RECEIVE_NUMBER";
        
        private string _USER_ID;
        
        /// <summary>
        /// USER_ID
        /// </summary>
        public static string M_USER_ID = "USER_ID";
        
        private string _DATA_TYPE;
        
        /// <summary>
        /// DATA_TYPE
        /// </summary>
        public static string M_DATA_TYPE = "DATA_TYPE";
        
        private string _UPLOAD_DATA;
        
        /// <summary>
        /// UPLOAD_DATA
        /// </summary>
        public static string M_UPLOAD_DATA = "UPLOAD_DATA";
        
        private int _LINE_INDEX;
        
        /// <summary>
        /// LINE_INDEX
        /// </summary>
        public static string M_LINE_INDEX = "LINE_INDEX";
        
        private string _KEYIN_DATE;
        
        /// <summary>
        /// KEYIN_DATE
        /// </summary>
        public static string M_KEYIN_DATE = "KEYIN_DATE";
        
        private string _UPDATE_DATE;
        
        /// <summary>
        /// UPDATE_DATE
        /// </summary>
        public static string M_UPDATE_DATE = "UPDATE_DATE";
        
        private string _KEYIN_FLAG;
        
        /// <summary>
        /// KEYIN_FLAG
        /// </summary>
        public static string M_KEYIN_FLAG = "KEYIN_FLAG";
        
        private string _SEND3270;
        
        /// <summary>
        /// SEND3270
        /// </summary>
        public static string M_SEND3270 = "SEND3270";
        
        private int _USE_TIME;
        
        /// <summary>
        /// USE_TIME
        /// </summary>
        public static string M_USE_TIME = "USE_TIME";
        
        private string _ISSAME;
        
        /// <summary>
        /// ISSAME
        /// </summary>
        public static string M_ISSAME = "ISSAME";
        
        private int _DIFF_NUM;
        
        /// <summary>
        /// DIFF_NUM
        /// </summary>
        public static string M_DIFF_NUM = "DIFF_NUM";
        
        private string _EDIT_USER_ID;
        
        /// <summary>
        /// EDIT_USER_ID
        /// </summary>
        public static string M_EDIT_USER_ID = "EDIT_USER_ID";
        
        /// <summary>
        /// RECEIVE_NUMBER
        /// </summary>
        [AttributeField("RECEIVE_NUMBER", "System.String", false, false, false, "String")]
        public string RECEIVE_NUMBER
        {
            get
            {
                return this._RECEIVE_NUMBER;
            }
            set
            {
                this._RECEIVE_NUMBER = value;
            }
        }
        
        /// <summary>
        /// USER_ID
        /// </summary>
        [AttributeField("USER_ID", "System.String", false, false, false, "String")]
        public string USER_ID
        {
            get
            {
                return this._USER_ID;
            }
            set
            {
                this._USER_ID = value;
            }
        }
        
        /// <summary>
        /// DATA_TYPE
        /// </summary>
        [AttributeField("DATA_TYPE", "System.String", false, false, false, "String")]
        public string DATA_TYPE
        {
            get
            {
                return this._DATA_TYPE;
            }
            set
            {
                this._DATA_TYPE = value;
            }
        }
        
        /// <summary>
        /// UPLOAD_DATA
        /// </summary>
        [AttributeField("UPLOAD_DATA", "System.String", false, false, false, "String")]
        public string UPLOAD_DATA
        {
            get
            {
                return this._UPLOAD_DATA;
            }
            set
            {
                this._UPLOAD_DATA = value;
            }
        }
        
        /// <summary>
        /// LINE_INDEX
        /// </summary>
        [AttributeField("LINE_INDEX", "System.Int32", false, false, false, "Int32")]
        public int LINE_INDEX
        {
            get
            {
                return this._LINE_INDEX;
            }
            set
            {
                this._LINE_INDEX = value;
            }
        }
        
        /// <summary>
        /// KEYIN_DATE
        /// </summary>
        [AttributeField("KEYIN_DATE", "System.String", false, false, false, "String")]
        public string KEYIN_DATE
        {
            get
            {
                return this._KEYIN_DATE;
            }
            set
            {
                this._KEYIN_DATE = value;
            }
        }
        
        /// <summary>
        /// UPDATE_DATE
        /// </summary>
        [AttributeField("UPDATE_DATE", "System.String", false, false, false, "String")]
        public string UPDATE_DATE
        {
            get
            {
                return this._UPDATE_DATE;
            }
            set
            {
                this._UPDATE_DATE = value;
            }
        }
        
        /// <summary>
        /// KEYIN_FLAG
        /// </summary>
        [AttributeField("KEYIN_FLAG", "System.String", false, false, false, "String")]
        public string KEYIN_FLAG
        {
            get
            {
                return this._KEYIN_FLAG;
            }
            set
            {
                this._KEYIN_FLAG = value;
            }
        }
        
        /// <summary>
        /// SEND3270
        /// </summary>
        [AttributeField("SEND3270", "System.String", false, false, false, "String")]
        public string SEND3270
        {
            get
            {
                return this._SEND3270;
            }
            set
            {
                this._SEND3270 = value;
            }
        }
        
        /// <summary>
        /// USE_TIME
        /// </summary>
        [AttributeField("USE_TIME", "System.Int32", false, false, false, "Int32")]
        public int USE_TIME
        {
            get
            {
                return this._USE_TIME;
            }
            set
            {
                this._USE_TIME = value;
            }
        }
        
        /// <summary>
        /// ISSAME
        /// </summary>
        [AttributeField("ISSAME", "System.String", false, false, false, "String")]
        public string ISSAME
        {
            get
            {
                return this._ISSAME;
            }
            set
            {
                this._ISSAME = value;
            }
        }
        
        /// <summary>
        /// DIFF_NUM
        /// </summary>
        [AttributeField("DIFF_NUM", "System.Int32", false, false, false, "Int32")]
        public int DIFF_NUM
        {
            get
            {
                return this._DIFF_NUM;
            }
            set
            {
                this._DIFF_NUM = value;
            }
        }
        
        /// <summary>
        /// EDIT_USER_ID
        /// </summary>
        [AttributeField("EDIT_USER_ID", "System.String", false, false, false, "String")]
        public string EDIT_USER_ID
        {
            get
            {
                return this._EDIT_USER_ID;
            }
            set
            {
                this._EDIT_USER_ID = value;
            }
        }
    }
    
    /// <summary>
    /// RedeemUpload
    /// </summary>
    [Serializable()]
    public class EntityRedeemUploadSet : EntitySet<EntityRedeemUpload>
    {
    }
}
