//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPKeyInGUI.EntityLayer
{
    
    
    /// <summary>
    /// customer_log
    /// </summary>
    [Serializable()]
    [AttributeTable("customer_log")]
    public class EntityCUSTOMER_LOG : Entity
    {
        
        private string _query_key;
        
        /// <summary>
        /// query_key
        /// </summary>
        public static string M_query_key = "query_key";
        
        private string _trans_id;
        
        /// <summary>
        /// trans_id
        /// </summary>
        public static string M_trans_id = "trans_id";
        
        private string _field_name;
        
        /// <summary>
        /// field_name
        /// </summary>
        public static string M_field_name = "field_name";
        
        private string _before;
        
        /// <summary>
        /// before
        /// </summary>
        public static string M_before = "before";
        
        private string _after;
        
        /// <summary>
        /// after
        /// </summary>
        public static string M_after = "after";
        
        private string _user_id;
        
        /// <summary>
        /// user_id
        /// </summary>
        public static string M_user_id = "user_id";

        private string _mod_date;
        
        /// <summary>
        /// mod_date
        /// </summary>
        public static string M_mod_date = "mod_date";

        private string _mod_time;
        
        /// <summary>
        /// mod_time
        /// </summary>
        public static string M_mod_time = "mod_time";
        
        private string _log_flag;
        
        /// <summary>
        /// log_flag
        /// </summary>
        public static string M_log_flag = "log_flag";
        
        private string _Receive_Number;
        
        /// <summary>
        /// Receive_Number
        /// </summary>
        public static string M_Receive_Number = "Receive_Number";
        
        /// <summary>
        /// query_key
        /// </summary>
        [AttributeField("query_key", "System.String", false, false, false, "String")]
        public string query_key
        {
            get
            {
                return this._query_key;
            }
            set
            {
                this._query_key = value;
            }
        }
        
        /// <summary>
        /// trans_id
        /// </summary>
        [AttributeField("trans_id", "System.String", false, false, false, "String")]
        public string trans_id
        {
            get
            {
                return this._trans_id;
            }
            set
            {
                this._trans_id = value;
            }
        }
        
        /// <summary>
        /// field_name
        /// </summary>
        [AttributeField("field_name", "System.String", false, false, false, "String")]
        public string field_name
        {
            get
            {
                return this._field_name;
            }
            set
            {
                this._field_name = value;
            }
        }
        
        /// <summary>
        /// before
        /// </summary>
        [AttributeField("before", "System.String", false, false, false, "String")]
        public string before
        {
            get
            {
                return this._before;
            }
            set
            {
                this._before = value;
            }
        }
        
        /// <summary>
        /// after
        /// </summary>
        [AttributeField("after", "System.String", false, false, false, "String")]
        public string after
        {
            get
            {
                return this._after;
            }
            set
            {
                this._after = value;
            }
        }
        
        /// <summary>
        /// user_id
        /// </summary>
        [AttributeField("user_id", "System.String", false, false, false, "String")]
        public string user_id
        {
            get
            {
                return this._user_id;
            }
            set
            {
                this._user_id = value;
            }
        }
        
        /// <summary>
        /// mod_date
        /// </summary>
        [AttributeField("mod_date", "System.String", false, false, false, "String")]
        public string mod_date
        {
            get
            {
                return this._mod_date;
            }
            set
            {
                this._mod_date = value;
            }
        }
        
        /// <summary>
        /// mod_time
        /// </summary>
        [AttributeField("mod_time", "System.String", false, false, false, "String")]
        public string mod_time
        {
            get
            {
                return this._mod_time;
            }
            set
            {
                this._mod_time = value;
            }
        }
        
        /// <summary>
        /// log_flag
        /// </summary>
        [AttributeField("log_flag", "System.String", false, false, false, "String")]
        public string log_flag
        {
            get
            {
                return this._log_flag;
            }
            set
            {
                this._log_flag = value;
            }
        }
        
        /// <summary>
        /// Receive_Number
        /// </summary>
        [AttributeField("Receive_Number", "System.String", false, false, false, "String")]
        public string Receive_Number
        {
            get
            {
                return this._Receive_Number;
            }
            set
            {
                this._Receive_Number = value;
            }
        }
    }
    
    /// <summary>
    /// customer_log
    /// </summary>
    [Serializable()]
    public class EntityCUSTOMER_LOGSet : EntitySet<EntityCUSTOMER_LOG>
    {
    }
}
