//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.3603
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPKeyInGUI.EntityLayer
{


    /// <summary>
    /// AwardSet3270
    /// </summary>
    [Serializable()]
    [AttributeTable("AwardSet3270")]
    public class EntityAwardSet3270 : Entity
    {

        private int _ID;

        /// <summary>
        /// ID
        /// </summary>
        public static string M_ID = "ID";

        private string _RECEIVE_NUMBER;

        /// <summary>
        /// RECEIVE_NUMBER
        /// </summary>
        public static string M_RECEIVE_NUMBER = "RECEIVE_NUMBER";

        private string _USER_ID;

        /// <summary>
        /// USER_ID
        /// </summary>
        public static string M_USER_ID = "USER_ID";

        private string _FUNCTION_CODE;

        /// <summary>
        /// FUNCTION_CODE
        /// </summary>
        public static string M_FUNCTION_CODE = "FUNCTION_CODE";

        private string _MSG_SEQ;

        /// <summary>
        /// MSG_SEQ
        /// </summary>
        public static string M_MSG_SEQ = "MSG_SEQ";

        private string _MSG_TYPE;

        /// <summary>
        /// MSG_TYPE
        /// </summary>
        public static string M_MSG_TYPE = "MSG_TYPE";

        private string _ORG;

        /// <summary>
        /// ORG
        /// </summary>
        public static string M_ORG = "ORG";

        private string _PROG_ID;

        /// <summary>
        /// PROG_ID
        /// </summary>
        public static string M_PROG_ID = "PROG_ID";

        private string _PARTNER_ID;

        /// <summary>
        /// PARTNER_ID
        /// </summary>
        public static string M_PARTNER_ID = "PARTNER_ID";

        private string _ACCUMULATION_TYPE;

        /// <summary>
        /// ACCUMULATION_TYPE
        /// </summary>
        public static string M_ACCUMULATION_TYPE = "ACCUMULATION_TYPE";

        private string _COUNTRY_CODE_IND;

        /// <summary>
        /// COUNTRY_CODE_IND
        /// </summary>
        public static string M_COUNTRY_CODE_IND = "COUNTRY_CODE_IND";

        private string _BASIC_CALC_MTHD;

        /// <summary>
        /// BASIC_CALC_MTHD
        /// </summary>
        public static string M_BASIC_CALC_MTHD = "BASIC_CALC_MTHD";

        private string _BASIC_CALC_IND;

        /// <summary>
        /// BASIC_CALC_IND
        /// </summary>
        public static string M_BASIC_CALC_IND = "BASIC_CALC_IND";

        private string _SUPP_BASIC_CAL_MTHD;

        /// <summary>
        /// SUPP_BASIC_CAL_MTHD
        /// </summary>
        public static string M_SUPP_BASIC_CAL_MTHD = "SUPP_BASIC_CAL_MTHD";

        private string _SUPP_BASIC_CAL_IND;

        /// <summary>
        /// SUPP_BASIC_CAL_IND
        /// </summary>
        public static string M_SUPP_BASIC_CAL_IND = "SUPP_BASIC_CAL_IND";

        private string _PROMO_START_DTE;

        /// <summary>
        /// PROMO_START_DTE
        /// </summary>
        public static string M_PROMO_START_DTE = "PROMO_START_DTE";

        private string _PROMO_END_DTE;

        /// <summary>
        /// PROMO_END_DTE
        /// </summary>
        public static string M_PROMO_END_DTE = "PROMO_END_DTE";

        private string _PROMO_CALC_MTHD;

        /// <summary>
        /// PROMO_CALC_MTHD
        /// </summary>
        public static string M_PROMO_CALC_MTHD = "PROMO_CALC_MTHD";

        private string _PROMO_CALC_IND;

        /// <summary>
        /// PROMO_CALC_IND
        /// </summary>
        public static string M_PROMO_CALC_IND = "PROMO_CALC_IND";

        private string _BTHDTE_FLAG;

        /// <summary>
        /// BTHDTE_FLAG
        /// </summary>
        public static string M_BTHDTE_FLAG = "BTHDTE_FLAG";

        private string _BTHDTE_START;

        /// <summary>
        /// BTHDTE_START
        /// </summary>
        public static string M_BTHDTE_START = "BTHDTE_START";

        private string _BTHDTE_END;

        /// <summary>
        /// BTHDTE_END
        /// </summary>
        public static string M_BTHDTE_END = "BTHDTE_END";

        private string _BTHDTE_CALC_MTHD;

        /// <summary>
        /// BTHDTE_CALC_MTHD
        /// </summary>
        public static string M_BTHDTE_CALC_MTHD = "BTHDTE_CALC_MTHD";

        private string _BTHDTE_CALC_IND;

        /// <summary>
        /// BTHDTE_CALC_IND
        /// </summary>
        public static string M_BTHDTE_CALC_IND = "BTHDTE_CALC_IND";

        private string _M_SIGNON_NAME;

        /// <summary>
        /// M_SIGNON_NAME
        /// </summary>
        public static string M_M_SIGNON_NAME = "M_SIGNON_NAME";

        private string _TC_CODE1;

        /// <summary>
        /// TC_CODE1
        /// </summary>
        public static string M_TC_CODE1 = "TC_CODE1";

        private string _TC_OP1;

        /// <summary>
        /// TC_OP1
        /// </summary>
        public static string M_TC_OP1 = "TC_OP1";

        private string _TC_CODE2;

        /// <summary>
        /// TC_CODE2
        /// </summary>
        public static string M_TC_CODE2 = "TC_CODE2";

        private string _TC_OP2;

        /// <summary>
        /// TC_OP2
        /// </summary>
        public static string M_TC_OP2 = "TC_OP2";

        private string _TC_CODE3;

        /// <summary>
        /// TC_CODE3
        /// </summary>
        public static string M_TC_CODE3 = "TC_CODE3";

        private string _TC_OP3;

        /// <summary>
        /// TC_OP3
        /// </summary>
        public static string M_TC_OP3 = "TC_OP3";

        private string _TC_CODE4;

        /// <summary>
        /// TC_CODE4
        /// </summary>
        public static string M_TC_CODE4 = "TC_CODE4";

        private string _TC_OP4;

        /// <summary>
        /// TC_OP4
        /// </summary>
        public static string M_TC_OP4 = "TC_OP4";

        private string _TC_CODE5;

        /// <summary>
        /// TC_CODE5
        /// </summary>
        public static string M_TC_CODE5 = "TC_CODE5";

        private string _TC_OP5;

        /// <summary>
        /// TC_OP5
        /// </summary>
        public static string M_TC_OP5 = "TC_OP5";

        private string _TC_CODE6;

        /// <summary>
        /// TC_CODE6
        /// </summary>
        public static string M_TC_CODE6 = "TC_CODE6";

        private string _TC_OP6;

        /// <summary>
        /// TC_OP6
        /// </summary>
        public static string M_TC_OP6 = "TC_OP6";

        private string _TC_CODE7;

        /// <summary>
        /// TC_CODE7
        /// </summary>
        public static string M_TC_CODE7 = "TC_CODE7";

        private string _TC_OP7;

        /// <summary>
        /// TC_OP7
        /// </summary>
        public static string M_TC_OP7 = "TC_OP7";

        private string _TC_CODE8;

        /// <summary>
        /// TC_CODE8
        /// </summary>
        public static string M_TC_CODE8 = "TC_CODE8";

        private string _TC_OP8;

        /// <summary>
        /// TC_OP8
        /// </summary>
        public static string M_TC_OP8 = "TC_OP8";

        private string _TC_CODE9;

        /// <summary>
        /// TC_CODE9
        /// </summary>
        public static string M_TC_CODE9 = "TC_CODE9";

        private string _TC_OP9;

        /// <summary>
        /// TC_OP9
        /// </summary>
        public static string M_TC_OP9 = "TC_OP9";

        private string _TC_CODE10;

        /// <summary>
        /// TC_CODE10
        /// </summary>
        public static string M_TC_CODE10 = "TC_CODE10";

        private string _TC_OP10;

        /// <summary>
        /// TC_OP10
        /// </summary>
        public static string M_TC_OP10 = "TC_OP10";

        private string _MCC_FROM1;

        /// <summary>
        /// MCC_FROM1
        /// </summary>
        public static string M_MCC_FROM1 = "MCC_FROM1";

        private string _MCC_TO1;

        /// <summary>
        /// MCC_TO1
        /// </summary>
        public static string M_MCC_TO1 = "MCC_TO1";

        private string _COUNTRY_CODE1;

        /// <summary>
        /// COUNTRY_CODE1
        /// </summary>
        public static string M_COUNTRY_CODE1 = "COUNTRY_CODE1";

        private string _MCC_FROM2;

        /// <summary>
        /// MCC_FROM2
        /// </summary>
        public static string M_MCC_FROM2 = "MCC_FROM2";

        private string _MCC_TO2;

        /// <summary>
        /// MCC_TO2
        /// </summary>
        public static string M_MCC_TO2 = "MCC_TO2";

        private string _COUNTRY_CODE2;

        /// <summary>
        /// COUNTRY_CODE2
        /// </summary>
        public static string M_COUNTRY_CODE2 = "COUNTRY_CODE2";

        private string _MCC_FROM3;

        /// <summary>
        /// MCC_FROM3
        /// </summary>
        public static string M_MCC_FROM3 = "MCC_FROM3";

        private string _MCC_TO3;

        /// <summary>
        /// MCC_TO3
        /// </summary>
        public static string M_MCC_TO3 = "MCC_TO3";

        private string _COUNTRY_CODE3;

        /// <summary>
        /// COUNTRY_CODE3
        /// </summary>
        public static string M_COUNTRY_CODE3 = "COUNTRY_CODE3";

        private string _MCC_FROM4;

        /// <summary>
        /// MCC_FROM4
        /// </summary>
        public static string M_MCC_FROM4 = "MCC_FROM4";

        private string _MCC_TO4;

        /// <summary>
        /// MCC_TO4
        /// </summary>
        public static string M_MCC_TO4 = "MCC_TO4";

        private string _COUNTRY_CODE4;

        /// <summary>
        /// COUNTRY_CODE4
        /// </summary>
        public static string M_COUNTRY_CODE4 = "COUNTRY_CODE4";

        private string _MCC_FROM5;

        /// <summary>
        /// MCC_FROM5
        /// </summary>
        public static string M_MCC_FROM5 = "MCC_FROM5";

        private string _MCC_TO5;

        /// <summary>
        /// MCC_TO5
        /// </summary>
        public static string M_MCC_TO5 = "MCC_TO5";

        private string _COUNTRY_CODE5;

        /// <summary>
        /// COUNTRY_CODE5
        /// </summary>
        public static string M_COUNTRY_CODE5 = "COUNTRY_CODE5";

        private string _MCC_FROM6;

        /// <summary>
        /// MCC_FROM6
        /// </summary>
        public static string M_MCC_FROM6 = "MCC_FROM6";

        private string _MCC_TO6;

        /// <summary>
        /// MCC_TO6
        /// </summary>
        public static string M_MCC_TO6 = "MCC_TO6";

        private string _COUNTRY_CODE6;

        /// <summary>
        /// COUNTRY_CODE6
        /// </summary>
        public static string M_COUNTRY_CODE6 = "COUNTRY_CODE6";

        private string _MCC_FROM7;

        /// <summary>
        /// MCC_FROM7
        /// </summary>
        public static string M_MCC_FROM7 = "MCC_FROM7";

        private string _MCC_TO7;

        /// <summary>
        /// MCC_TO7
        /// </summary>
        public static string M_MCC_TO7 = "MCC_TO7";

        private string _COUNTRY_CODE7;

        /// <summary>
        /// COUNTRY_CODE7
        /// </summary>
        public static string M_COUNTRY_CODE7 = "COUNTRY_CODE7";

        private string _MCC_FROM8;

        /// <summary>
        /// MCC_FROM8
        /// </summary>
        public static string M_MCC_FROM8 = "MCC_FROM8";

        private string _MCC_TO8;

        /// <summary>
        /// MCC_TO8
        /// </summary>
        public static string M_MCC_TO8 = "MCC_TO8";

        private string _COUNTRY_CODE8;

        /// <summary>
        /// COUNTRY_CODE8
        /// </summary>
        public static string M_COUNTRY_CODE8 = "COUNTRY_CODE8";

        private string _MCC_FROM9;

        /// <summary>
        /// MCC_FROM9
        /// </summary>
        public static string M_MCC_FROM9 = "MCC_FROM9";

        private string _MCC_TO9;

        /// <summary>
        /// MCC_TO9
        /// </summary>
        public static string M_MCC_TO9 = "MCC_TO9";

        private string _COUNTRY_CODE9;

        /// <summary>
        /// COUNTRY_CODE9
        /// </summary>
        public static string M_COUNTRY_CODE9 = "COUNTRY_CODE9";

        private string _MCC_FROM10;

        /// <summary>
        /// MCC_FROM10
        /// </summary>
        public static string M_MCC_FROM10 = "MCC_FROM10";

        private string _MCC_TO10;

        /// <summary>
        /// MCC_TO10
        /// </summary>
        public static string M_MCC_TO10 = "MCC_TO10";

        private string _COUNTRY_CODE10;

        /// <summary>
        /// COUNTRY_CODE10
        /// </summary>
        public static string M_COUNTRY_CODE10 = "COUNTRY_CODE10";

        private string _BASIC_TIER_AMT1;

        /// <summary>
        /// BASIC_TIER_AMT1
        /// </summary>
        public static string M_BASIC_TIER_AMT1 = "BASIC_TIER_AMT1";

        private string _BASIC_TIER_RATE1;

        /// <summary>
        /// BASIC_TIER_RATE1
        /// </summary>
        public static string M_BASIC_TIER_RATE1 = "BASIC_TIER_RATE1";

        private string _SUPP_BASIC_TIER_AMT1;

        /// <summary>
        /// SUPP_BASIC_TIER_AMT1
        /// </summary>
        public static string M_SUPP_BASIC_TIER_AMT1 = "SUPP_BASIC_TIER_AMT1";

        private string _SUPP_BASIC_TIER_RATE1;

        /// <summary>
        /// SUPP_BASIC_TIER_RATE1
        /// </summary>
        public static string M_SUPP_BASIC_TIER_RATE1 = "SUPP_BASIC_TIER_RATE1";

        private string _PROMO_TIER_AMT1;

        /// <summary>
        /// PROMO_TIER_AMT1
        /// </summary>
        public static string M_PROMO_TIER_AMT1 = "PROMO_TIER_AMT1";

        private string _PROMO_TIER_RATE1;

        /// <summary>
        /// PROMO_TIER_RATE1
        /// </summary>
        public static string M_PROMO_TIER_RATE1 = "PROMO_TIER_RATE1";

        private string _BTHDTE_TIER_AMT1;

        /// <summary>
        /// BTHDTE_TIER_AMT1
        /// </summary>
        public static string M_BTHDTE_TIER_AMT1 = "BTHDTE_TIER_AMT1";

        private string _BTHDTE_TIER_RATE1;

        /// <summary>
        /// BTHDTE_TIER_RATE1
        /// </summary>
        public static string M_BTHDTE_TIER_RATE1 = "BTHDTE_TIER_RATE1";

        private string _BASIC_TIER_AMT2;

        /// <summary>
        /// BASIC_TIER_AMT2
        /// </summary>
        public static string M_BASIC_TIER_AMT2 = "BASIC_TIER_AMT2";

        private string _BASIC_TIER_RATE2;

        /// <summary>
        /// BASIC_TIER_RATE2
        /// </summary>
        public static string M_BASIC_TIER_RATE2 = "BASIC_TIER_RATE2";

        private string _SUPP_BASIC_TIER_AMT2;

        /// <summary>
        /// SUPP_BASIC_TIER_AMT2
        /// </summary>
        public static string M_SUPP_BASIC_TIER_AMT2 = "SUPP_BASIC_TIER_AMT2";

        private string _SUPP_BASIC_TIER_RATE2;

        /// <summary>
        /// SUPP_BASIC_TIER_RATE2
        /// </summary>
        public static string M_SUPP_BASIC_TIER_RATE2 = "SUPP_BASIC_TIER_RATE2";

        private string _PROMO_TIER_AMT2;

        /// <summary>
        /// PROMO_TIER_AMT2
        /// </summary>
        public static string M_PROMO_TIER_AMT2 = "PROMO_TIER_AMT2";

        private string _PROMO_TIER_RATE2;

        /// <summary>
        /// PROMO_TIER_RATE2
        /// </summary>
        public static string M_PROMO_TIER_RATE2 = "PROMO_TIER_RATE2";

        private string _BTHDTE_TIER_AMT2;

        /// <summary>
        /// BTHDTE_TIER_AMT2
        /// </summary>
        public static string M_BTHDTE_TIER_AMT2 = "BTHDTE_TIER_AMT2";

        private string _BTHDTE_TIER_RATE2;

        /// <summary>
        /// BTHDTE_TIER_RATE2
        /// </summary>
        public static string M_BTHDTE_TIER_RATE2 = "BTHDTE_TIER_RATE2";

        private string _BASIC_TIER_AMT3;

        /// <summary>
        /// BASIC_TIER_AMT3
        /// </summary>
        public static string M_BASIC_TIER_AMT3 = "BASIC_TIER_AMT3";

        private string _BASIC_TIER_RATE3;

        /// <summary>
        /// BASIC_TIER_RATE3
        /// </summary>
        public static string M_BASIC_TIER_RATE3 = "BASIC_TIER_RATE3";

        private string _SUPP_BASIC_TIER_AMT3;

        /// <summary>
        /// SUPP_BASIC_TIER_AMT3
        /// </summary>
        public static string M_SUPP_BASIC_TIER_AMT3 = "SUPP_BASIC_TIER_AMT3";

        private string _SUPP_BASIC_TIER_RATE3;

        /// <summary>
        /// SUPP_BASIC_TIER_RATE3
        /// </summary>
        public static string M_SUPP_BASIC_TIER_RATE3 = "SUPP_BASIC_TIER_RATE3";

        private string _PROMO_TIER_AMT3;

        /// <summary>
        /// PROMO_TIER_AMT3
        /// </summary>
        public static string M_PROMO_TIER_AMT3 = "PROMO_TIER_AMT3";

        private string _PROMO_TIER_RATE3;

        /// <summary>
        /// PROMO_TIER_RATE3
        /// </summary>
        public static string M_PROMO_TIER_RATE3 = "PROMO_TIER_RATE3";

        private string _BTHDTE_TIER_AMT3;

        /// <summary>
        /// BTHDTE_TIER_AMT3
        /// </summary>
        public static string M_BTHDTE_TIER_AMT3 = "BTHDTE_TIER_AMT3";

        private string _BTHDTE_TIER_RATE3;

        /// <summary>
        /// BTHDTE_TIER_RATE3
        /// </summary>
        public static string M_BTHDTE_TIER_RATE3 = "BTHDTE_TIER_RATE3";

        private string _BASIC_TIER_AMT4;

        /// <summary>
        /// BASIC_TIER_AMT4
        /// </summary>
        public static string M_BASIC_TIER_AMT4 = "BASIC_TIER_AMT4";

        private string _BASIC_TIER_RATE4;

        /// <summary>
        /// BASIC_TIER_RATE4
        /// </summary>
        public static string M_BASIC_TIER_RATE4 = "BASIC_TIER_RATE4";

        private string _SUPP_BASIC_TIER_AMT4;

        /// <summary>
        /// SUPP_BASIC_TIER_AMT4
        /// </summary>
        public static string M_SUPP_BASIC_TIER_AMT4 = "SUPP_BASIC_TIER_AMT4";

        private string _SUPP_BASIC_TIER_RATE4;

        /// <summary>
        /// SUPP_BASIC_TIER_RATE4
        /// </summary>
        public static string M_SUPP_BASIC_TIER_RATE4 = "SUPP_BASIC_TIER_RATE4";

        private string _PROMO_TIER_AMT4;

        /// <summary>
        /// PROMO_TIER_AMT4
        /// </summary>
        public static string M_PROMO_TIER_AMT4 = "PROMO_TIER_AMT4";

        private string _PROMO_TIER_RATE4;

        /// <summary>
        /// PROMO_TIER_RATE4
        /// </summary>
        public static string M_PROMO_TIER_RATE4 = "PROMO_TIER_RATE4";

        private string _BTHDTE_TIER_AMT4;

        /// <summary>
        /// BTHDTE_TIER_AMT4
        /// </summary>
        public static string M_BTHDTE_TIER_AMT4 = "BTHDTE_TIER_AMT4";

        private string _BTHDTE_TIER_RATE4;

        /// <summary>
        /// BTHDTE_TIER_RATE4
        /// </summary>
        public static string M_BTHDTE_TIER_RATE4 = "BTHDTE_TIER_RATE4";

        private string _SEND_FLAG;

        /// <summary>
        /// SEND_FLAG
        /// </summary>
        public static string M_SEND_FLAG = "SEND_FLAG";

        /// <summary>
        /// ID
        /// </summary>
        [AttributeField("ID", "System.Int32", false, true, true, "Int32")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this._ID = value;
            }
        }

        /// <summary>
        /// RECEIVE_NUMBER
        /// </summary>
        [AttributeField("RECEIVE_NUMBER", "System.String", false, false, false, "String")]
        public string RECEIVE_NUMBER
        {
            get
            {
                return this._RECEIVE_NUMBER;
            }
            set
            {
                this._RECEIVE_NUMBER = value;
            }
        }

        /// <summary>
        /// USER_ID
        /// </summary>
        [AttributeField("USER_ID", "System.String", false, false, false, "String")]
        public string USER_ID
        {
            get
            {
                return this._USER_ID;
            }
            set
            {
                this._USER_ID = value;
            }
        }

        /// <summary>
        /// FUNCTION_CODE
        /// </summary>
        [AttributeField("FUNCTION_CODE", "System.String", false, false, false, "String")]
        public string FUNCTION_CODE
        {
            get
            {
                return this._FUNCTION_CODE;
            }
            set
            {
                this._FUNCTION_CODE = value;
            }
        }

        /// <summary>
        /// MSG_SEQ
        /// </summary>
        [AttributeField("MSG_SEQ", "System.String", false, false, false, "String")]
        public string MSG_SEQ
        {
            get
            {
                return this._MSG_SEQ;
            }
            set
            {
                this._MSG_SEQ = value;
            }
        }

        /// <summary>
        /// MSG_TYPE
        /// </summary>
        [AttributeField("MSG_TYPE", "System.String", false, false, false, "String")]
        public string MSG_TYPE
        {
            get
            {
                return this._MSG_TYPE;
            }
            set
            {
                this._MSG_TYPE = value;
            }
        }

        /// <summary>
        /// ORG
        /// </summary>
        [AttributeField("ORG", "System.String", false, false, false, "String")]
        public string ORG
        {
            get
            {
                return this._ORG;
            }
            set
            {
                this._ORG = value;
            }
        }

        /// <summary>
        /// PROG_ID
        /// </summary>
        [AttributeField("PROG_ID", "System.String", false, false, false, "String")]
        public string PROG_ID
        {
            get
            {
                return this._PROG_ID;
            }
            set
            {
                this._PROG_ID = value;
            }
        }

        /// <summary>
        /// PARTNER_ID
        /// </summary>
        [AttributeField("PARTNER_ID", "System.String", false, false, false, "String")]
        public string PARTNER_ID
        {
            get
            {
                return this._PARTNER_ID;
            }
            set
            {
                this._PARTNER_ID = value;
            }
        }

        /// <summary>
        /// ACCUMULATION_TYPE
        /// </summary>
        [AttributeField("ACCUMULATION_TYPE", "System.String", false, false, false, "String")]
        public string ACCUMULATION_TYPE
        {
            get
            {
                return this._ACCUMULATION_TYPE;
            }
            set
            {
                this._ACCUMULATION_TYPE = value;
            }
        }

        /// <summary>
        /// COUNTRY_CODE_IND
        /// </summary>
        [AttributeField("COUNTRY_CODE_IND", "System.String", false, false, false, "String")]
        public string COUNTRY_CODE_IND
        {
            get
            {
                return this._COUNTRY_CODE_IND;
            }
            set
            {
                this._COUNTRY_CODE_IND = value;
            }
        }

        /// <summary>
        /// BASIC_CALC_MTHD
        /// </summary>
        [AttributeField("BASIC_CALC_MTHD", "System.String", false, false, false, "String")]
        public string BASIC_CALC_MTHD
        {
            get
            {
                return this._BASIC_CALC_MTHD;
            }
            set
            {
                this._BASIC_CALC_MTHD = value;
            }
        }

        /// <summary>
        /// BASIC_CALC_IND
        /// </summary>
        [AttributeField("BASIC_CALC_IND", "System.String", false, false, false, "String")]
        public string BASIC_CALC_IND
        {
            get
            {
                return this._BASIC_CALC_IND;
            }
            set
            {
                this._BASIC_CALC_IND = value;
            }
        }

        /// <summary>
        /// SUPP_BASIC_CAL_MTHD
        /// </summary>
        [AttributeField("SUPP_BASIC_CAL_MTHD", "System.String", false, false, false, "String")]
        public string SUPP_BASIC_CAL_MTHD
        {
            get
            {
                return this._SUPP_BASIC_CAL_MTHD;
            }
            set
            {
                this._SUPP_BASIC_CAL_MTHD = value;
            }
        }

        /// <summary>
        /// SUPP_BASIC_CAL_IND
        /// </summary>
        [AttributeField("SUPP_BASIC_CAL_IND", "System.String", false, false, false, "String")]
        public string SUPP_BASIC_CAL_IND
        {
            get
            {
                return this._SUPP_BASIC_CAL_IND;
            }
            set
            {
                this._SUPP_BASIC_CAL_IND = value;
            }
        }

        /// <summary>
        /// PROMO_START_DTE
        /// </summary>
        [AttributeField("PROMO_START_DTE", "System.String", false, false, false, "String")]
        public string PROMO_START_DTE
        {
            get
            {
                return this._PROMO_START_DTE;
            }
            set
            {
                this._PROMO_START_DTE = value;
            }
        }

        /// <summary>
        /// PROMO_END_DTE
        /// </summary>
        [AttributeField("PROMO_END_DTE", "System.String", false, false, false, "String")]
        public string PROMO_END_DTE
        {
            get
            {
                return this._PROMO_END_DTE;
            }
            set
            {
                this._PROMO_END_DTE = value;
            }
        }

        /// <summary>
        /// PROMO_CALC_MTHD
        /// </summary>
        [AttributeField("PROMO_CALC_MTHD", "System.String", false, false, false, "String")]
        public string PROMO_CALC_MTHD
        {
            get
            {
                return this._PROMO_CALC_MTHD;
            }
            set
            {
                this._PROMO_CALC_MTHD = value;
            }
        }

        /// <summary>
        /// PROMO_CALC_IND
        /// </summary>
        [AttributeField("PROMO_CALC_IND", "System.String", false, false, false, "String")]
        public string PROMO_CALC_IND
        {
            get
            {
                return this._PROMO_CALC_IND;
            }
            set
            {
                this._PROMO_CALC_IND = value;
            }
        }

        /// <summary>
        /// BTHDTE_FLAG
        /// </summary>
        [AttributeField("BTHDTE_FLAG", "System.String", false, false, false, "String")]
        public string BTHDTE_FLAG
        {
            get
            {
                return this._BTHDTE_FLAG;
            }
            set
            {
                this._BTHDTE_FLAG = value;
            }
        }

        /// <summary>
        /// BTHDTE_START
        /// </summary>
        [AttributeField("BTHDTE_START", "System.String", false, false, false, "String")]
        public string BTHDTE_START
        {
            get
            {
                return this._BTHDTE_START;
            }
            set
            {
                this._BTHDTE_START = value;
            }
        }

        /// <summary>
        /// BTHDTE_END
        /// </summary>
        [AttributeField("BTHDTE_END", "System.String", false, false, false, "String")]
        public string BTHDTE_END
        {
            get
            {
                return this._BTHDTE_END;
            }
            set
            {
                this._BTHDTE_END = value;
            }
        }

        /// <summary>
        /// BTHDTE_CALC_MTHD
        /// </summary>
        [AttributeField("BTHDTE_CALC_MTHD", "System.String", false, false, false, "String")]
        public string BTHDTE_CALC_MTHD
        {
            get
            {
                return this._BTHDTE_CALC_MTHD;
            }
            set
            {
                this._BTHDTE_CALC_MTHD = value;
            }
        }

        /// <summary>
        /// BTHDTE_CALC_IND
        /// </summary>
        [AttributeField("BTHDTE_CALC_IND", "System.String", false, false, false, "String")]
        public string BTHDTE_CALC_IND
        {
            get
            {
                return this._BTHDTE_CALC_IND;
            }
            set
            {
                this._BTHDTE_CALC_IND = value;
            }
        }

        /// <summary>
        /// M_SIGNON_NAME
        /// </summary>
        [AttributeField("M_SIGNON_NAME", "System.String", false, false, false, "String")]
        public string M_SIGNON_NAME
        {
            get
            {
                return this._M_SIGNON_NAME;
            }
            set
            {
                this._M_SIGNON_NAME = value;
            }
        }

        /// <summary>
        /// TC_CODE1
        /// </summary>
        [AttributeField("TC_CODE1", "System.String", false, false, false, "String")]
        public string TC_CODE1
        {
            get
            {
                return this._TC_CODE1;
            }
            set
            {
                this._TC_CODE1 = value;
            }
        }

        /// <summary>
        /// TC_OP1
        /// </summary>
        [AttributeField("TC_OP1", "System.String", false, false, false, "String")]
        public string TC_OP1
        {
            get
            {
                return this._TC_OP1;
            }
            set
            {
                this._TC_OP1 = value;
            }
        }

        /// <summary>
        /// TC_CODE2
        /// </summary>
        [AttributeField("TC_CODE2", "System.String", false, false, false, "String")]
        public string TC_CODE2
        {
            get
            {
                return this._TC_CODE2;
            }
            set
            {
                this._TC_CODE2 = value;
            }
        }

        /// <summary>
        /// TC_OP2
        /// </summary>
        [AttributeField("TC_OP2", "System.String", false, false, false, "String")]
        public string TC_OP2
        {
            get
            {
                return this._TC_OP2;
            }
            set
            {
                this._TC_OP2 = value;
            }
        }

        /// <summary>
        /// TC_CODE3
        /// </summary>
        [AttributeField("TC_CODE3", "System.String", false, false, false, "String")]
        public string TC_CODE3
        {
            get
            {
                return this._TC_CODE3;
            }
            set
            {
                this._TC_CODE3 = value;
            }
        }

        /// <summary>
        /// TC_OP3
        /// </summary>
        [AttributeField("TC_OP3", "System.String", false, false, false, "String")]
        public string TC_OP3
        {
            get
            {
                return this._TC_OP3;
            }
            set
            {
                this._TC_OP3 = value;
            }
        }

        /// <summary>
        /// TC_CODE4
        /// </summary>
        [AttributeField("TC_CODE4", "System.String", false, false, false, "String")]
        public string TC_CODE4
        {
            get
            {
                return this._TC_CODE4;
            }
            set
            {
                this._TC_CODE4 = value;
            }
        }

        /// <summary>
        /// TC_OP4
        /// </summary>
        [AttributeField("TC_OP4", "System.String", false, false, false, "String")]
        public string TC_OP4
        {
            get
            {
                return this._TC_OP4;
            }
            set
            {
                this._TC_OP4 = value;
            }
        }

        /// <summary>
        /// TC_CODE5
        /// </summary>
        [AttributeField("TC_CODE5", "System.String", false, false, false, "String")]
        public string TC_CODE5
        {
            get
            {
                return this._TC_CODE5;
            }
            set
            {
                this._TC_CODE5 = value;
            }
        }

        /// <summary>
        /// TC_OP5
        /// </summary>
        [AttributeField("TC_OP5", "System.String", false, false, false, "String")]
        public string TC_OP5
        {
            get
            {
                return this._TC_OP5;
            }
            set
            {
                this._TC_OP5 = value;
            }
        }

        /// <summary>
        /// TC_CODE6
        /// </summary>
        [AttributeField("TC_CODE6", "System.String", false, false, false, "String")]
        public string TC_CODE6
        {
            get
            {
                return this._TC_CODE6;
            }
            set
            {
                this._TC_CODE6 = value;
            }
        }

        /// <summary>
        /// TC_OP6
        /// </summary>
        [AttributeField("TC_OP6", "System.String", false, false, false, "String")]
        public string TC_OP6
        {
            get
            {
                return this._TC_OP6;
            }
            set
            {
                this._TC_OP6 = value;
            }
        }

        /// <summary>
        /// TC_CODE7
        /// </summary>
        [AttributeField("TC_CODE7", "System.String", false, false, false, "String")]
        public string TC_CODE7
        {
            get
            {
                return this._TC_CODE7;
            }
            set
            {
                this._TC_CODE7 = value;
            }
        }

        /// <summary>
        /// TC_OP7
        /// </summary>
        [AttributeField("TC_OP7", "System.String", false, false, false, "String")]
        public string TC_OP7
        {
            get
            {
                return this._TC_OP7;
            }
            set
            {
                this._TC_OP7 = value;
            }
        }

        /// <summary>
        /// TC_CODE8
        /// </summary>
        [AttributeField("TC_CODE8", "System.String", false, false, false, "String")]
        public string TC_CODE8
        {
            get
            {
                return this._TC_CODE8;
            }
            set
            {
                this._TC_CODE8 = value;
            }
        }

        /// <summary>
        /// TC_OP8
        /// </summary>
        [AttributeField("TC_OP8", "System.String", false, false, false, "String")]
        public string TC_OP8
        {
            get
            {
                return this._TC_OP8;
            }
            set
            {
                this._TC_OP8 = value;
            }
        }

        /// <summary>
        /// TC_CODE9
        /// </summary>
        [AttributeField("TC_CODE9", "System.String", false, false, false, "String")]
        public string TC_CODE9
        {
            get
            {
                return this._TC_CODE9;
            }
            set
            {
                this._TC_CODE9 = value;
            }
        }

        /// <summary>
        /// TC_OP9
        /// </summary>
        [AttributeField("TC_OP9", "System.String", false, false, false, "String")]
        public string TC_OP9
        {
            get
            {
                return this._TC_OP9;
            }
            set
            {
                this._TC_OP9 = value;
            }
        }

        /// <summary>
        /// TC_CODE10
        /// </summary>
        [AttributeField("TC_CODE10", "System.String", false, false, false, "String")]
        public string TC_CODE10
        {
            get
            {
                return this._TC_CODE10;
            }
            set
            {
                this._TC_CODE10 = value;
            }
        }

        /// <summary>
        /// TC_OP10
        /// </summary>
        [AttributeField("TC_OP10", "System.String", false, false, false, "String")]
        public string TC_OP10
        {
            get
            {
                return this._TC_OP10;
            }
            set
            {
                this._TC_OP10 = value;
            }
        }

        /// <summary>
        /// MCC_FROM1
        /// </summary>
        [AttributeField("MCC_FROM1", "System.String", false, false, false, "String")]
        public string MCC_FROM1
        {
            get
            {
                return this._MCC_FROM1;
            }
            set
            {
                this._MCC_FROM1 = value;
            }
        }

        /// <summary>
        /// MCC_TO1
        /// </summary>
        [AttributeField("MCC_TO1", "System.String", false, false, false, "String")]
        public string MCC_TO1
        {
            get
            {
                return this._MCC_TO1;
            }
            set
            {
                this._MCC_TO1 = value;
            }
        }

        /// <summary>
        /// COUNTRY_CODE1
        /// </summary>
        [AttributeField("COUNTRY_CODE1", "System.String", false, false, false, "String")]
        public string COUNTRY_CODE1
        {
            get
            {
                return this._COUNTRY_CODE1;
            }
            set
            {
                this._COUNTRY_CODE1 = value;
            }
        }

        /// <summary>
        /// MCC_FROM2
        /// </summary>
        [AttributeField("MCC_FROM2", "System.String", false, false, false, "String")]
        public string MCC_FROM2
        {
            get
            {
                return this._MCC_FROM2;
            }
            set
            {
                this._MCC_FROM2 = value;
            }
        }

        /// <summary>
        /// MCC_TO2
        /// </summary>
        [AttributeField("MCC_TO2", "System.String", false, false, false, "String")]
        public string MCC_TO2
        {
            get
            {
                return this._MCC_TO2;
            }
            set
            {
                this._MCC_TO2 = value;
            }
        }

        /// <summary>
        /// COUNTRY_CODE2
        /// </summary>
        [AttributeField("COUNTRY_CODE2", "System.String", false, false, false, "String")]
        public string COUNTRY_CODE2
        {
            get
            {
                return this._COUNTRY_CODE2;
            }
            set
            {
                this._COUNTRY_CODE2 = value;
            }
        }

        /// <summary>
        /// MCC_FROM3
        /// </summary>
        [AttributeField("MCC_FROM3", "System.String", false, false, false, "String")]
        public string MCC_FROM3
        {
            get
            {
                return this._MCC_FROM3;
            }
            set
            {
                this._MCC_FROM3 = value;
            }
        }

        /// <summary>
        /// MCC_TO3
        /// </summary>
        [AttributeField("MCC_TO3", "System.String", false, false, false, "String")]
        public string MCC_TO3
        {
            get
            {
                return this._MCC_TO3;
            }
            set
            {
                this._MCC_TO3 = value;
            }
        }

        /// <summary>
        /// COUNTRY_CODE3
        /// </summary>
        [AttributeField("COUNTRY_CODE3", "System.String", false, false, false, "String")]
        public string COUNTRY_CODE3
        {
            get
            {
                return this._COUNTRY_CODE3;
            }
            set
            {
                this._COUNTRY_CODE3 = value;
            }
        }

        /// <summary>
        /// MCC_FROM4
        /// </summary>
        [AttributeField("MCC_FROM4", "System.String", false, false, false, "String")]
        public string MCC_FROM4
        {
            get
            {
                return this._MCC_FROM4;
            }
            set
            {
                this._MCC_FROM4 = value;
            }
        }

        /// <summary>
        /// MCC_TO4
        /// </summary>
        [AttributeField("MCC_TO4", "System.String", false, false, false, "String")]
        public string MCC_TO4
        {
            get
            {
                return this._MCC_TO4;
            }
            set
            {
                this._MCC_TO4 = value;
            }
        }

        /// <summary>
        /// COUNTRY_CODE4
        /// </summary>
        [AttributeField("COUNTRY_CODE4", "System.String", false, false, false, "String")]
        public string COUNTRY_CODE4
        {
            get
            {
                return this._COUNTRY_CODE4;
            }
            set
            {
                this._COUNTRY_CODE4 = value;
            }
        }

        /// <summary>
        /// MCC_FROM5
        /// </summary>
        [AttributeField("MCC_FROM5", "System.String", false, false, false, "String")]
        public string MCC_FROM5
        {
            get
            {
                return this._MCC_FROM5;
            }
            set
            {
                this._MCC_FROM5 = value;
            }
        }

        /// <summary>
        /// MCC_TO5
        /// </summary>
        [AttributeField("MCC_TO5", "System.String", false, false, false, "String")]
        public string MCC_TO5
        {
            get
            {
                return this._MCC_TO5;
            }
            set
            {
                this._MCC_TO5 = value;
            }
        }

        /// <summary>
        /// COUNTRY_CODE5
        /// </summary>
        [AttributeField("COUNTRY_CODE5", "System.String", false, false, false, "String")]
        public string COUNTRY_CODE5
        {
            get
            {
                return this._COUNTRY_CODE5;
            }
            set
            {
                this._COUNTRY_CODE5 = value;
            }
        }

        /// <summary>
        /// MCC_FROM6
        /// </summary>
        [AttributeField("MCC_FROM6", "System.String", false, false, false, "String")]
        public string MCC_FROM6
        {
            get
            {
                return this._MCC_FROM6;
            }
            set
            {
                this._MCC_FROM6 = value;
            }
        }

        /// <summary>
        /// MCC_TO6
        /// </summary>
        [AttributeField("MCC_TO6", "System.String", false, false, false, "String")]
        public string MCC_TO6
        {
            get
            {
                return this._MCC_TO6;
            }
            set
            {
                this._MCC_TO6 = value;
            }
        }

        /// <summary>
        /// COUNTRY_CODE6
        /// </summary>
        [AttributeField("COUNTRY_CODE6", "System.String", false, false, false, "String")]
        public string COUNTRY_CODE6
        {
            get
            {
                return this._COUNTRY_CODE6;
            }
            set
            {
                this._COUNTRY_CODE6 = value;
            }
        }

        /// <summary>
        /// MCC_FROM7
        /// </summary>
        [AttributeField("MCC_FROM7", "System.String", false, false, false, "String")]
        public string MCC_FROM7
        {
            get
            {
                return this._MCC_FROM7;
            }
            set
            {
                this._MCC_FROM7 = value;
            }
        }

        /// <summary>
        /// MCC_TO7
        /// </summary>
        [AttributeField("MCC_TO7", "System.String", false, false, false, "String")]
        public string MCC_TO7
        {
            get
            {
                return this._MCC_TO7;
            }
            set
            {
                this._MCC_TO7 = value;
            }
        }

        /// <summary>
        /// COUNTRY_CODE7
        /// </summary>
        [AttributeField("COUNTRY_CODE7", "System.String", false, false, false, "String")]
        public string COUNTRY_CODE7
        {
            get
            {
                return this._COUNTRY_CODE7;
            }
            set
            {
                this._COUNTRY_CODE7 = value;
            }
        }

        /// <summary>
        /// MCC_FROM8
        /// </summary>
        [AttributeField("MCC_FROM8", "System.String", false, false, false, "String")]
        public string MCC_FROM8
        {
            get
            {
                return this._MCC_FROM8;
            }
            set
            {
                this._MCC_FROM8 = value;
            }
        }

        /// <summary>
        /// MCC_TO8
        /// </summary>
        [AttributeField("MCC_TO8", "System.String", false, false, false, "String")]
        public string MCC_TO8
        {
            get
            {
                return this._MCC_TO8;
            }
            set
            {
                this._MCC_TO8 = value;
            }
        }

        /// <summary>
        /// COUNTRY_CODE8
        /// </summary>
        [AttributeField("COUNTRY_CODE8", "System.String", false, false, false, "String")]
        public string COUNTRY_CODE8
        {
            get
            {
                return this._COUNTRY_CODE8;
            }
            set
            {
                this._COUNTRY_CODE8 = value;
            }
        }

        /// <summary>
        /// MCC_FROM9
        /// </summary>
        [AttributeField("MCC_FROM9", "System.String", false, false, false, "String")]
        public string MCC_FROM9
        {
            get
            {
                return this._MCC_FROM9;
            }
            set
            {
                this._MCC_FROM9 = value;
            }
        }

        /// <summary>
        /// MCC_TO9
        /// </summary>
        [AttributeField("MCC_TO9", "System.String", false, false, false, "String")]
        public string MCC_TO9
        {
            get
            {
                return this._MCC_TO9;
            }
            set
            {
                this._MCC_TO9 = value;
            }
        }

        /// <summary>
        /// COUNTRY_CODE9
        /// </summary>
        [AttributeField("COUNTRY_CODE9", "System.String", false, false, false, "String")]
        public string COUNTRY_CODE9
        {
            get
            {
                return this._COUNTRY_CODE9;
            }
            set
            {
                this._COUNTRY_CODE9 = value;
            }
        }

        /// <summary>
        /// MCC_FROM10
        /// </summary>
        [AttributeField("MCC_FROM10", "System.String", false, false, false, "String")]
        public string MCC_FROM10
        {
            get
            {
                return this._MCC_FROM10;
            }
            set
            {
                this._MCC_FROM10 = value;
            }
        }

        /// <summary>
        /// MCC_TO10
        /// </summary>
        [AttributeField("MCC_TO10", "System.String", false, false, false, "String")]
        public string MCC_TO10
        {
            get
            {
                return this._MCC_TO10;
            }
            set
            {
                this._MCC_TO10 = value;
            }
        }

        /// <summary>
        /// COUNTRY_CODE10
        /// </summary>
        [AttributeField("COUNTRY_CODE10", "System.String", false, false, false, "String")]
        public string COUNTRY_CODE10
        {
            get
            {
                return this._COUNTRY_CODE10;
            }
            set
            {
                this._COUNTRY_CODE10 = value;
            }
        }

        /// <summary>
        /// BASIC_TIER_AMT1
        /// </summary>
        [AttributeField("BASIC_TIER_AMT1", "System.String", false, false, false, "String")]
        public string BASIC_TIER_AMT1
        {
            get
            {
                return this._BASIC_TIER_AMT1;
            }
            set
            {
                this._BASIC_TIER_AMT1 = value;
            }
        }

        /// <summary>
        /// BASIC_TIER_RATE1
        /// </summary>
        [AttributeField("BASIC_TIER_RATE1", "System.String", false, false, false, "String")]
        public string BASIC_TIER_RATE1
        {
            get
            {
                return this._BASIC_TIER_RATE1;
            }
            set
            {
                this._BASIC_TIER_RATE1 = value;
            }
        }

        /// <summary>
        /// SUPP_BASIC_TIER_AMT1
        /// </summary>
        [AttributeField("SUPP_BASIC_TIER_AMT1", "System.String", false, false, false, "String")]
        public string SUPP_BASIC_TIER_AMT1
        {
            get
            {
                return this._SUPP_BASIC_TIER_AMT1;
            }
            set
            {
                this._SUPP_BASIC_TIER_AMT1 = value;
            }
        }

        /// <summary>
        /// SUPP_BASIC_TIER_RATE1
        /// </summary>
        [AttributeField("SUPP_BASIC_TIER_RATE1", "System.String", false, false, false, "String")]
        public string SUPP_BASIC_TIER_RATE1
        {
            get
            {
                return this._SUPP_BASIC_TIER_RATE1;
            }
            set
            {
                this._SUPP_BASIC_TIER_RATE1 = value;
            }
        }

        /// <summary>
        /// PROMO_TIER_AMT1
        /// </summary>
        [AttributeField("PROMO_TIER_AMT1", "System.String", false, false, false, "String")]
        public string PROMO_TIER_AMT1
        {
            get
            {
                return this._PROMO_TIER_AMT1;
            }
            set
            {
                this._PROMO_TIER_AMT1 = value;
            }
        }

        /// <summary>
        /// PROMO_TIER_RATE1
        /// </summary>
        [AttributeField("PROMO_TIER_RATE1", "System.String", false, false, false, "String")]
        public string PROMO_TIER_RATE1
        {
            get
            {
                return this._PROMO_TIER_RATE1;
            }
            set
            {
                this._PROMO_TIER_RATE1 = value;
            }
        }

        /// <summary>
        /// BTHDTE_TIER_AMT1
        /// </summary>
        [AttributeField("BTHDTE_TIER_AMT1", "System.String", false, false, false, "String")]
        public string BTHDTE_TIER_AMT1
        {
            get
            {
                return this._BTHDTE_TIER_AMT1;
            }
            set
            {
                this._BTHDTE_TIER_AMT1 = value;
            }
        }

        /// <summary>
        /// BTHDTE_TIER_RATE1
        /// </summary>
        [AttributeField("BTHDTE_TIER_RATE1", "System.String", false, false, false, "String")]
        public string BTHDTE_TIER_RATE1
        {
            get
            {
                return this._BTHDTE_TIER_RATE1;
            }
            set
            {
                this._BTHDTE_TIER_RATE1 = value;
            }
        }

        /// <summary>
        /// BASIC_TIER_AMT2
        /// </summary>
        [AttributeField("BASIC_TIER_AMT2", "System.String", false, false, false, "String")]
        public string BASIC_TIER_AMT2
        {
            get
            {
                return this._BASIC_TIER_AMT2;
            }
            set
            {
                this._BASIC_TIER_AMT2 = value;
            }
        }

        /// <summary>
        /// BASIC_TIER_RATE2
        /// </summary>
        [AttributeField("BASIC_TIER_RATE2", "System.String", false, false, false, "String")]
        public string BASIC_TIER_RATE2
        {
            get
            {
                return this._BASIC_TIER_RATE2;
            }
            set
            {
                this._BASIC_TIER_RATE2 = value;
            }
        }

        /// <summary>
        /// SUPP_BASIC_TIER_AMT2
        /// </summary>
        [AttributeField("SUPP_BASIC_TIER_AMT2", "System.String", false, false, false, "String")]
        public string SUPP_BASIC_TIER_AMT2
        {
            get
            {
                return this._SUPP_BASIC_TIER_AMT2;
            }
            set
            {
                this._SUPP_BASIC_TIER_AMT2 = value;
            }
        }

        /// <summary>
        /// SUPP_BASIC_TIER_RATE2
        /// </summary>
        [AttributeField("SUPP_BASIC_TIER_RATE2", "System.String", false, false, false, "String")]
        public string SUPP_BASIC_TIER_RATE2
        {
            get
            {
                return this._SUPP_BASIC_TIER_RATE2;
            }
            set
            {
                this._SUPP_BASIC_TIER_RATE2 = value;
            }
        }

        /// <summary>
        /// PROMO_TIER_AMT2
        /// </summary>
        [AttributeField("PROMO_TIER_AMT2", "System.String", false, false, false, "String")]
        public string PROMO_TIER_AMT2
        {
            get
            {
                return this._PROMO_TIER_AMT2;
            }
            set
            {
                this._PROMO_TIER_AMT2 = value;
            }
        }

        /// <summary>
        /// PROMO_TIER_RATE2
        /// </summary>
        [AttributeField("PROMO_TIER_RATE2", "System.String", false, false, false, "String")]
        public string PROMO_TIER_RATE2
        {
            get
            {
                return this._PROMO_TIER_RATE2;
            }
            set
            {
                this._PROMO_TIER_RATE2 = value;
            }
        }

        /// <summary>
        /// BTHDTE_TIER_AMT2
        /// </summary>
        [AttributeField("BTHDTE_TIER_AMT2", "System.String", false, false, false, "String")]
        public string BTHDTE_TIER_AMT2
        {
            get
            {
                return this._BTHDTE_TIER_AMT2;
            }
            set
            {
                this._BTHDTE_TIER_AMT2 = value;
            }
        }

        /// <summary>
        /// BTHDTE_TIER_RATE2
        /// </summary>
        [AttributeField("BTHDTE_TIER_RATE2", "System.String", false, false, false, "String")]
        public string BTHDTE_TIER_RATE2
        {
            get
            {
                return this._BTHDTE_TIER_RATE2;
            }
            set
            {
                this._BTHDTE_TIER_RATE2 = value;
            }
        }

        /// <summary>
        /// BASIC_TIER_AMT3
        /// </summary>
        [AttributeField("BASIC_TIER_AMT3", "System.String", false, false, false, "String")]
        public string BASIC_TIER_AMT3
        {
            get
            {
                return this._BASIC_TIER_AMT3;
            }
            set
            {
                this._BASIC_TIER_AMT3 = value;
            }
        }

        /// <summary>
        /// BASIC_TIER_RATE3
        /// </summary>
        [AttributeField("BASIC_TIER_RATE3", "System.String", false, false, false, "String")]
        public string BASIC_TIER_RATE3
        {
            get
            {
                return this._BASIC_TIER_RATE3;
            }
            set
            {
                this._BASIC_TIER_RATE3 = value;
            }
        }

        /// <summary>
        /// SUPP_BASIC_TIER_AMT3
        /// </summary>
        [AttributeField("SUPP_BASIC_TIER_AMT3", "System.String", false, false, false, "String")]
        public string SUPP_BASIC_TIER_AMT3
        {
            get
            {
                return this._SUPP_BASIC_TIER_AMT3;
            }
            set
            {
                this._SUPP_BASIC_TIER_AMT3 = value;
            }
        }

        /// <summary>
        /// SUPP_BASIC_TIER_RATE3
        /// </summary>
        [AttributeField("SUPP_BASIC_TIER_RATE3", "System.String", false, false, false, "String")]
        public string SUPP_BASIC_TIER_RATE3
        {
            get
            {
                return this._SUPP_BASIC_TIER_RATE3;
            }
            set
            {
                this._SUPP_BASIC_TIER_RATE3 = value;
            }
        }

        /// <summary>
        /// PROMO_TIER_AMT3
        /// </summary>
        [AttributeField("PROMO_TIER_AMT3", "System.String", false, false, false, "String")]
        public string PROMO_TIER_AMT3
        {
            get
            {
                return this._PROMO_TIER_AMT3;
            }
            set
            {
                this._PROMO_TIER_AMT3 = value;
            }
        }

        /// <summary>
        /// PROMO_TIER_RATE3
        /// </summary>
        [AttributeField("PROMO_TIER_RATE3", "System.String", false, false, false, "String")]
        public string PROMO_TIER_RATE3
        {
            get
            {
                return this._PROMO_TIER_RATE3;
            }
            set
            {
                this._PROMO_TIER_RATE3 = value;
            }
        }

        /// <summary>
        /// BTHDTE_TIER_AMT3
        /// </summary>
        [AttributeField("BTHDTE_TIER_AMT3", "System.String", false, false, false, "String")]
        public string BTHDTE_TIER_AMT3
        {
            get
            {
                return this._BTHDTE_TIER_AMT3;
            }
            set
            {
                this._BTHDTE_TIER_AMT3 = value;
            }
        }

        /// <summary>
        /// BTHDTE_TIER_RATE3
        /// </summary>
        [AttributeField("BTHDTE_TIER_RATE3", "System.String", false, false, false, "String")]
        public string BTHDTE_TIER_RATE3
        {
            get
            {
                return this._BTHDTE_TIER_RATE3;
            }
            set
            {
                this._BTHDTE_TIER_RATE3 = value;
            }
        }

        /// <summary>
        /// BASIC_TIER_AMT4
        /// </summary>
        [AttributeField("BASIC_TIER_AMT4", "System.String", false, false, false, "String")]
        public string BASIC_TIER_AMT4
        {
            get
            {
                return this._BASIC_TIER_AMT4;
            }
            set
            {
                this._BASIC_TIER_AMT4 = value;
            }
        }

        /// <summary>
        /// BASIC_TIER_RATE4
        /// </summary>
        [AttributeField("BASIC_TIER_RATE4", "System.String", false, false, false, "String")]
        public string BASIC_TIER_RATE4
        {
            get
            {
                return this._BASIC_TIER_RATE4;
            }
            set
            {
                this._BASIC_TIER_RATE4 = value;
            }
        }

        /// <summary>
        /// SUPP_BASIC_TIER_AMT4
        /// </summary>
        [AttributeField("SUPP_BASIC_TIER_AMT4", "System.String", false, false, false, "String")]
        public string SUPP_BASIC_TIER_AMT4
        {
            get
            {
                return this._SUPP_BASIC_TIER_AMT4;
            }
            set
            {
                this._SUPP_BASIC_TIER_AMT4 = value;
            }
        }

        /// <summary>
        /// SUPP_BASIC_TIER_RATE4
        /// </summary>
        [AttributeField("SUPP_BASIC_TIER_RATE4", "System.String", false, false, false, "String")]
        public string SUPP_BASIC_TIER_RATE4
        {
            get
            {
                return this._SUPP_BASIC_TIER_RATE4;
            }
            set
            {
                this._SUPP_BASIC_TIER_RATE4 = value;
            }
        }

        /// <summary>
        /// PROMO_TIER_AMT4
        /// </summary>
        [AttributeField("PROMO_TIER_AMT4", "System.String", false, false, false, "String")]
        public string PROMO_TIER_AMT4
        {
            get
            {
                return this._PROMO_TIER_AMT4;
            }
            set
            {
                this._PROMO_TIER_AMT4 = value;
            }
        }

        /// <summary>
        /// PROMO_TIER_RATE4
        /// </summary>
        [AttributeField("PROMO_TIER_RATE4", "System.String", false, false, false, "String")]
        public string PROMO_TIER_RATE4
        {
            get
            {
                return this._PROMO_TIER_RATE4;
            }
            set
            {
                this._PROMO_TIER_RATE4 = value;
            }
        }

        /// <summary>
        /// BTHDTE_TIER_AMT4
        /// </summary>
        [AttributeField("BTHDTE_TIER_AMT4", "System.String", false, false, false, "String")]
        public string BTHDTE_TIER_AMT4
        {
            get
            {
                return this._BTHDTE_TIER_AMT4;
            }
            set
            {
                this._BTHDTE_TIER_AMT4 = value;
            }
        }

        /// <summary>
        /// BTHDTE_TIER_RATE4
        /// </summary>
        [AttributeField("BTHDTE_TIER_RATE4", "System.String", false, false, false, "String")]
        public string BTHDTE_TIER_RATE4
        {
            get
            {
                return this._BTHDTE_TIER_RATE4;
            }
            set
            {
                this._BTHDTE_TIER_RATE4 = value;
            }
        }

        /// <summary>
        /// SEND_FLAG
        /// </summary>
        [AttributeField("SEND_FLAG", "System.String", false, false, false, "String")]
        public string SEND_FLAG
        {
            get
            {
                return this._SEND_FLAG;
            }
            set
            {
                this._SEND_FLAG = value;
            }
        }
    }

    /// <summary>
    /// AwardSet3270
    /// </summary>
    [Serializable()]
    public class EntityAwardSet3270Set : EntitySet<EntityAwardSet3270>
    {
    }
}
