//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPKeyInGUI.EntityLayer
{
    
    
    /// <summary>
    /// szip
    /// </summary>
    [Serializable()]
    [AttributeTable("szip")]
    public class EntitySZIP : Entity
    {
        
        private string _zip_code;
        
        /// <summary>
        /// zip_code
        /// </summary>
        public static string M_zip_code = "zip_code";
        
        private string _zip_data;
        
        /// <summary>
        /// zip_data
        /// </summary>
        public static string M_zip_data = "zip_data";
        
        /// <summary>
        /// zip_code
        /// </summary>
        [AttributeField("zip_code", "System.String", false, true, false, "String")]
        public string zip_code
        {
            get
            {
                return this._zip_code;
            }
            set
            {
                this._zip_code = value;
            }
        }
        
        /// <summary>
        /// zip_data
        /// </summary>
        [AttributeField("zip_data", "System.String", false, false, false, "String")]
        public string zip_data
        {
            get
            {
                return this._zip_data;
            }
            set
            {
                this._zip_data = value;
            }
        }
    }
    
    /// <summary>
    /// szip
    /// </summary>
    [Serializable()]
    public class EntitySZIPSet : EntitySet<EntitySZIP>
    {
    }
}
