//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPKeyInGUI.EntityLayer
{
    
    
    /// <summary>
    /// shop_Upload
    /// </summary>
    [Serializable()]
    [AttributeTable("shop_Upload")]
    public class EntitySHOP_UPLOAD : Entity
    {
        
        private string _shop_id;
        
        /// <summary>
        /// shop_id
        /// </summary>
        public static string M_shop_id = "shop_id";
        
        private string _Change_Item;
        
        /// <summary>
        /// Change_Item
        /// </summary>
        public static string M_Change_Item = "Change_Item";
        
        private string _KeyIn_Flag;
        
        /// <summary>
        /// KeyIn_Flag
        /// </summary>
        public static string M_KeyIn_Flag = "KeyIn_Flag";
        
        private string _user_id;
        
        /// <summary>
        /// user_id
        /// </summary>
        public static string M_user_id = "user_id";
        
        private string _mod_date;
        
        /// <summary>
        /// mod_date
        /// </summary>
        public static string M_mod_date = "mod_date";
        
        private string _mod_time;
        
        /// <summary>
        /// mod_time
        /// </summary>
        public static string M_mod_time = "mod_time";
        
        /// <summary>
        /// shop_id
        /// </summary>
        [AttributeField("shop_id", "System.String", false, false, false, "String")]
        public string shop_id
        {
            get
            {
                return this._shop_id;
            }
            set
            {
                this._shop_id = value;
            }
        }
        
        /// <summary>
        /// Change_Item
        /// </summary>
        [AttributeField("Change_Item", "System.String", false, false, false, "String")]
        public string Change_Item
        {
            get
            {
                return this._Change_Item;
            }
            set
            {
                this._Change_Item = value;
            }
        }
        
        /// <summary>
        /// KeyIn_Flag
        /// </summary>
        [AttributeField("KeyIn_Flag", "System.String", false, false, false, "String")]
        public string KeyIn_Flag
        {
            get
            {
                return this._KeyIn_Flag;
            }
            set
            {
                this._KeyIn_Flag = value;
            }
        }
        
        /// <summary>
        /// user_id
        /// </summary>
        [AttributeField("user_id", "System.String", false, false, false, "String")]
        public string user_id
        {
            get
            {
                return this._user_id;
            }
            set
            {
                this._user_id = value;
            }
        }
        
        /// <summary>
        /// mod_date
        /// </summary>
        [AttributeField("mod_date", "System.String", false, false, false, "String")]
        public string mod_date
        {
            get
            {
                return this._mod_date;
            }
            set
            {
                this._mod_date = value;
            }
        }
        
        /// <summary>
        /// mod_time
        /// </summary>
        [AttributeField("mod_time", "System.String", false, false, false, "String")]
        public string mod_time
        {
            get
            {
                return this._mod_time;
            }
            set
            {
                this._mod_time = value;
            }
        }
    }
    
    /// <summary>
    /// shop_Upload
    /// </summary>
    [Serializable()]
    public class EntitySHOP_UPLOADSet : EntitySet<EntitySHOP_UPLOAD>
    {
    }
}
