//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPKeyInGUI.EntityLayer
{
    
    
    /// <summary>
    /// Job_Status
    /// </summary>
    [Serializable()]
    [AttributeTable("Job_Status")]
    public class EntityJOB_STATUS : Entity
    {
        
        private string _job_name;
        
        /// <summary>
        /// job_name
        /// </summary>
        public static string M_job_name = "job_name";
        
        private string _job_status;
        
        /// <summary>
        /// job_status
        /// </summary>
        public static string M_job_status = "job_status";
        
        private object _start_time;
        
        /// <summary>
        /// start_time
        /// </summary>
        public static string M_start_time = "start_time";
        
        private object _end_time;
        
        /// <summary>
        /// end_time
        /// </summary>
        public static string M_end_time = "end_time";

        private object _data_count;

        /// <summary>
        /// data_count
        /// </summary>
        public static string M_data_count = "data_count";
        
        /// <summary>
        /// job_name
        /// </summary>
        [AttributeField("job_name", "System.String", false, false, false, "String")]
        public string job_name
        {
            get
            {
                return this._job_name;
            }
            set
            {
                this._job_name = value;
            }
        }
        
        /// <summary>
        /// job_status
        /// </summary>
        [AttributeField("job_status", "System.String", false, false, false, "String")]
        public string job_status
        {
            get
            {
                return this._job_status;
            }
            set
            {
                this._job_status = value;
            }
        }
        
        /// <summary>
        /// start_time
        /// </summary>
        [AttributeField("start_time", "System.DateTime", false, false, false, "DateTime")]
        public object start_time
        {
            get
            {
                return this._start_time;
            }
            set
            {
                this._start_time = value;
            }
        }
        
        /// <summary>
        /// end_time
        /// </summary>
        [AttributeField("end_time", "System.DateTime", false, false, false, "DateTime")]
        public object end_time
        {
            get
            {
                return this._end_time;
            }
            set
            {
                this._end_time = value;
            }
        }

        /// <summary>
        /// data_count
        /// </summary>
        [AttributeField("data_count", "System.Int32", false, false, false, "Int32")]
        public object data_count
        {
            get
            {
                return this._data_count;
            }
            set
            {
                this._data_count = value;
            }
        }
    }
    
    /// <summary>
    /// Job_Status
    /// </summary>
    [Serializable()]
    public class EntityJOB_STATUSSet : EntitySet<EntityJOB_STATUS>
    {
    }
}
