//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPKeyInGUI.EntityLayer
{
    
    
    /// <summary>
    /// Other_Bank_Temp
    /// </summary>
    [Serializable()]
    [AttributeTable("Other_Bank_Temp")]
    public class EntityOTHER_BANK_TEMP : Entity
    {
        
        private string _Cus_ID;
        
        /// <summary>
        /// Cus_ID
        /// </summary>
        public static string M_Cus_ID = "Cus_ID";


        private string _Cus_Name;

        /// <summary>
        /// Cus_Name
        /// </summary>
        public static string M_Cus_Name = "Cus_Name";


        private string _Other_Bank_Code_S;
        
        /// <summary>
        /// Other_Bank_Code_S
        /// </summary>
        public static string M_Other_Bank_Code_S = "Other_Bank_Code_S";
        
        private string _Other_Bank_Code_L;
        
        /// <summary>
        /// Other_Bank_Code_L
        /// </summary>
        public static string M_Other_Bank_Code_L = "Other_Bank_Code_L";
        
        private string _Other_Bank_Acc_No;
        
        /// <summary>
        /// Other_Bank_Acc_No
        /// </summary>
        public static string M_Other_Bank_Acc_No = "Other_Bank_Acc_No";
        
        private string _Other_Bank_Pay_Way;
        
        /// <summary>
        /// Other_Bank_Pay_Way
        /// </summary>
        public static string M_Other_Bank_Pay_Way = "Other_Bank_Pay_Way";
        
        private string _bcycle_code;
        
        /// <summary>
        /// bcycle_code
        /// </summary>
        public static string M_bcycle_code = "bcycle_code";
        
        private string _Mobile_Phone;
        
        /// <summary>
        /// Mobile_Phone
        /// </summary>
        public static string M_Mobile_Phone = "Mobile_Phone";
        
        private string _E_Mail;
        
        /// <summary>
        /// E_Mail
        /// </summary>
        public static string M_E_Mail = "E_Mail";
        
        private string _E_Bill;
        
        /// <summary>
        /// E_Bill
        /// </summary>
        public static string M_E_Bill = "E_Bill";
        
        private string _Build_Date;
        
        /// <summary>
        /// Build_Date
        /// </summary>
        public static string M_Build_Date = "Build_Date";
        
        private string _Receive_Number;
        
        /// <summary>
        /// Receive_Number
        /// </summary>
        public static string M_Receive_Number = "Receive_Number";
        
        private string _Other_Bank_Cus_ID;
        
        /// <summary>
        /// Other_Bank_Cus_ID
        /// </summary>
        public static string M_Other_Bank_Cus_ID = "Other_Bank_Cus_ID";
        
        private string _Apply_Type;
        
        /// <summary>
        /// Apply_Type
        /// </summary>
        public static string M_Apply_Type = "Apply_Type";
        
        private string _Deal_S_No;
        
        /// <summary>
        /// Deal_S_No
        /// </summary>
        public static string M_Deal_S_No = "Deal_S_No";
        
        private string _Deal_No;
        
        /// <summary>
        /// Deal_No
        /// </summary>
        public static string M_Deal_No = "Deal_No";
        
        private string _Acc_No_D;
        
        /// <summary>
        /// Acc_No_D
        /// </summary>
        public static string M_Acc_No_D = "Acc_No_D";
        
        private string _Acc_No_L;
        
        /// <summary>
        /// Acc_No_L
        /// </summary>
        public static string M_Acc_No_L = "Acc_No_L";
        
        private string _Acc_No;
        
        /// <summary>
        /// Acc_No
        /// </summary>
        public static string M_Acc_No = "Acc_No";
        
        private string _Pay_Way;
        
        /// <summary>
        /// Pay_Way
        /// </summary>
        public static string M_Pay_Way = "Pay_Way";
        
        private string _Acc_ID;
        
        /// <summary>
        /// Acc_ID
        /// </summary>
        public static string M_Acc_ID = "Acc_ID";
        
        private string _KeyIn_Flag;
        
        /// <summary>
        /// KeyIn_Flag
        /// </summary>
        public static string M_KeyIn_Flag = "KeyIn_Flag";
        
        private string _Upload_flag;
        
        /// <summary>
        /// Upload_flag
        /// </summary>
        public static string M_Upload_flag = "Upload_flag";
        
        private string _user_id;
        
        /// <summary>
        /// user_id
        /// </summary>
        public static string M_user_id = "user_id";
        
        private string _mod_date;
        
        /// <summary>
        /// mod_date
        /// </summary>
        public static string M_mod_date = "mod_date";
        
        private string _ACH_Return_Code;
        
        /// <summary>
        /// ACH_Return_Code
        /// </summary>
        public static string M_ACH_Return_Code = "ACH_Return_Code";
        
        private string _Pcmc_Return_Code;
        
        /// <summary>
        /// Pcmc_Return_Code
        /// </summary>
        public static string M_Pcmc_Return_Code = "Pcmc_Return_Code";
        
        private string _C1342_Return_Code;
        
        /// <summary>
        /// C1342_Return_Code
        /// </summary>
        public static string M_C1342_Return_Code = "C1342_Return_Code";
        
        private string _Batch_no;
        
        /// <summary>
        /// Batch_no
        /// </summary>
        public static string M_Batch_no = "Batch_no";
        
        private string _Oper_Flag;
        
        /// <summary>
        /// Oper_Flag
        /// </summary>
        public static string M_Oper_Flag = "Oper_Flag";
        
        private string _Pcmc_Upload_flag;
        
        /// <summary>
        /// Pcmc_Upload_flag
        /// </summary>
        public static string M_Pcmc_Upload_flag = "Pcmc_Upload_flag";
        
        private string _Auto_Pay_Setting;
        
        /// <summary>
        /// Auto_Pay_Setting
        /// </summary>
        public static string M_Auto_Pay_Setting = "Auto_Pay_Setting";
        
        private string _CellP_Email_Setting;
        
        /// <summary>
        /// CellP_Email_Setting
        /// </summary>
        public static string M_CellP_Email_Setting = "CellP_Email_Setting";
        
        private string _E_Bill_Setting;
        
        /// <summary>
        /// E_Bill_Setting
        /// </summary>
        public static string M_E_Bill_Setting = "E_Bill_Setting";
        
        private string _OutputByTXT_Setting;
        
        /// <summary>
        /// OutputByTXT_Setting
        /// </summary>
        public static string M_OutputByTXT_Setting = "OutputByTXT_Setting";
        
        private string _Acct_NBR;
        
        /// <summary>
        /// Acct_NBR
        /// </summary>
        public static string M_Acct_NBR = "Acct_NBR";

        private string _Ach_Batch_date;

        /// <summary>
        /// Ach_Batch_date
        /// </summary>
        public static string M_Ach_Batch_date = "Ach_Batch_date";

        private string _Ach_hold;

        /// <summary>
        /// Ach_hold
        /// </summary>
        public static string M_Ach_hold = "Ach_hold";

        /// <summary>
        /// Cus_ID
        /// </summary>
        [AttributeField("Cus_ID", "System.String", false, false, false, "String")]
        public string Cus_ID
        {
            get
            {
                return this._Cus_ID;
            }
            set
            {
                this._Cus_ID = value;
            }
        }

        /// <summary>
        /// Cus_Name
        /// </summary>
        [AttributeField("Cus_Name", "System.String", false, false, false, "String")]
        public string Cus_Name
        {
            get
            {
                return this._Cus_Name;
            }
            set
            {
                this._Cus_Name = value;
            }
        }

        /// <summary>
        /// Other_Bank_Code_S
        /// </summary>
        [AttributeField("Other_Bank_Code_S", "System.String", false, false, false, "String")]
        public string Other_Bank_Code_S
        {
            get
            {
                return this._Other_Bank_Code_S;
            }
            set
            {
                this._Other_Bank_Code_S = value;
            }
        }
        
        /// <summary>
        /// Other_Bank_Code_L
        /// </summary>
        [AttributeField("Other_Bank_Code_L", "System.String", false, false, false, "String")]
        public string Other_Bank_Code_L
        {
            get
            {
                return this._Other_Bank_Code_L;
            }
            set
            {
                this._Other_Bank_Code_L = value;
            }
        }
        
        /// <summary>
        /// Other_Bank_Acc_No
        /// </summary>
        [AttributeField("Other_Bank_Acc_No", "System.String", false, false, false, "String")]
        public string Other_Bank_Acc_No
        {
            get
            {
                return this._Other_Bank_Acc_No;
            }
            set
            {
                this._Other_Bank_Acc_No = value;
            }
        }
        
        /// <summary>
        /// Other_Bank_Pay_Way
        /// </summary>
        [AttributeField("Other_Bank_Pay_Way", "System.String", false, false, false, "String")]
        public string Other_Bank_Pay_Way
        {
            get
            {
                return this._Other_Bank_Pay_Way;
            }
            set
            {
                this._Other_Bank_Pay_Way = value;
            }
        }
        
        /// <summary>
        /// bcycle_code
        /// </summary>
        [AttributeField("bcycle_code", "System.String", false, false, false, "String")]
        public string bcycle_code
        {
            get
            {
                return this._bcycle_code;
            }
            set
            {
                this._bcycle_code = value;
            }
        }
        
        /// <summary>
        /// Mobile_Phone
        /// </summary>
        [AttributeField("Mobile_Phone", "System.String", false, false, false, "String")]
        public string Mobile_Phone
        {
            get
            {
                return this._Mobile_Phone;
            }
            set
            {
                this._Mobile_Phone = value;
            }
        }
        
        /// <summary>
        /// E_Mail
        /// </summary>
        [AttributeField("E_Mail", "System.String", false, false, false, "String")]
        public string E_Mail
        {
            get
            {
                return this._E_Mail;
            }
            set
            {
                this._E_Mail = value;
            }
        }
        
        /// <summary>
        /// E_Bill
        /// </summary>
        [AttributeField("E_Bill", "System.String", false, false, false, "String")]
        public string E_Bill
        {
            get
            {
                return this._E_Bill;
            }
            set
            {
                this._E_Bill = value;
            }
        }
        
        /// <summary>
        /// Build_Date
        /// </summary>
        [AttributeField("Build_Date", "System.String", false, false, false, "String")]
        public string Build_Date
        {
            get
            {
                return this._Build_Date;
            }
            set
            {
                this._Build_Date = value;
            }
        }
        
        /// <summary>
        /// Receive_Number
        /// </summary>
        [AttributeField("Receive_Number", "System.String", false, false, false, "String")]
        public string Receive_Number
        {
            get
            {
                return this._Receive_Number;
            }
            set
            {
                this._Receive_Number = value;
            }
        }
        
        /// <summary>
        /// Other_Bank_Cus_ID
        /// </summary>
        [AttributeField("Other_Bank_Cus_ID", "System.String", false, false, false, "String")]
        public string Other_Bank_Cus_ID
        {
            get
            {
                return this._Other_Bank_Cus_ID;
            }
            set
            {
                this._Other_Bank_Cus_ID = value;
            }
        }
        
        /// <summary>
        /// Apply_Type
        /// </summary>
        [AttributeField("Apply_Type", "System.String", false, false, false, "String")]
        public string Apply_Type
        {
            get
            {
                return this._Apply_Type;
            }
            set
            {
                this._Apply_Type = value;
            }
        }
        
        /// <summary>
        /// Deal_S_No
        /// </summary>
        [AttributeField("Deal_S_No", "System.String", false, false, false, "String")]
        public string Deal_S_No
        {
            get
            {
                return this._Deal_S_No;
            }
            set
            {
                this._Deal_S_No = value;
            }
        }
        
        /// <summary>
        /// Deal_No
        /// </summary>
        [AttributeField("Deal_No", "System.String", false, false, false, "String")]
        public string Deal_No
        {
            get
            {
                return this._Deal_No;
            }
            set
            {
                this._Deal_No = value;
            }
        }
        
        /// <summary>
        /// Acc_No_D
        /// </summary>
        [AttributeField("Acc_No_D", "System.String", false, false, false, "String")]
        public string Acc_No_D
        {
            get
            {
                return this._Acc_No_D;
            }
            set
            {
                this._Acc_No_D = value;
            }
        }
        
        /// <summary>
        /// Acc_No_L
        /// </summary>
        [AttributeField("Acc_No_L", "System.String", false, false, false, "String")]
        public string Acc_No_L
        {
            get
            {
                return this._Acc_No_L;
            }
            set
            {
                this._Acc_No_L = value;
            }
        }
        
        /// <summary>
        /// Acc_No
        /// </summary>
        [AttributeField("Acc_No", "System.String", false, false, false, "String")]
        public string Acc_No
        {
            get
            {
                return this._Acc_No;
            }
            set
            {
                this._Acc_No = value;
            }
        }
        
        /// <summary>
        /// Pay_Way
        /// </summary>
        [AttributeField("Pay_Way", "System.String", false, false, false, "String")]
        public string Pay_Way
        {
            get
            {
                return this._Pay_Way;
            }
            set
            {
                this._Pay_Way = value;
            }
        }
        
        /// <summary>
        /// Acc_ID
        /// </summary>
        [AttributeField("Acc_ID", "System.String", false, false, false, "String")]
        public string Acc_ID
        {
            get
            {
                return this._Acc_ID;
            }
            set
            {
                this._Acc_ID = value;
            }
        }
        
        /// <summary>
        /// KeyIn_Flag
        /// </summary>
        [AttributeField("KeyIn_Flag", "System.String", false, false, false, "String")]
        public string KeyIn_Flag
        {
            get
            {
                return this._KeyIn_Flag;
            }
            set
            {
                this._KeyIn_Flag = value;
            }
        }
        
        /// <summary>
        /// Upload_flag
        /// </summary>
        [AttributeField("Upload_flag", "System.String", false, false, false, "String")]
        public string Upload_flag
        {
            get
            {
                return this._Upload_flag;
            }
            set
            {
                this._Upload_flag = value;
            }
        }
        
        /// <summary>
        /// user_id
        /// </summary>
        [AttributeField("user_id", "System.String", false, false, false, "String")]
        public string user_id
        {
            get
            {
                return this._user_id;
            }
            set
            {
                this._user_id = value;
            }
        }
        
        /// <summary>
        /// mod_date
        /// </summary>
        [AttributeField("mod_date", "System.String", false, false, false, "String")]
        public string mod_date
        {
            get
            {
                return this._mod_date;
            }
            set
            {
                this._mod_date = value;
            }
        }
        
        /// <summary>
        /// ACH_Return_Code
        /// </summary>
        [AttributeField("ACH_Return_Code", "System.String", false, false, false, "String")]
        public string ACH_Return_Code
        {
            get
            {
                return this._ACH_Return_Code;
            }
            set
            {
                this._ACH_Return_Code = value;
            }
        }
        
        /// <summary>
        /// Pcmc_Return_Code
        /// </summary>
        [AttributeField("Pcmc_Return_Code", "System.String", false, false, false, "String")]
        public string Pcmc_Return_Code
        {
            get
            {
                return this._Pcmc_Return_Code;
            }
            set
            {
                this._Pcmc_Return_Code = value;
            }
        }
        
        /// <summary>
        /// C1342_Return_Code
        /// </summary>
        [AttributeField("C1342_Return_Code", "System.String", false, false, false, "String")]
        public string C1342_Return_Code
        {
            get
            {
                return this._C1342_Return_Code;
            }
            set
            {
                this._C1342_Return_Code = value;
            }
        }
        
        /// <summary>
        /// Batch_no
        /// </summary>
        [AttributeField("Batch_no", "System.String", false, false, false, "String")]
        public string Batch_no
        {
            get
            {
                return this._Batch_no;
            }
            set
            {
                this._Batch_no = value;
            }
        }
        
        /// <summary>
        /// Oper_Flag
        /// </summary>
        [AttributeField("Oper_Flag", "System.String", false, false, false, "String")]
        public string Oper_Flag
        {
            get
            {
                return this._Oper_Flag;
            }
            set
            {
                this._Oper_Flag = value;
            }
        }
        
        /// <summary>
        /// Pcmc_Upload_flag
        /// </summary>
        [AttributeField("Pcmc_Upload_flag", "System.String", false, false, false, "String")]
        public string Pcmc_Upload_flag
        {
            get
            {
                return this._Pcmc_Upload_flag;
            }
            set
            {
                this._Pcmc_Upload_flag = value;
            }
        }
        
        /// <summary>
        /// Auto_Pay_Setting
        /// </summary>
        [AttributeField("Auto_Pay_Setting", "System.String", false, false, false, "String")]
        public string Auto_Pay_Setting
        {
            get
            {
                return this._Auto_Pay_Setting;
            }
            set
            {
                this._Auto_Pay_Setting = value;
            }
        }
        
        /// <summary>
        /// CellP_Email_Setting
        /// </summary>
        [AttributeField("CellP_Email_Setting", "System.String", false, false, false, "String")]
        public string CellP_Email_Setting
        {
            get
            {
                return this._CellP_Email_Setting;
            }
            set
            {
                this._CellP_Email_Setting = value;
            }
        }
        
        /// <summary>
        /// E_Bill_Setting
        /// </summary>
        [AttributeField("E_Bill_Setting", "System.String", false, false, false, "String")]
        public string E_Bill_Setting
        {
            get
            {
                return this._E_Bill_Setting;
            }
            set
            {
                this._E_Bill_Setting = value;
            }
        }
        
        /// <summary>
        /// OutputByTXT_Setting
        /// </summary>
        [AttributeField("OutputByTXT_Setting", "System.String", false, false, false, "String")]
        public string OutputByTXT_Setting
        {
            get
            {
                return this._OutputByTXT_Setting;
            }
            set
            {
                this._OutputByTXT_Setting = value;
            }
        }
        
        /// <summary>
        /// Acct_NBR
        /// </summary>
        [AttributeField("Acct_NBR", "System.String", false, false, false, "String")]
        public string Acct_NBR
        {
            get
            {
                return this._Acct_NBR;
            }
            set
            {
                this._Acct_NBR = value;
            }
        }

        /// <summary>
        /// Ach_Batch_date
        /// </summary>
        [AttributeField("Ach_Batch_date", "System.String", false, false, false, "String")]
        public string Ach_Batch_date
        {
            get
            {
                return this._Ach_Batch_date;
            }
            set
            {
                this._Ach_Batch_date = value;
            }
        }

        /// <summary>
        /// Ach_hold
        /// </summary>
        [AttributeField("Ach_hold", "System.String", false, false, false, "String")]
        public string Ach_hold
        {
            get
            {
                return this._Ach_hold;
            }
            set
            {
                this._Ach_hold = value;
            }
        }
        
    }
    
    /// <summary>
    /// Other_Bank_Temp
    /// </summary>
    [Serializable()]
    public class Other_Bank_TempSet : EntitySet<EntityOTHER_BANK_TEMP>
    {
    }
}
