//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPKeyInGUI.EntityLayer
{
    
    
    /// <summary>
    /// ProgramList
    /// </summary>
    [Serializable()]
    [AttributeTable("ProgramList")]
    public class EntityProgramList : Entity
    {
        
        private string _CODE;
        
        /// <summary>
        /// CODE
        /// </summary>
        public static string M_CODE = "CODE";
        
        private string _MEMO;
        
        /// <summary>
        /// MEMO
        /// </summary>
        public static string M_MEMO = "MEMO";
        
        /// <summary>
        /// CODE
        /// </summary>
        [AttributeField("CODE", "System.String", false, false, false, "String")]
        public string CODE
        {
            get
            {
                return this._CODE;
            }
            set
            {
                this._CODE = value;
            }
        }
        
        /// <summary>
        /// MEMO
        /// </summary>
        [AttributeField("MEMO", "System.String", false, false, false, "String")]
        public string MEMO
        {
            get
            {
                return this._MEMO;
            }
            set
            {
                this._MEMO = value;
            }
        }
    }
    
    /// <summary>
    /// ProgramList
    /// </summary>
    [Serializable()]
    public class EntityProgramListSet : EntitySet<EntityProgramList>
    {
    }
}
